/*
 * Copyright (C) 2024-present Puter Technologies Inc.
 *
 * This file is part of Puter.
 *
 * Puter is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import type { IChatModel } from '../../types.js';

// Hardcoded from https://models.dev/api.json (Groq chat/text models)
export const GROQ_MODELS: IChatModel[] = [
    {
        puterId: 'groq:llama-3.1-8b-instant',
        id: 'llama-3.1-8b-instant',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        release_date: '2024-07-23',
        name: 'Llama 3.1 8B Instant',
        aliases: ['llama-3.1-8b-instant'],
        context: 131072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 5,
            completion_tokens: 8,
            cached_tokens: 0,
        },
        max_tokens: 131072,
    },
    {
        puterId: 'groq:llama-3.3-70b-versatile',
        id: 'llama-3.3-70b-versatile',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        release_date: '2024-12-06',
        name: 'Llama 3.3 70B Versatile',
        aliases: ['llama-3.3-70b-versatile'],
        context: 131072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 59,
            completion_tokens: 79,
            cached_tokens: 0,
        },
        max_tokens: 32768,
    },
    {
        puterId: 'groq:openai/gpt-oss-120b',
        id: 'openai/gpt-oss-120b',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        release_date: '2025-08-05',
        name: 'GPT OSS 120B',
        aliases: ['openai/gpt-oss-120b'],
        context: 131072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 15,
            completion_tokens: 60,
            cached_tokens: 8,
        },
        max_tokens: 65536,
    },
    {
        puterId: 'groq:openai/gpt-oss-20b',
        id: 'openai/gpt-oss-20b',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        release_date: '2025-08-05',
        name: 'GPT OSS 20B',
        aliases: ['openai/gpt-oss-20b'],
        context: 131072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 8,
            completion_tokens: 30,
            cached_tokens: 4,
        },
        max_tokens: 65536,
    },
    {
        puterId: 'groq:openai/gpt-oss-safeguard-20b',
        id: 'openai/gpt-oss-safeguard-20b',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        release_date: '2025-10-29',
        name: 'GPT OSS Safeguard 20B',
        aliases: ['openai/gpt-oss-safeguard-20b'],
        context: 131072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 8,
            completion_tokens: 30,
            cached_tokens: 0,
        },
        max_tokens: 65536,
    },
    {
        puterId: 'groq:groq/compound',
        id: 'groq/compound',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: false,
        release_date: '2025-09-04',
        name: 'Groq Compound',
        aliases: ['groq/compound'],
        context: 131072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 0,
            completion_tokens: 0,
            cached_tokens: 0,
        },
        max_tokens: 8192,
    },
    {
        puterId: 'groq:groq/compound-mini',
        id: 'groq/compound-mini',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: false,
        release_date: '2025-09-04',
        name: 'Groq Compound Mini',
        aliases: ['groq/compound-mini'],
        context: 131072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 0,
            completion_tokens: 0,
            cached_tokens: 0,
        },
        max_tokens: 8192,
    },
    {
        puterId: 'groq:qwen/qwen3.6-27b',
        id: 'qwen/qwen3.6-27b',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        release_date: '2026-04-22',
        name: 'Qwen3.6 27B',
        aliases: ['qwen/qwen3.6-27b'],
        context: 131072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 60,
            completion_tokens: 300,
            cached_tokens: 30,
        },
        max_tokens: 16384,
    },
    {
        puterId: 'groq:meta-llama/llama-prompt-guard-2-22m',
        id: 'meta-llama/llama-prompt-guard-2-22m',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: false,
        release_date: '2025-05-29',
        name: 'Llama Prompt Guard 2 22M',
        aliases: ['meta-llama/llama-prompt-guard-2-22m'],
        context: 512,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 3,
            completion_tokens: 3,
            cached_tokens: 0,
        },
        max_tokens: 512,
    },
    {
        puterId: 'groq:meta-llama/llama-prompt-guard-2-86m',
        id: 'meta-llama/llama-prompt-guard-2-86m',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: false,
        release_date: '2025-05-29',
        name: 'Llama Prompt Guard 2 86M',
        aliases: ['meta-llama/llama-prompt-guard-2-86m'],
        context: 512,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 4,
            completion_tokens: 4,
            cached_tokens: 0,
        },
        max_tokens: 512,
    },
    {
        puterId: 'groq:allam-2-7b',
        id: 'allam-2-7b',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: false,
        release_date: '2025-01-23',
        name: 'ALLaM 2 7B',
        aliases: ['allam-2-7b'],
        context: 4096,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 0,
            completion_tokens: 0,
            cached_tokens: 0,
        },
        max_tokens: 4096,
    },
    {
        puterId: 'groq:meta-llama/llama-guard-4-12b',
        id: 'meta-llama/llama-guard-4-12b',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: true,
        tool_call: false,
        release_date: '2025-04-05',
        name: 'Llama Guard 4 12B',
        aliases: ['meta-llama/llama-guard-4-12b'],
        context: 131072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 20,
            completion_tokens: 20,
            cached_tokens: 0,
        },
        max_tokens: 1024,
    },
];
