import { IChatModel } from '../types.js';

// Hardcoded from https://models.dev/api.json
export const XAI_MODELS: IChatModel[] = [
    {
        puterId: 'x-ai:x-ai/grok-beta',
        id: 'grok-beta',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-08',
        release_date: '2024-11-01',
        name: 'Grok Beta',
        aliases: ['x-ai/grok-beta'],
        context: 131072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 500,
            completion_tokens: 1500,
        },
        max_tokens: 131072,
    },
    {
        puterId: 'x-ai:x-ai/grok-vision-beta',
        id: 'grok-vision-beta',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-08',
        release_date: '2024-11-01',
        name: 'Grok Vision Beta',
        aliases: ['x-ai/grok-vision-beta'],
        context: 8192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 500,
            completion_tokens: 1500,
        },
        max_tokens: 8192,
    },
    {
        puterId: 'x-ai:x-ai/grok-3',
        id: 'grok-3',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-11',
        release_date: '2025-02-17',
        name: 'Grok 3',
        aliases: ['x-ai/grok-3'],
        context: 131072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 300,
            completion_tokens: 1500,
            // Cached tokens billed at 0.75 cents / 1M tokens = 0.75 micro-cents / token
            cached_tokens: 0.75,
        },
        max_tokens: 131072,
    },
    {
        puterId: 'x-ai:x-ai/grok-3-fast',
        id: 'grok-3-fast',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-11',
        release_date: '2025-02-17',
        name: 'Grok 3 Fast',
        aliases: ['x-ai/grok-3-fast'],
        context: 131072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 500,
            completion_tokens: 2500,
        },
        max_tokens: 131072,
    },
    {
        puterId: 'x-ai:x-ai/grok-3-mini',
        id: 'grok-3-mini',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-11',
        release_date: '2025-02-17',
        name: 'Grok 3 Mini',
        aliases: ['x-ai/grok-3-mini'],
        context: 131072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 30,
            completion_tokens: 50,
            // Cached tokens billed at 0.075 cents / 1M tokens = 0.075 micro-cents / token
            cached_tokens: 0.075,
        },
        max_tokens: 131072,
    },
    {
        puterId: 'x-ai:x-ai/grok-3-mini-fast',
        id: 'grok-3-mini-fast',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-11',
        release_date: '2025-02-17',
        name: 'Grok 3 Mini Fast',
        aliases: ['x-ai/grok-3-mini-fast'],
        context: 131072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 60,
            completion_tokens: 400,
            // https://www.oracle.com/artificial-intelligence/generative-ai/generative-ai-service/pricing/ is the only place I could find this??
            cached_tokens: 15,
        },
        max_tokens: 131072,
    },
    {
        puterId: 'x-ai:x-ai/grok-2-vision',
        id: 'grok-2-vision',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-08',
        release_date: '2024-08-20',
        name: 'Grok 2 Vision',
        aliases: ['x-ai/grok-2-vision'],
        context: 8192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 200,
            completion_tokens: 1000,
            // No cache supported
            cached_tokens: 0,
        },
        max_tokens: 8192,
    },
    {
        puterId: 'x-ai:x-ai/grok-4-1-fast',
        id: 'grok-4-1-fast',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-07',
        release_date: '2025-11-19',
        name: 'Grok 4.1 Fast (Reasoning)',
        aliases: ['x-ai/grok-4-1-fast', 'grok-4-1-fast-reasoning'],
        context: 2_000_000,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 20,
            completion_tokens: 50,
            // Cached tokens billed at 5 cents / 1M tokens = 5 micro-cents / token
            cached_tokens: 5,
        },
        max_tokens: 2_000_000,
    },
    {
        puterId: 'x-ai:x-ai/grok-4-1-fast-non-reasoning',
        id: 'grok-4-1-fast-non-reasoning',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-07',
        release_date: '2025-11-19',
        name: 'Grok 4.1 Fast (Non-Reasoning)',
        aliases: ['x-ai/grok-4-1-fast-non-reasoning'],
        context: 2_000_000,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 20,
            completion_tokens: 50,
            // Cached tokens billed at 5 cents / 1M tokens = 5 micro-cents / token
            cached_tokens: 5,
        },
        max_tokens: 2_000_000,
    },
    {
        puterId: 'x-ai:x-ai/grok-code-fast-1',
        id: 'grok-code-fast-1',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2023-10',
        release_date: '2025-08-28',
        name: 'Grok Code Fast 1',
        aliases: ['x-ai/grok-code-fast-1'],
        context: 256_000,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 20,
            completion_tokens: 150,
            // Cached tokens billed at 2 cents / 1M tokens = 2 micro-cents / token
            cached_tokens: 2,
        },
        max_tokens: 256_000,
    },
    {
        puterId: 'x-ai:x-ai/grok-4-fast',
        id: 'grok-4-fast',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-07',
        release_date: '2025-09-19',
        name: 'Grok 4 Fast (Reasoning)',
        aliases: ['x-ai/grok-4-fast', 'grok-4-fast-reasoning'],
        context: 2_000_000,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 20,
            completion_tokens: 50,
            // Cached tokens billed at 5 cents / 1M tokens = 5 micro-cents / token
            cached_tokens: 5,
        },
        max_tokens: 2_000_000,
    },
    {
        puterId: 'x-ai:x-ai/grok-4-fast-non-reasoning',
        id: 'grok-4-fast-non-reasoning',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-07',
        release_date: '2025-09-19',
        name: 'Grok 4 Fast (Non-Reasoning)',
        aliases: ['x-ai/grok-4-fast-non-reasoning'],
        context: 2_000_000,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 20,
            completion_tokens: 50,
            // Cached tokens billed at 5 cents / 1M tokens = 5 micro-cents / token
            cached_tokens: 5,
        },
        max_tokens: 2_000_000,
    },
    {
        puterId: 'x-ai:x-ai/grok-4-0709',
        id: 'grok-4-0709',
        // Not present in models.dev/api.json (as of 2026-02-11); values below follow xAI pricing page.
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-07',
        release_date: '2025-07-09',
        name: 'Grok 4 (0709)',
        aliases: ['x-ai/grok-4-0709'],
        context: 256_000,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 300,
            completion_tokens: 1500,
            // Cached tokens billed at 75 cents / 1M tokens = 75 micro-cents / token
            cached_tokens: 75,
        },
        max_tokens: 256_000,
    },
    {
        puterId: 'x-ai:x-ai/grok-4',
        id: 'grok-4',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-07',
        release_date: '2025-07-09',
        name: 'Grok 4',
        aliases: ['x-ai/grok-4'],
        context: 256_000,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 300,
            completion_tokens: 1500,
            // Cached tokens billed at 75 cents / 1M tokens = 75 micro-cents / token
            cached_tokens: 75,
        },
        max_tokens: 256_000,
    },
    {
        puterId: 'x-ai:x-ai/grok-2-vision-1212',
        id: 'grok-2-vision-1212',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-08',
        release_date: '2024-08-20',
        name: 'Grok 2 Vision (1212)',
        aliases: ['x-ai/grok-2-vision-1212'],
        context: 32_768,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 200,
            completion_tokens: 1000,
            // No cache supported
            cached_tokens: 0,
        },
        max_tokens: 32_768,
    },
];
