import path from 'path-browserify';

/** @typedef {import('../../types/modules/fs-item').FSItem} FSItemType */

/**
 * A file or a directory in the Puter file system. Accepts an entry in any of
 * the shapes the API returns it in (`is_dir`, `fsentry_is_dir`, …).
 */
class FSItem {
    // Declared rather than left to inference: the constructor reads each one
    // off a loosely-typed entry, which would otherwise make them all
    // `unknown` to consumers.

    /**
     * Signed URL the file's contents can be read from.
     *
     * @type {string | undefined}
     */
    readURL;

    /**
     * Signed URL the file's contents can be written to.
     *
     * @type {string | undefined}
     */
    writeURL;

    /**
     * Signed URL the item's metadata can be read from.
     *
     * @type {string | undefined}
     */
    metadataURL;

    /**
     * The name of the item.
     *
     * @type {string}
     */
    name;

    /** @type {string} */
    uid;

    /**
     * The unique identifier of the item, generated by Puter when the item is
     * created.
     *
     * @type {string}
     */
    id;

    /** @type {string} */
    uuid;

    /**
     * The path of the item, relative to the root directory of the file system.
     *
     * @type {string}
     */
    path;

    /**
     * The size of the item in bytes. `null` if the item is a directory.
     *
     * @type {number | null}
     */
    size;

    /**
     * Unix timestamp of when the item was last accessed.
     *
     * @type {number | undefined}
     */
    accessed;

    /**
     * Unix timestamp of when the item was last modified.
     *
     * @type {number | undefined}
     */
    modified;

    /**
     * Unix timestamp of when the item was created.
     *
     * @type {number | undefined}
     */
    created;

    /**
     * Whether the item is a directory. `true` for a directory, `false` for a
     * file.
     *
     * @type {boolean}
     */
    isDir;

    /**
     * Alias of `isDir`, kept for backward compatibility.
     *
     * @type {boolean}
     */
    isDirectory;

    /** @param {Record<string, unknown>} options */
    constructor (options) {
        this.readURL = options.readURL ?? options.read_url;
        this.writeURL = options.writeURL ?? options.write_url;
        this.metadataURL = options.metadataURL ?? options.metadata_url;
        this.name = options.name ?? options.fsentry_name;
        this.uid = options.uid ?? options.uuid ?? options.fsentry_uid ?? options.fsentry_id ?? options.fsentry_uuid ?? options.id;
        this.id = this.uid;
        this.uuid = this.uid;
        this.path = options.path ?? options.fsentry_path;
        this.size = options.size ?? options.fsentry_size;
        this.accessed = options.accessed ?? options.fsentry_accessed;
        this.modified = options.modified ?? options.fsentry_modified;
        this.created = options.created ?? options.fsentry_created;
        this.isDirectory = (options.isDirectory || options.isDir || options.is_dir || options.fsentry_is_dir) ? true : false;
        // `isDir` is the documented name; `isDirectory` predates it and stays.
        this.isDir = this.isDirectory;

        // We add some properties to '_internalProperties' to make it clear
        // that they are not meant to be accessed outside of puter.js;
        // this permits us to change or remove these properties in the future.
        const internalProperties = {};
        Object.defineProperty(this, '_internalProperties', {
            enumerable: false,
            value: internalProperties,
        });

        // Currently 'signature' and 'expires' are not provided in 'options',
        // but they can be inferred by writeURL or readURL.
        internalProperties.signature = options.signature ?? (() => {
            const url = new URL(/** @type {string} */ (this.writeURL ?? this.readURL));
            return url.searchParams.get('signature');
        })();
        internalProperties.expires = options.expires ?? (() => {
            const url = new URL(/** @type {string} */ (this.writeURL ?? this.readURL));
            return url.searchParams.get('expires');
        })();

        // This computed property gives us an object in the format output by
        // the `/sign` endpoint, which can be passed to `launch_app` to
        // allow apps to open a file in another app or another instance.
        Object.defineProperty(internalProperties, 'file_signature', {
            get: () => ({
                read_url: this.readURL,
                write_url: this.writeURL,
                metadata_url: this.metadataURL,
                fsentry_accessed: this.accessed,
                fsentry_modified: this.modified,
                fsentry_created: this.created,
                fsentry_is_dir: this.isDirectory,
                fsentry_size: this.size,
                fsentry_name: this.name,
                path: this.path,
                uid: this.uid,
                // /sign outputs another property called "type", but we don't
                // have that information here, so it's omitted.
            }),
        });
    }

    /**
     * Writes data to the file, replacing its contents.
     *
     * @param {string | File | Blob | ArrayBuffer | ArrayBufferView} data
     * @returns {Promise<FSItemType>}
     */
    write = async function (data) {
        return puter.fs.write(this.path, data, {
            overwrite: true,
            dedupeName: false,
        });
    };

    // -- Not implemented yet --
    // These are part of the published surface but are still stubs: they accept
    // their arguments and do nothing. Declared in types/modules/fs-item.d.ts
    // as placeholders too.

    /**
     * Would call `callback` with the item whenever it changes.
     *
     * @type {(callback: (item: FSItemType) => void) => void}
     */
    watch = function (callback) {
        // todo - implement
    };

    /**
     * Would open the item in its associated app.
     *
     * @type {(callback: (item: FSItemType) => void) => void}
     */
    open = function (callback) {
        // todo - implement
    };

    /**
     * Would set the item as the desktop wallpaper.
     *
     * @type {(options?: Record<string, unknown>, callback?: () => void) => void}
     */
    setAsWallpaper = function (options, callback) {
        // todo - implement
    };

    /**
     * Renames the item.
     *
     * @param {string} newName
     * @returns {Promise<FSItemType>}
     */
    rename = function (newName) {
        // Address by uid when we have one: the item may have been moved since
        // this object was handed out, but its uid never changes.
        return puter.fs.rename(this.uid !== undefined
            ? { uid: this.uid, newName }
            : { path: this.path, newName });
    };

    /**
     * Moves the item to `destination`, which is either the directory to move
     * it into or the item's new path.
     *
     * @param {string} destination
     * @param {boolean} [overwrite]
     * @param {string} [newName]
     * @returns {Promise<FSItemType>}
     */
    move = function (destination, overwrite = false, newName) {
        return puter.fs.move(this.path, destination, { overwrite, newName });
    };

    /**
     * Copies the item into `destinationDirectory`.
     *
     * @param {string} destinationDirectory
     * @param {boolean} [autoRename] pick a free name instead of conflicting
     * @param {boolean} [overwrite]
     * @returns {Promise<FSItemType>}
     */
    copy = function (destinationDirectory, autoRename, overwrite = false) {
        return puter.fs.copy(this.path, destinationDirectory, {
            // Only sent when the caller asked for it, so the default copy
            // keeps sending the payload it always has.
            dedupeName: autoRename,
            overwrite,
        });
    };

    /**
     * Deletes the item.
     *
     * @returns {Promise<void>}
     */
    delete = function () {
        return puter.fs.delete(this.path);
    };

    /**
     * Would list the item's previous versions. Not implemented yet.
     *
     * @type {() => Promise<unknown>}
     */
    versions = async function () {
        // todo - implement
    };

    /**
     * Would move the item to the trash. Not implemented yet.
     *
     * @type {() => void}
     */
    trash = function () {
        // todo make sure puter allows for moving to trash by default
        // todo implement trashing
    };

    /**
     * Creates a subdirectory inside this directory.
     *
     * @param {string} name
     * @param {boolean} [autoRename] pick a free name instead of conflicting
     * @returns {Promise<FSItemType>}
     */
    mkdir = async function (name, autoRename = false) {
        // Don't proceed if this is not a directory, throw error
        if ( ! this.isDirectory )
        {
            throw new Error('mkdir() can only be called on a directory');
        }

        return puter.fs.mkdir(path.join(this.path, name), { dedupeName: autoRename });
    };

    /**
     * Would return the item's metadata. Not implemented yet.
     *
     * @type {() => Promise<unknown>}
     */
    metadata = async function () {
        // todo - implement
    };

    /**
     * Lists the contents of this directory.
     *
     * @returns {Promise<FSItemType[]>}
     */
    readdir = async function () {
        // Don't proceed if this is not a directory, throw error
        if ( ! this.isDirectory )
        {
            throw new Error('readdir() can only be called on a directory');
        }

        return puter.fs.readdir(this.path);
    };

    /**
     * Reads the contents of the file.
     *
     * @returns {Promise<Blob>}
     */
    read = async function () {
        return puter.fs.read(this.path);
    };
}

export default FSItem;