/*
 * Copyright (C) 2024-present Puter Technologies Inc.
 *
 * This file is part of Puter.
 *
 * Puter is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { toFinishReason } from './stopReason.js';

export class AIChatConstructStream {
    constructor(chatStream, params) {
        this.chatStream = chatStream;
        if (this._start) this._start(params);
    }
    end() {}
}

export class AIChatTextStream extends AIChatConstructStream {
    addText(text, extra_content) {
        this.chatStream.writeChunk({
            type: 'text',
            text,
            ...(extra_content ? { extra_content } : {}),
        });
    }

    addReasoning(reasoning) {
        this.chatStream.writeChunk({
            type: 'reasoning',
            reasoning,
        });
    }

    addExtraContent(extra_content) {
        this.chatStream.writeChunk({
            type: 'extra_content',
            extra_content,
        });
    }
}

export class AIChatToolUseStream extends AIChatConstructStream {
    _start(params) {
        this.contentBlock = params;
        this.buffer = '';
        // Incremental tool-call deltas are opt-in (`streamToolInput`): most
        // callers still want only the final `tool_use` chunk `end()` writes.
        if (this.chatStream.streamToolInput) {
            this.chatStream.writeChunk(
                {
                    type: 'tool_use_start',
                    id: params.id,
                    name: params.name,
                    // The upstream's own item id (OpenAI Responses `fc_…`).
                    ...(params.canonical_id
                        ? { canonical_id: params.canonical_id }
                        : {}),
                },
                { alreadyCounted: true },
            );
        }
    }
    addPartialJSON(partial_json) {
        // Counted as it accumulates, not when the block is written out: a
        // stream that dies mid-tool-call still produced these characters.
        this.chatStream.countOutput(partial_json);
        this.buffer += partial_json;
        if (this.chatStream.streamToolInput) {
            this.chatStream.writeChunk(
                {
                    type: 'tool_input_delta',
                    id: this.contentBlock.id,
                    partialJson: partial_json,
                },
                { alreadyCounted: true },
            );
        }
    }
    end() {
        if (this.buffer.trim() === '') {
            this.buffer = '{}';
        }
        if (process.env.DEBUG) console.log('BUFFER BEING PARSED', this.buffer);
        // Truncated `eager_input_streaming` input is still a tool call that
        // happened — surface it as empty args instead of killing the whole
        // stream over one malformed block.
        let input;
        try {
            input = JSON.parse(this.buffer);
        } catch {
            input = {};
        }
        this.chatStream.writeChunk(
            {
                type: 'tool_use',
                ...this.contentBlock,
                input,
                ...(!this.contentBlock.text ? { text: '' } : {}),
            },
            { alreadyCounted: true },
        );
    }
}

export class AIChatMessageStream extends AIChatConstructStream {
    contentBlock({ type, ...params }) {
        if (type === 'tool_use') {
            return new AIChatToolUseStream(this.chatStream, params);
        }
        if (type === 'text') {
            return new AIChatTextStream(this.chatStream, params);
        }
        throw new Error(`Unknown content block type: ${type}`);
    }
}

// Chunk fields that are envelope rather than model output — everything else
// string-valued in an outgoing chunk was generated by the model and counts
// toward the billing estimate for a stream whose usage is never reported.
const ENVELOPE_KEYS = new Set(['type', 'id', 'usage']);

/** Characters of model-authored payload in one outgoing chunk value. */
const payloadChars = (value) => {
    if (typeof value === 'string') return value.length;
    if (Array.isArray(value)) {
        return value.reduce((n, v) => n + payloadChars(v), 0);
    }
    if (value && typeof value === 'object') {
        let n = 0;
        for (const [key, v] of Object.entries(value)) {
            if (!ENVELOPE_KEYS.has(key)) n += payloadChars(v);
        }
        return n;
    }
    return 0;
};

export class AIChatStream {
    stream;
    /**
     * Characters of model output that have gone through this stream.
     *
     * The only measure of what a completion produced that survives a stream
     * ending badly. Providers report usage at the end and meter from it; when
     * that end is never reached, this is what the driver falls back to so a
     * completion that was generated is a completion that gets charged.
     */
    outputChars = 0;

    /**
     * Usage the provider has metered, recorded the moment it is known rather
     * than when `end` is reached. A throw between metering and `end` must not
     * disguise a charged stream as an uncharged one — the driver would then
     * charge its estimate on top of the real usage.
     *
     * @type {Record<string, number> | null}
     */
    reportedUsage = null;

    /** Set once the caller has gone away; see `abort`. */
    aborted = false;

    /**
     * Stop/usage/context-management state for the end-of-stream `usage` line,
     * set by `setStop` / `setUsageDetails` / `setUsageCosts` /
     * `setContextManagement`. Stored only — `end()` reads them, and
     * `usageCosts` is never written to the wire.
     *
     * @type {{
     *     reason?: string;
     *     sequence?: string | null;
     *     details?: Record<string, unknown> | null;
     * } | null}
     */
    stop = null;
    /** @type {import('../types.js').UsageDetails | null} */
    usageDetails = null;
    /** @type {Record<string, number> | null} */
    usageCosts = null;
    /** @type {Record<string, unknown> | null} */
    contextManagement = null;

    constructor({ stream, streamToolInput } = {}) {
        this.stream = stream;
        this.streamToolInput = !!streamToolInput;
    }

    /**
     * Stop accepting output after cancellation; providers cancel their requests
     * too.
     */
    abort() {
        this.aborted = true;
    }

    #assertOpen() {
        if (this.aborted) throw new ChatStreamAbortedError();
    }

    /** @param {string} text */
    countOutput(text) {
        // Tool-call input arrives through here and is only written when the
        // block ends, so a long tool call has to notice the abort here too.
        this.#assertOpen();
        if (typeof text === 'string') this.outputChars += text.length;
    }

    /**
     * Mark this stream's usage as metered. A usage object with no finite
     * numbers in it is not a report — nothing was recorded from it (a Claude
     * stream that died before its usage events ends with `{}`, and the driver's
     * `end` wrapper decorates that with `usd_cents: null`), so the driver's
     * estimate is still the only charge the stream would ever get.
     *
     * @param {Record<string, number> | undefined | null} usage
     */
    reportUsage(usage) {
        if (!usage) return;
        if (Object.values(usage).some((v) => Number.isFinite(v))) {
            this.reportedUsage = usage;
        }
    }

    /**
     * Write one NDJSON chunk, counting its model-authored payload toward
     * `outputChars` — counting lives at this choke point so a new chunk type is
     * counted by default instead of arriving for free. Pass `alreadyCounted`
     * when the payload was counted as it accumulated.
     *
     * @param {Record<string, unknown>} chunk
     * @param {{ alreadyCounted?: boolean }} [opts]
     */
    writeChunk(chunk, { alreadyCounted = false } = {}) {
        this.#assertOpen();
        if (!alreadyCounted) this.outputChars += payloadChars(chunk);
        this.stream.write(`${JSON.stringify(chunk)}\n`);
    }

    /**
     * Store the real stop reason for the end-of-stream `usage` line.
     * `sequence`/`details` default to `null` (the wire's "none" spelling);
     * `reason` left unset is still a no-op stop.
     *
     * @param {{
     *     reason?: string;
     *     sequence?: string | null;
     *     details?: Record<string, unknown> | null;
     * }} [stop]
     */
    setStop({ reason, sequence, details } = {}) {
        this.stop = {
            reason,
            sequence: sequence ?? null,
            details: details ?? null,
        };
    }

    /** @param {import('../types.js').UsageDetails} details */
    setUsageDetails(details) {
        this.usageDetails = details;
    }

    /**
     * Per-usage-key cost (µ¢) the provider already metered with. Read by the
     * driver for `usd_cents`/cost-calculated events; never serialized here.
     *
     * @param {Record<string, number>} costs
     */
    setUsageCosts(costs) {
        this.usageCosts = costs;
    }

    /** @param {Record<string, unknown>} contextManagement */
    setContextManagement(contextManagement) {
        this.contextManagement = contextManagement;
    }

    /**
     * A replayable reasoning block opened. Claude only, for now — other
     * providers' reasoning is plain `{type:'reasoning'}` deltas with no
     * replayable artifact.
     *
     * @param {string} format
     */
    reasoningStart(format) {
        this.writeChunk({ type: 'reasoning_start', format });
    }

    /**
     * A verbatim reasoning artifact for replay (`message.reasoning_details`): a
     * signed `thinking` block, a `redacted_thinking` block, or an OpenAI
     * Responses `reasoning` item. Counted as already-produced output — the
     * underlying text already went through `countOutput`/`addReasoning`.
     *
     * @param {Record<string, unknown>} detail
     */
    reasoningDetail(detail) {
        this.writeChunk(
            { type: 'reasoning_detail', detail },
            { alreadyCounted: true },
        );
    }

    /**
     * A server-executed tool block: the call (`server_tool_use`) or one of its
     * result types. Results are input the model read back, not output it
     * generated, so both are written already-counted — the call's JSON streamed
     * through `countOutput` as it arrived.
     *
     * @param {Record<string, unknown>} block
     */
    serverTool(block) {
        this.writeChunk(
            { type: 'server_tool', block },
            { alreadyCounted: true },
        );
    }

    /**
     * Dangerous-tool-use classifier verdicts, only ever written when the
     * upstream actually sent them.
     *
     * @param {unknown[]} results
     */
    safeguardResults(results) {
        this.writeChunk(
            { type: 'safeguard_results', results },
            { alreadyCounted: true },
        );
    }

    /**
     * @param {Record<string, number>} usage
     * @param {Record<string, unknown>} [extra] Fields for the `usage` line;
     *   override the stored state.
     */
    end(usage, extra) {
        this.reportUsage(usage);
        // Usage still counts after an abort; only the line has no reader.
        if (!this.aborted) {
            const stop = this.stop;
            const finish_reason = stop?.reason
                ? toFinishReason(stop.reason)
                : undefined;
            this.stream.write(
                `${JSON.stringify({
                    type: 'usage',
                    usage,
                    ...(stop?.reason !== undefined
                        ? {
                              stopReason: stop.reason,
                              stopSequence: stop.sequence ?? null,
                              stopDetails: stop.details ?? null,
                          }
                        : {}),
                    ...(finish_reason !== undefined ? { finish_reason } : {}),
                    ...(this.usageDetails
                        ? { usageDetails: this.usageDetails }
                        : {}),
                    ...(this.contextManagement
                        ? { contextManagement: this.contextManagement }
                        : {}),
                    ...extra,
                })}\n`,
            );
        }
        this.stream.end();
    }

    /**
     * Emit a canonical compaction event into the NDJSON stream. Both the OpenAI
     * and Anthropic providers normalize their native inline-compaction artifact
     * to this single shape, so downstream consumers (controllers, puter.js) see
     * an identical `{ type: 'compaction', id, encrypted_content }` chunk
     * regardless of which upstream served the request.
     *
     * @param {{ id?: string; encrypted_content: string }} compaction
     */
    compaction({ id, encrypted_content }) {
        this.writeChunk({
            type: 'compaction',
            ...(id !== undefined ? { id } : {}),
            encrypted_content,
        });
    }

    message() {
        return new AIChatMessageStream(this);
    }
    write(...args) {
        this.#assertOpen();
        return this.stream.write(...args);
    }
}

/** Thrown into a provider's read loop once its caller has gone away. */
export class ChatStreamAbortedError extends Error {
    constructor() {
        super('Chat stream aborted: the caller disconnected');
        this.name = 'ChatStreamAbortedError';
    }
}

export default class Streaming {
    static AIChatStream = AIChatStream;
}
