/*
 * Copyright (C) 2024-present Puter Technologies Inc.
 *
 * This file is part of Puter.
 *
 * Puter is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

export class AIChatConstructStream {
    constructor(chatStream, params) {
        this.chatStream = chatStream;
        if (this._start) this._start(params);
    }
    end() {}
}

export class AIChatTextStream extends AIChatConstructStream {
    addText(text, extra_content) {
        this.chatStream.writeChunk({
            type: 'text',
            text,
            ...(extra_content ? { extra_content } : {}),
        });
    }

    addReasoning(reasoning) {
        this.chatStream.writeChunk({
            type: 'reasoning',
            reasoning,
        });
    }

    addExtraContent(extra_content) {
        this.chatStream.writeChunk({
            type: 'extra_content',
            extra_content,
        });
    }
}

export class AIChatToolUseStream extends AIChatConstructStream {
    _start(params) {
        this.contentBlock = params;
        this.buffer = '';
    }
    addPartialJSON(partial_json) {
        // Counted as it accumulates, not when the block is written out: a
        // stream that dies mid-tool-call still produced these characters.
        this.chatStream.countOutput(partial_json);
        this.buffer += partial_json;
    }
    end() {
        if (this.buffer.trim() === '') {
            this.buffer = '{}';
        }
        if (process.env.DEBUG) console.log('BUFFER BEING PARSED', this.buffer);
        this.chatStream.writeChunk(
            {
                type: 'tool_use',
                ...this.contentBlock,
                input: JSON.parse(this.buffer),
                ...(!this.contentBlock.text ? { text: '' } : {}),
            },
            { alreadyCounted: true },
        );
    }
}

export class AIChatMessageStream extends AIChatConstructStream {
    contentBlock({ type, ...params }) {
        if (type === 'tool_use') {
            return new AIChatToolUseStream(this.chatStream, params);
        }
        if (type === 'text') {
            return new AIChatTextStream(this.chatStream, params);
        }
        throw new Error(`Unknown content block type: ${type}`);
    }
}

// Chunk fields that are envelope rather than model output — everything else
// string-valued in an outgoing chunk was generated by the model and counts
// toward the billing estimate for a stream whose usage is never reported.
const ENVELOPE_KEYS = new Set(['type', 'id', 'usage']);

/** Characters of model-authored payload in one outgoing chunk value. */
const payloadChars = (value) => {
    if (typeof value === 'string') return value.length;
    if (Array.isArray(value)) {
        return value.reduce((n, v) => n + payloadChars(v), 0);
    }
    if (value && typeof value === 'object') {
        let n = 0;
        for (const [key, v] of Object.entries(value)) {
            if (!ENVELOPE_KEYS.has(key)) n += payloadChars(v);
        }
        return n;
    }
    return 0;
};

export class AIChatStream {
    stream;
    /**
     * Characters of model output that have gone through this stream.
     *
     * The only measure of what a completion produced that survives a stream
     * ending badly. Providers report usage at the end and meter from it; when
     * that end is never reached, this is what the driver falls back to so a
     * completion that was generated is a completion that gets charged.
     */
    outputChars = 0;

    /**
     * Usage the provider has metered, recorded the moment it is known rather
     * than when `end` is reached. A throw between metering and `end` must not
     * disguise a charged stream as an uncharged one — the driver would then
     * charge its estimate on top of the real usage.
     *
     * @type {Record<string, number> | null}
     */
    reportedUsage = null;

    constructor({ stream }) {
        this.stream = stream;
    }

    /** @param {string} text */
    countOutput(text) {
        if (typeof text === 'string') this.outputChars += text.length;
    }

    /**
     * Mark this stream's usage as metered. A usage object with no finite
     * numbers in it is not a report — nothing was recorded from it (a Claude
     * stream that died before its usage events ends with `{}`, and the driver's
     * `end` wrapper decorates that with `usd_cents: null`), so the driver's
     * estimate is still the only charge the stream would ever get.
     *
     * @param {Record<string, number> | undefined | null} usage
     */
    reportUsage(usage) {
        if (!usage) return;
        if (Object.values(usage).some((v) => Number.isFinite(v))) {
            this.reportedUsage = usage;
        }
    }

    /**
     * Write one NDJSON chunk, counting its model-authored payload toward
     * `outputChars` — counting lives at this choke point so a new chunk type is
     * counted by default instead of arriving for free. Pass `alreadyCounted`
     * when the payload was counted as it accumulated.
     *
     * @param {Record<string, unknown>} chunk
     * @param {{ alreadyCounted?: boolean }} [opts]
     */
    writeChunk(chunk, { alreadyCounted = false } = {}) {
        if (!alreadyCounted) this.outputChars += payloadChars(chunk);
        this.stream.write(`${JSON.stringify(chunk)}\n`);
    }

    end(/** @type {Record<string, number>} */ usage) {
        this.reportUsage(usage);
        this.stream.write(
            `${JSON.stringify({
                type: 'usage',
                usage,
            })}\n`,
        );
        this.stream.end();
    }

    /**
     * Emit a canonical compaction event into the NDJSON stream. Both the OpenAI
     * and Anthropic providers normalize their native inline-compaction artifact
     * to this single shape, so downstream consumers (controllers, puter.js) see
     * an identical `{ type: 'compaction', id, encrypted_content }` chunk
     * regardless of which upstream served the request.
     *
     * @param {{ id?: string; encrypted_content: string }} compaction
     */
    compaction({ id, encrypted_content }) {
        this.writeChunk({
            type: 'compaction',
            ...(id !== undefined ? { id } : {}),
            encrypted_content,
        });
    }

    message() {
        return new AIChatMessageStream(this);
    }
    write(...args) {
        return this.stream.write(...args);
    }
}

export default class Streaming {
    static AIChatStream = AIChatStream;
}
