CREATE TABLE `notification` (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `user_id` INTEGER NOT NULL,
    `uid` TEXT NOT NULL UNIQUE,
    `value` JSON NOT NULL,
    `awknowledged` INTEGER DEFAULT NULL,
    `shown` INTEGER DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
