/*
 * Copyright (C) 2024-present Puter Technologies Inc.
 *
 * This file is part of Puter.
 *
 * Puter is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import type { IImageModel } from '../../types.js';

export const RETIRED_TOGETHER_IMAGE_MODELS = [
    'black-forest-labs/FLUX.1-schnell',
    'black-forest-labs/FLUX.1-krea-dev',
    'HiDream-ai/HiDream-I1-Dev',
    'HiDream-ai/HiDream-I1-Fast',
    'HiDream-ai/HiDream-I1-Full',
    'Lykon/DreamShaper',
    'stabilityai/stable-diffusion-3-medium',
];

export type TogetherImageModel = IImageModel & {
    defaultRatio?: { w: number; h: number };
    referenceImageField?: 'image_url' | 'reference_images';
    supportsImageCount?: boolean;
    requiresInputImage?: boolean;
    dimensionStep?: number;
    minDimension?: number;
    maxDimension?: number;
};

type ResolutionMap = Record<string, Record<string, { w: number; h: number }>>;

export const GEMINI_3_IMAGE_RESOLUTION_MAP: ResolutionMap = {
    '1:1': {
        '1K': { w: 1024, h: 1024 },
        '2K': { w: 2048, h: 2048 },
        '4K': { w: 4096, h: 4096 },
    },
    '2:3': {
        '1K': { w: 848, h: 1264 },
        '2K': { w: 1696, h: 2528 },
        '4K': { w: 3392, h: 5096 },
    },
    '3:2': {
        '1K': { w: 1264, h: 848 },
        '2K': { w: 2528, h: 1696 },
        '4K': { w: 5096, h: 3392 },
    },
    '3:4': {
        '1K': { w: 896, h: 1200 },
        '2K': { w: 1792, h: 2400 },
        '4K': { w: 3584, h: 4800 },
    },
    '4:3': {
        '1K': { w: 1200, h: 896 },
        '2K': { w: 2400, h: 1792 },
        '4K': { w: 4800, h: 3584 },
    },
    '4:5': {
        '1K': { w: 928, h: 1152 },
        '2K': { w: 1856, h: 2304 },
        '4K': { w: 3712, h: 4608 },
    },
    '5:4': {
        '1K': { w: 1152, h: 928 },
        '2K': { w: 2304, h: 1856 },
        '4K': { w: 4608, h: 3712 },
    },
    '9:16': {
        '1K': { w: 768, h: 1376 },
        '2K': { w: 1536, h: 2752 },
        '4K': { w: 3072, h: 5504 },
    },
    '16:9': {
        '1K': { w: 1376, h: 768 },
        '2K': { w: 2752, h: 1536 },
        '4K': { w: 5504, h: 3072 },
    },
    '21:9': {
        '1K': { w: 1584, h: 672 },
        '2K': { w: 3168, h: 1344 },
        '4K': { w: 6336, h: 2688 },
    },
};

export const FLASH_IMAGE_3_1_RESOLUTION_MAP: ResolutionMap = {
    '1:1': {
        '0.5K': { w: 512, h: 512 },
        '1K': { w: 1024, h: 1024 },
        '2K': { w: 2048, h: 2048 },
        '4K': { w: 4096, h: 4096 },
    },
    '1:4': {
        '0.5K': { w: 256, h: 1024 },
        '1K': { w: 512, h: 2048 },
        '2K': { w: 1024, h: 4096 },
        '4K': { w: 2048, h: 8192 },
    },
    '1:8': {
        '0.5K': { w: 192, h: 1536 },
        '1K': { w: 384, h: 3072 },
        '2K': { w: 768, h: 6144 },
        '4K': { w: 1536, h: 12288 },
    },
    '2:3': {
        '0.5K': { w: 424, h: 632 },
        '1K': { w: 848, h: 1264 },
        '2K': { w: 1696, h: 2528 },
        '4K': { w: 3392, h: 5056 },
    },
    '3:2': {
        '0.5K': { w: 632, h: 424 },
        '1K': { w: 1264, h: 848 },
        '2K': { w: 2528, h: 1696 },
        '4K': { w: 5056, h: 3392 },
    },
    '3:4': {
        '0.5K': { w: 448, h: 600 },
        '1K': { w: 896, h: 1200 },
        '2K': { w: 1792, h: 2400 },
        '4K': { w: 3584, h: 4800 },
    },
    '4:1': {
        '0.5K': { w: 1024, h: 256 },
        '1K': { w: 2048, h: 512 },
        '2K': { w: 4096, h: 1024 },
        '4K': { w: 8192, h: 2048 },
    },
    '4:3': {
        '0.5K': { w: 600, h: 448 },
        '1K': { w: 1200, h: 896 },
        '2K': { w: 2400, h: 1792 },
        '4K': { w: 4800, h: 3584 },
    },
    '4:5': {
        '0.5K': { w: 464, h: 576 },
        '1K': { w: 928, h: 1152 },
        '2K': { w: 1856, h: 2304 },
        '4K': { w: 3712, h: 4608 },
    },
    '5:4': {
        '0.5K': { w: 576, h: 464 },
        '1K': { w: 1152, h: 928 },
        '2K': { w: 2304, h: 1856 },
        '4K': { w: 4608, h: 3712 },
    },
    '8:1': {
        '0.5K': { w: 1536, h: 192 },
        '1K': { w: 3072, h: 384 },
        '2K': { w: 6144, h: 768 },
        '4K': { w: 12288, h: 1536 },
    },
    '9:16': {
        '0.5K': { w: 384, h: 688 },
        '1K': { w: 768, h: 1376 },
        '2K': { w: 1536, h: 2752 },
        '4K': { w: 3072, h: 5504 },
    },
    '16:9': {
        '0.5K': { w: 688, h: 384 },
        '1K': { w: 1376, h: 768 },
        '2K': { w: 2752, h: 1536 },
        '4K': { w: 5504, h: 3072 },
    },
    '21:9': {
        '0.5K': { w: 792, h: 168 },
        '1K': { w: 1584, h: 672 },
        '2K': { w: 3168, h: 1344 },
        '4K': { w: 6336, h: 2688 },
    },
};

const togetherImageModels: TogetherImageModel[] = [
    {
        id: 'togetherai:ByteDance-Seed/Seedream-3.0',
        aliases: ['ByteDance-Seed/Seedream-3.0', 'Seedream-3.0'],
        costs_currency: 'usd-cents',
        index_cost_key: '1MP',
        name: 'ByteDance-Seed/Seedream-3.0',
        allowedQualityLevels: [''],
        pricing_unit: 'per-MP',
        costs: { '1MP': 1.8 },
    },
    {
        id: 'togetherai:ByteDance-Seed/Seedream-4.0',
        aliases: ['ByteDance-Seed/Seedream-4.0', 'Seedream-4.0'],
        costs_currency: 'usd-cents',
        index_cost_key: '1MP',
        name: 'ByteDance-Seed/Seedream-4.0',
        allowedQualityLevels: [''],
        pricing_unit: 'per-MP',
        costs: { '1MP': 3 },
    },
    {
        id: 'togetherai:Qwen/Qwen-Image',
        aliases: ['Qwen/Qwen-Image', 'Qwen-Image'],
        costs_currency: 'usd-cents',
        index_cost_key: '1MP',
        name: 'Qwen/Qwen-Image',
        allowedQualityLevels: [''],
        pricing_unit: 'per-MP',
        costs: { '1MP': 0.58 },
    },
    {
        id: 'togetherai:Qwen/Qwen-Image-2.0',
        aliases: ['Qwen/Qwen-Image-2.0', 'Qwen-Image-2.0'],
        costs_currency: 'usd-cents',
        index_cost_key: 'per-image',
        name: 'Qwen/Qwen-Image-2.0',
        allowedQualityLevels: [''],
        pricing_unit: 'per-image',
        costs: { 'per-image': 3.5 },
    },
    {
        id: 'togetherai:Qwen/Qwen-Image-2.0-Pro',
        aliases: ['Qwen/Qwen-Image-2.0-Pro', 'Qwen-Image-2.0-Pro'],
        costs_currency: 'usd-cents',
        index_cost_key: 'per-image',
        name: 'Qwen/Qwen-Image-2.0-Pro',
        allowedQualityLevels: [''],
        pricing_unit: 'per-image',
        costs: { 'per-image': 7.5 },
    },
    {
        id: 'togetherai:RunDiffusion/Juggernaut-pro-flux',
        aliases: ['RunDiffusion/Juggernaut-pro-flux', 'Juggernaut-pro-flux'],
        costs_currency: 'usd-cents',
        index_cost_key: '1MP',
        name: 'RunDiffusion/Juggernaut-pro-flux',
        allowedQualityLevels: [''],
        pricing_unit: 'per-MP',
        costs: { '1MP': 0.49 },
    },
    {
        id: 'togetherai:Rundiffusion/Juggernaut-Lightning-Flux',
        aliases: [
            'Rundiffusion/Juggernaut-Lightning-Flux',
            'Juggernaut-Lightning-Flux',
        ],
        costs_currency: 'usd-cents',
        index_cost_key: '1MP',
        name: 'Rundiffusion/Juggernaut-Lightning-Flux',
        allowedQualityLevels: [''],
        pricing_unit: 'per-MP',
        costs: { '1MP': 0.17 },
    },
    {
        id: 'togetherai:Wan-AI/Wan2.6-image',
        defaultRatio: { w: 1280, h: 1280 },
        aliases: ['Wan-AI/Wan2.6-image', 'Wan2.6-image'],
        costs_currency: 'usd-cents',
        index_cost_key: 'per-image',
        name: 'Wan-AI/Wan2.6-image',
        allowedQualityLevels: [''],
        pricing_unit: 'per-image',
        costs: { 'per-image': 3 },
    },
    {
        id: 'togetherai:black-forest-labs/FLUX.1-kontext-max',
        referenceImageField: 'image_url',
        requiresInputImage: true,
        aliases: ['black-forest-labs/FLUX.1-kontext-max', 'FLUX.1-kontext-max'],
        costs_currency: 'usd-cents',
        index_cost_key: '1MP',
        name: 'black-forest-labs/FLUX.1-kontext-max',
        allowedQualityLevels: [''],
        pricing_unit: 'per-MP',
        costs: { '1MP': 8 },
    },
    {
        id: 'togetherai:black-forest-labs/FLUX.1-kontext-pro',
        referenceImageField: 'image_url',
        requiresInputImage: true,
        aliases: ['black-forest-labs/FLUX.1-kontext-pro', 'FLUX.1-kontext-pro'],
        costs_currency: 'usd-cents',
        index_cost_key: '1MP',
        name: 'black-forest-labs/FLUX.1-kontext-pro',
        allowedQualityLevels: [''],
        pricing_unit: 'per-MP',
        costs: { '1MP': 4 },
    },
    {
        id: 'togetherai:black-forest-labs/FLUX.1.1-pro',
        aliases: ['black-forest-labs/FLUX.1.1-pro', 'FLUX.1.1-pro'],
        costs_currency: 'usd-cents',
        index_cost_key: '1MP',
        name: 'black-forest-labs/FLUX.1.1-pro',
        allowedQualityLevels: [''],
        pricing_unit: 'per-MP',
        costs: { '1MP': 4 },
    },
    {
        id: 'togetherai:black-forest-labs/FLUX.2-dev',
        dimensionStep: 16,
        minDimension: 128,
        maxDimension: 2048,
        referenceImageField: 'reference_images',
        aliases: ['black-forest-labs/FLUX.2-dev', 'FLUX.2-dev'],
        costs_currency: 'usd-cents',
        index_cost_key: 'per-image',
        name: 'black-forest-labs/FLUX.2-dev',
        allowedQualityLevels: [''],
        pricing_unit: 'per-image',
        costs: { 'per-image': 1.54 },
    },
    {
        id: 'togetherai:black-forest-labs/FLUX.2-flex',
        referenceImageField: 'reference_images',
        aliases: ['black-forest-labs/FLUX.2-flex', 'FLUX.2-flex'],
        costs_currency: 'usd-cents',
        index_cost_key: 'per-image',
        name: 'black-forest-labs/FLUX.2-flex',
        allowedQualityLevels: [''],
        pricing_unit: 'per-image',
        costs: { 'per-image': 3 },
    },
    {
        id: 'togetherai:black-forest-labs/FLUX.2-max',
        referenceImageField: 'reference_images',
        aliases: ['black-forest-labs/FLUX.2-max', 'FLUX.2-max'],
        costs_currency: 'usd-cents',
        index_cost_key: '1MP',
        name: 'black-forest-labs/FLUX.2-max',
        allowedQualityLevels: [''],
        pricing_unit: 'per-MP',
        costs: { '1MP': 7 },
    },
    {
        id: 'togetherai:black-forest-labs/FLUX.2-pro',
        referenceImageField: 'reference_images',
        aliases: ['black-forest-labs/FLUX.2-pro', 'FLUX.2-pro'],
        costs_currency: 'usd-cents',
        index_cost_key: 'per-image',
        name: 'black-forest-labs/FLUX.2-pro',
        allowedQualityLevels: [''],
        pricing_unit: 'per-image',
        costs: { 'per-image': 3 },
    },
    {
        id: 'togetherai:google/flash-image-2.5',
        referenceImageField: 'reference_images',
        supportsImageCount: false,
        aliases: ['google/flash-image-2.5', 'flash-image-2.5'],
        costs_currency: 'usd-cents',
        index_cost_key: 'per-image',
        name: 'google/flash-image-2.5',
        allowedQualityLevels: ['1K'],
        allowedRatios: [
            { w: 1024, h: 1024 },
            { w: 1248, h: 832 },
            { w: 832, h: 1248 },
            { w: 1184, h: 864 },
            { w: 864, h: 1184 },
            { w: 896, h: 1152 },
            { w: 1152, h: 896 },
            { w: 768, h: 1344 },
            { w: 1344, h: 768 },
            { w: 1536, h: 672 },
            { w: 672, h: 1536 },
        ],
        pricing_unit: 'per-image',
        costs: { 'per-image': 3.9 },
    },
    {
        id: 'togetherai:google/flash-image-3.1',
        referenceImageField: 'reference_images',
        supportsImageCount: false,
        aliases: ['google/flash-image-3.1', 'flash-image-3.1', 'nano-banana-2'],
        name: 'google/flash-image-3.1',
        costs_currency: 'usd-cents',
        index_cost_key: '1K',
        allowedQualityLevels: ['0.5K', '1K', '2K', '4K'],
        allowedRatios: [
            { w: 1, h: 1 },
            { w: 2, h: 3 },
            { w: 3, h: 2 },
            { w: 3, h: 4 },
            { w: 4, h: 3 },
            { w: 4, h: 5 },
            { w: 5, h: 4 },
            { w: 9, h: 16 },
            { w: 16, h: 9 },
            { w: 21, h: 9 },
            { w: 1, h: 4 },
            { w: 4, h: 1 },
            { w: 1, h: 8 },
            { w: 8, h: 1 },
        ],
        pricing_unit: 'per-tier',
        costs: {
            '0.5K': 4.657,
            '1K': 6.7,
            '2K': 10.1,
            '4K': 15.1,
            input_image: 0.028,
        },
        resolution_map: FLASH_IMAGE_3_1_RESOLUTION_MAP,
    },
    {
        id: 'togetherai:google/gemini-3-pro-image',
        referenceImageField: 'reference_images',
        supportsImageCount: false,
        aliases: ['gemini-3-pro-image', 'google/gemini-3-pro-image'],
        name: 'gemini-3-pro-image (Together AI)',
        costs_currency: 'usd-cents',
        index_cost_key: '1K',
        allowedQualityLevels: ['1K', '2K', '4K'],
        allowedRatios: [
            { w: 1, h: 1 },
            { w: 2, h: 3 },
            { w: 3, h: 2 },
            { w: 3, h: 4 },
            { w: 4, h: 3 },
            { w: 4, h: 5 },
            { w: 5, h: 4 },
            { w: 9, h: 16 },
            { w: 16, h: 9 },
            { w: 21, h: 9 },
        ],
        pricing_unit: 'per-tier',
        costs: { '1K': 13.4, '2K': 13.4, '4K': 24 },
        resolution_map: GEMINI_3_IMAGE_RESOLUTION_MAP,
    },

    {
        id: 'togetherai:ideogram/ideogram-3.0',
        aliases: ['ideogram/ideogram-3.0', 'ideogram-3.0'],
        costs_currency: 'usd-cents',
        index_cost_key: '1MP',
        name: 'ideogram/ideogram-3.0',
        allowedQualityLevels: [''],
        pricing_unit: 'per-MP',
        costs: { '1MP': 6 },
    },
    {
        id: 'togetherai:ideogram/ideogram-4.0',
        aliases: ['ideogram/ideogram-4.0', 'ideogram-4.0'],
        costs_currency: 'usd-cents',
        index_cost_key: 'per-image',
        name: 'ideogram/ideogram-4.0',
        allowedQualityLevels: [''],
        pricing_unit: 'per-image',
        costs: { 'per-image': 6 },
        defaultRatio: { w: 2048, h: 2048 },
        allowedRatios: [
            { w: 2048, h: 2048 },
            { w: 1440, h: 2880 },
            { w: 2880, h: 1440 },
            { w: 1664, h: 2496 },
            { w: 2496, h: 1664 },
            { w: 1792, h: 2240 },
            { w: 2240, h: 1792 },
            { w: 1440, h: 2560 },
            { w: 2560, h: 1440 },
            { w: 1600, h: 2560 },
            { w: 2560, h: 1600 },
            { w: 1728, h: 2304 },
            { w: 2304, h: 1728 },
            { w: 1296, h: 3168 },
            { w: 3168, h: 1296 },
            { w: 1152, h: 2944 },
            { w: 2944, h: 1152 },
            { w: 1248, h: 3328 },
            { w: 3328, h: 1248 },
            { w: 1280, h: 3072 },
            { w: 3072, h: 1280 },
            { w: 1024, h: 3072 },
            { w: 3072, h: 1024 },
        ],
    },
    {
        id: 'togetherai:openai/gpt-image-1.5',
        aliases: ['openai/gpt-image-1.5', 'gpt-image-1.5'],
        costs_currency: 'usd-cents',
        index_cost_key: 'per-image',
        name: 'openai/gpt-image-1.5',
        allowedQualityLevels: [''],
        pricing_unit: 'per-image',
        costs: { 'per-image': 3.4 },
    },
    {
        id: 'togetherai:stabilityai/stable-diffusion-xl-base-1.0',
        aliases: [
            'stabilityai/stable-diffusion-xl-base-1.0',
            'stable-diffusion-xl-base-1.0',
        ],
        costs_currency: 'usd-cents',
        index_cost_key: '1MP',
        name: 'stabilityai/stable-diffusion-xl-base-1.0',
        allowedQualityLevels: [''],
        pricing_unit: 'per-MP',
        costs: { '1MP': 0.19 },
    },
    {
        id: 'togetherai:ByteDance/Seedream-5.0-lite',
        aliases: ['ByteDance/Seedream-5.0-lite', 'Seedream-5.0-lite'],
        name: 'Seedream 5.0 Lite',
        defaultRatio: { w: 2048, h: 2048 },
        costs_currency: 'usd-cents',
        pricing_unit: 'per-image',
        index_cost_key: 'per-image',
        costs: { 'per-image': 3.5 },
    },
    {
        id: 'togetherai:openai/gpt-image-2',
        // OpenAI owns the bare id; the alias only applies with `provider: 'together'`.
        aliases: ['openai/gpt-image-2', 'gpt-image-2'],
        name: 'GPT Image 2',
        costs_currency: 'usd-cents',
        pricing_unit: 'per-image',
        index_cost_key: 'per-image',
        costs: { 'per-image': 5.3 },
    },
    {
        id: 'togetherai:google/flash-image-3.1-lite',
        referenceImageField: 'reference_images',
        supportsImageCount: false,
        aliases: ['google/flash-image-3.1-lite', 'flash-image-3.1-lite'],
        name: 'Gemini 3.1 Flash Lite Image',
        costs_currency: 'usd-cents',
        pricing_unit: 'per-image',
        index_cost_key: 'per-image',
        costs: { 'per-image': 6.9 },
    },
    {
        id: 'togetherai:prunaai/p-image-ideogram',
        aliases: ['prunaai/p-image-ideogram', 'p-image-ideogram'],
        name: 'P Image Ideogram',
        costs_currency: 'usd-cents',
        pricing_unit: 'per-image',
        index_cost_key: 'per-image',
        costs: { 'per-image': 0.225 },
    },
    ...[
        { variant: 'fast', price: 2 },
        { variant: 'preview', price: 4 },
        { variant: 'ultra', price: 6 },
    ].map(({ variant, price }): TogetherImageModel => ({
        id: `togetherai:google/imagen-4.0-${variant}`,
        aliases: [`google/imagen-4.0-${variant}`, `imagen-4.0-${variant}`],
        name: `Imagen 4.0 ${variant}`,
        supportsImageCount: false,
        costs_currency: 'usd-cents',
        pricing_unit: 'per-image',
        index_cost_key: 'per-image',
        costs: { 'per-image': price },
    })),
];

// These endpoints reject requests while third-party data sharing is disabled.
export const TOGETHER_IMAGE_GENERATION_MODELS: TogetherImageModel[] =
    togetherImageModels.map((model) => ({
        ...model,
        excludedForDataPolicy: 'thirdPartySharing',
    }));
