/*
 * Copyright (C) 2024-present Puter Technologies Inc.
 * 
 * This file is part of Puter.
 * 
 * Puter is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

const configurable_auth = require("../../middleware/configurable_auth");
const { Endpoint } = require("../../util/expressutil");
const BaseService = require("../BaseService");
const fs = require("node:fs");

const { createWorker, setCloudflareKeys, deleteWorker } = require("./workerUtils/cloudflareDeploy");
const { getUserInfo } = require("./workerUtils/puterUtils");
const { LLRead } = require("../../filesystem/ll_operations/ll_read");
const { Context } = require("../../util/context");
const { NodePathSelector } = require("../../filesystem/node/selectors");
const { calculateWorkerName } = require("./workerUtils/nameUtils");
const { Entity } = require("../../om/entitystorage/Entity");
const { SKIP_ES_VALIDATION } = require("../../om/entitystorage/consts");

async function readPuterFile(actor, filePath) {
    try {
        const svc_fs = this.services.get('filesystem');
        const node = await svc_fs.node(new NodePathSelector(filePath));
        const ll_read = new LLRead();
        const stream = await ll_read.run({
            fsNode: node,
            actor,
        });
        const chunks = [];
        stream.on("data", (data) => {
            chunks.push(data)
        });
        return new Promise((res, rej) => {
            stream.on("error", (e) => {
                rej(e);
            });
            stream.on("end", () => {
                res(Buffer.concat(chunks));
            })
        })
    } catch (e) {
        console.error(e)
    }


}
// This file is generated by webpack. To rebuild: cd to this directory and run `npm run build`
let preamble;
try {
    preamble = fs.readFileSync(__dirname + "/dist/workerPreamble.js", "utf-8");
} catch (e) {
    preamble = "";
    console.error("WORKERS ERROR: Preamble has not been built! Workers will not have access to puter.js\nTo fix this cd into src/backend/src/worker and run npm run build")
}
const PREAMBLE_LENGTH = preamble.split("\n").length - 1
class WorkerService extends BaseService {
    ['__on_install.routes'](_, { app }) {
        setCloudflareKeys(this.config);
        const svc_event = this.services.get('event');
        svc_event.on('fs.write.*', (_key, data, meta) => {
            if (meta.from_outside) return;
        });
    }
    static IMPLEMENTS = {
        ['workers']: {
            async create({ filePath, workerName, authorization }) {
                try {
                    const userData = await getUserInfo(authorization, this.global_config.api_base_url);
                    const actor = Context.get("actor");
                    const es_subdomain = this.services.get('es:subdomain');
                    console.log(actor)
                    const fileData = (await readPuterFile(actor, filePath)).toString();
                    const cfData = await createWorker(userData, authorization, workerName, preamble + fileData, PREAMBLE_LENGTH);

                    await Context.sub({ [SKIP_ES_VALIDATION]: true }).arun(async () => {
                        const entity = await Entity.create({ om: es_subdomain.om }, {
                            subdomain: "workers.puter." + calculateWorkerName(userData.username, workerName),
                            owner: userData.id,
                            root_dir: filePath
                        });
                        await es_subdomain.upsert(entity);
                    });
                    
                    return cfData;
                } catch (e) {
                    console.error(e)
                    return { success: false, e }
                }
            },
            async destroy({ workerName, authorization }) {
                try {
                    const userData = await getUserInfo(authorization, this.global_config.api_base_url);
                    const cfData = await deleteWorker(userData, authorization, workerName);

                    const es_subdomain = this.services.get('es:subdomain');
                    const crudqSubdomain = es_subdomain.as('crud-q');
                    await crudq_subdomain.delete({ id: { subdomain: "workers.puter." + calculateWorkerName(userData.username, workerName) } })
                    return cfData;


                } catch (e) {
                    return { success: false, e }
                }
            },
            async startLogs({ workerName, authorization }) {
                return await this.exec_({ runtime, code });
            },
            async endLogs({ workerName, authorization }) {
                return await this.exec_({ runtime, code });
            },
        }
    }
    async ['__on_driver.register.interfaces']() {
        const svc_registry = this.services.get('registry');
        const col_interfaces = svc_registry.get('interfaces');

        col_interfaces.set('workers', {
            description: 'Execute code with various languages.',
            methods: {
                create: {
                    description: 'Create a backend worker',
                    parameters: {
                        filePath: {
                            type: "string",
                            description: "The path of the code of the worker to upload"
                        },
                        workerName: {
                            type: "string",
                            description: "The name of the worker you want to upload"
                        },
                        authorization: {
                            type: "string",
                            description: "Puter token"
                        }
                    },
                    result: { type: 'json' },
                },
                startLogs: {
                    description: 'Get logs for your backend worker',
                    parameters: {
                        workerName: {
                            type: "string",
                            description: "The name of the worker you want the logs of"
                        },
                        authorization: {
                            type: "string",
                            description: "Puter token"
                        }
                    },
                    result: { type: 'json' },
                },
                endLogs: {
                    description: 'Get logs for your backend worker',
                    parameters: {
                        workerName: {
                            type: "string",
                            description: "The name of the worker you want the logs of"
                        },
                        authorization: {
                            type: "string",
                            description: "Puter token"
                        }
                    },
                    result: { type: 'json' },
                },
                destroy: {
                    description: 'Get rid of your backend worker',
                    parameters: {
                        workerName: {
                            type: "string",
                            description: "The name of the worker you want to destroy"
                        },
                        authorization: {
                            type: "string",
                            description: "Puter token"
                        }
                    },
                    result: { type: 'json' },
                },
            }
        });
    }
}

module.exports = {
    WorkerService,
};
