/*
 * Copyright (C) 2024-present Puter Technologies Inc.
 *
 * This file is part of Puter.
 *
 * Puter is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { IVideoModel } from '../../types.js';

/**
 * Together prices its older video models per clip (`per-video`) and its newer
 * ones per second of output (`per-second`, plus `per-second-<tier>` where a
 * cheaper resolution tier exists). Per-second rates are the highest rate
 * Together publishes for the model so the pre-flight estimate never
 * undershoots; the provider then bills the amount Together reports on the
 * finished job. `default-duration-per-video` is the estimated cents for a 5s
 * clip and only feeds cross-provider cost sorting.
 */
export interface ITogetherVideoModel extends IVideoModel {
    model: string;
    organization: string;
    durationSeconds: number[] | null;
    /**
     * Pixel sizes the model takes as width/height, or resolution tiers ('720p')
     * it takes as `resolution`. The first entry is the default.
     */
    dimensions: string[] | null;
    fps: number[] | null;
    keyframes: string[] | null;
    promptLength: { min: number; max: number } | null;
    promptSupported: boolean | null;
    /**
     * Aspect ratios accepted as `ratio`, derived from width/height. Only
     * tier-sized models take one.
     */
    ratios?: string[] | null;
}

// Duration ladder for the driver's normalization: element 0 is the default,
// the rest enumerate the model's contiguous valid range.
const seconds = (def: number, min: number, max: number): number[] => [
    def,
    ...Array.from({ length: max - min + 1 }, (_, i) => min + i).filter(
        (s) => s !== def,
    ),
];

// Catalog from https://api.together.xyz/v1/models (type=video) and
// https://docs.together.ai/docs/serverless/models.
export const TOGETHER_VIDEO_GENERATION_MODELS: ITogetherVideoModel[] = [
    {
        id: 'togetherai:minimax/video-01-director',
        puterId: 'togetherai:minimax/video-01-director',
        organization: 'MiniMax',
        name: 'MiniMax 01 Director',
        model: 'minimax/video-01-director',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 28 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: ['1366x768'],
        fps: [25],
        keyframes: ['first'],
        promptLength: { min: 2, max: 3000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:minimax/hailuo-02',
        puterId: 'togetherai:minimax/hailuo-02',
        organization: 'MiniMax',
        name: 'MiniMax Hailuo 02',
        model: 'minimax/hailuo-02',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 49 },
        output_cost_key: 'per-video',
        durationSeconds: [10],
        dimensions: ['1366x768', '1920x1080'],
        fps: [25],
        keyframes: ['first'],
        promptLength: { min: 2, max: 3000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:google/veo-2.0',
        puterId: 'togetherai:google/veo-2.0',
        organization: 'Google',
        name: 'Veo 2.0',
        model: 'google/veo-2.0',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 250 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: ['1280x720', '720x1280'],
        fps: [24],
        keyframes: ['first', 'last'],
        promptLength: { min: 2, max: 3000 },
        promptSupported: true,
    },
    // Google serves Veo 3.1 directly too; these entries exist for callers who
    // pin `togetherai:`. Together's own listing quotes $0.60/s with audio.
    {
        id: 'togetherai:google/veo-3.1',
        puterId: 'togetherai:google/veo-3.1',
        organization: 'Google',
        name: 'Veo 3.1',
        model: 'google/veo-3.1',
        costs_currency: 'usd-cents',
        costs: { 'per-second': 60, 'default-duration-per-video': 300 },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: [4, 6, 8],
        dimensions: null,
        fps: [24],
        keyframes: ['first', 'last'],
        promptLength: null,
        promptSupported: true,
    },
    {
        id: 'togetherai:google/veo-3.1-lite',
        puterId: 'togetherai:google/veo-3.1-lite',
        organization: 'Google',
        name: 'Veo 3.1 Lite',
        model: 'google/veo-3.1-lite',
        costs_currency: 'usd-cents',
        costs: { 'per-second': 8, 'default-duration-per-video': 40 },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: [4, 6, 8],
        dimensions: null,
        fps: [24],
        keyframes: ['first', 'last'],
        promptLength: null,
        promptSupported: true,
    },
    {
        id: 'togetherai:ByteDance/Seedance-1.0-lite',
        puterId: 'togetherai:bytedance/seedance-1.0-lite',
        organization: 'ByteDance',
        name: 'Seedance 1.0 Lite',
        model: 'ByteDance/Seedance-1.0-lite',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 14.3 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: [
            '864x480',
            '736x544',
            '640x640',
            '960x416',
            '416x960',
            '1248x704',
            '1120x832',
            '960x960',
            '1504x640',
            '640x1504',
        ],
        fps: [24],
        keyframes: ['first', 'last'],
        promptLength: { min: 2, max: 3000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:ByteDance/Seedance-1.0-pro',
        puterId: 'togetherai:bytedance/seedance-1.0-pro',
        organization: 'ByteDance',
        name: 'Seedance 1.0 Pro',
        model: 'ByteDance/Seedance-1.0-pro',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 57 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: [
            '864x480',
            '736x544',
            '640x640',
            '960x416',
            '416x960',
            '1248x704',
            '1120x832',
            '960x960',
            '1504x640',
            '640x1504',
        ],
        fps: [24],
        keyframes: ['first', 'last'],
        promptLength: { min: 2, max: 3000 },
        promptSupported: true,
    },
    // Together quotes 720P text/image-to-video at $0.16/s and video-to-video
    // "from $0.28/s"; the higher rate is the estimate since reference inputs
    // can route to the latter.
    {
        id: 'togetherai:ByteDance/Seedance-2.0',
        puterId: 'togetherai:bytedance/seedance-2.0',
        organization: 'ByteDance',
        name: 'Seedance 2.0',
        model: 'ByteDance/Seedance-2.0',
        costs_currency: 'usd-cents',
        costs: { 'per-second': 28, 'default-duration-per-video': 140 },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: seconds(5, 4, 15),
        dimensions: null,
        fps: [24],
        keyframes: ['first', 'last'],
        promptLength: null,
        promptSupported: true,
    },
    {
        id: 'togetherai:ByteDance/Seedance-2.5',
        puterId: 'togetherai:bytedance/seedance-2.5',
        organization: 'ByteDance',
        name: 'Seedance 2.5',
        model: 'ByteDance/Seedance-2.5',
        costs_currency: 'usd-cents',
        costs: {
            'per-second': 24.9,
            'per-second-480p': 11.5,
            'default-duration-per-video': 125,
        },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: seconds(5, 4, 30),
        dimensions: ['720p', '480p'],
        fps: [24],
        keyframes: ['first', 'last'],
        promptLength: { min: 2, max: 10000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:pixverse/pixverse-v5',
        puterId: 'togetherai:pixverse/pixverse-v5',
        organization: 'PixVerse',
        name: 'PixVerse v5',
        model: 'pixverse/pixverse-v5',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 30 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: [
            '640x360',
            '480x360',
            '360x360',
            '270x360',
            '360x640',
            '960x540',
            '720x540',
            '540x540',
            '405x540',
            '540x960',
            '1280x720',
            '960x720',
            '720x720',
            '540x720',
            '720x1280',
            '1920x1080',
            '1440x1080',
            '1080x1080',
            '810x1080',
            '1080x1920',
        ],
        fps: [16, 24],
        keyframes: ['first', 'last'],
        promptLength: { min: 2, max: 2048 },
        promptSupported: true,
    },
    // Together quotes $0.1031-$0.221 per 5s clip plus $0.1326 for audio.
    {
        id: 'togetherai:pixverse/pixverse-v5.6',
        puterId: 'togetherai:pixverse/pixverse-v5.6',
        organization: 'PixVerse',
        name: 'PixVerse v5.6',
        model: 'pixverse/pixverse-v5.6',
        costs_currency: 'usd-cents',
        costs: { 'per-second': 7.1, 'default-duration-per-video': 36 },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: null,
        dimensions: null,
        fps: null,
        keyframes: null,
        promptLength: null,
        promptSupported: true,
    },
    {
        id: 'togetherai:pixverse/pixverse-v6',
        puterId: 'togetherai:pixverse/pixverse-v6',
        organization: 'PixVerse',
        name: 'PixVerse v6',
        model: 'pixverse/pixverse-v6',
        costs_currency: 'usd-cents',
        costs: { 'per-second': 11.5, 'default-duration-per-video': 58 },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: null,
        dimensions: null,
        fps: null,
        keyframes: null,
        promptLength: null,
        promptSupported: true,
    },
    {
        id: 'togetherai:kwaivgI/kling-2.1-master',
        puterId: 'togetherai:kwaivgi/kling-2.1-master',
        organization: 'Kuaishou',
        name: 'Kling 2.1 Master',
        model: 'kwaivgI/kling-2.1-master',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 92 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: ['1920x1080', '1080x1080', '1080x1920'],
        fps: [24],
        keyframes: ['first'],
        promptLength: { min: 2, max: 2500 },
        promptSupported: true,
    },
    {
        id: 'togetherai:kwaivgI/kling-2.1-standard',
        puterId: 'togetherai:kwaivgi/kling-2.1-standard',
        organization: 'Kuaishou',
        name: 'Kling 2.1 Standard',
        model: 'kwaivgI/kling-2.1-standard',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 18 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: ['1920x1080', '1080x1080', '1080x1920'],
        fps: [24],
        keyframes: ['first'],
        promptLength: null,
        promptSupported: false,
    },
    {
        id: 'togetherai:kwaivgI/kling-2.1-pro',
        puterId: 'togetherai:kwaivgi/kling-2.1-pro',
        organization: 'Kuaishou',
        name: 'Kling 2.1 Pro',
        model: 'kwaivgI/kling-2.1-pro',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 32 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: ['1920x1080', '1080x1080', '1080x1920'],
        fps: [24],
        keyframes: ['first', 'last'],
        promptLength: null,
        promptSupported: false,
    },
    {
        id: 'togetherai:kwaivgI/kling-1.6-standard',
        puterId: 'togetherai:kwaivgi/kling-1.6-standard',
        organization: 'Kuaishou',
        name: 'Kling 1.6 Standard',
        model: 'kwaivgI/kling-1.6-standard',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 19 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: ['1920x1080', '1080x1080', '1080x1920'],
        fps: [30, 24],
        keyframes: ['first'],
        promptLength: { min: 2, max: 2500 },
        promptSupported: true,
    },
    // Wan 2.7 sizes output by `resolution` + `ratio` and quotes a flat
    // $0.10 per 5 seconds.
    {
        id: 'togetherai:Wan-AI/wan2.7-t2v',
        puterId: 'togetherai:wan-ai/wan2.7-t2v',
        organization: 'Wan-AI',
        name: 'Wan 2.7 T2V',
        model: 'Wan-AI/wan2.7-t2v',
        costs_currency: 'usd-cents',
        costs: { 'per-second': 2, 'default-duration-per-video': 10 },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: seconds(5, 2, 15),
        dimensions: ['720P', '1080P'],
        ratios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
        fps: [30],
        keyframes: null,
        promptLength: { min: 1, max: 5000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:Wan-AI/wan2.7-i2v',
        puterId: 'togetherai:wan-ai/wan2.7-i2v',
        organization: 'Wan-AI',
        name: 'Wan 2.7 I2V',
        model: 'Wan-AI/wan2.7-i2v',
        costs_currency: 'usd-cents',
        costs: { 'per-second': 2, 'default-duration-per-video': 10 },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: seconds(5, 2, 15),
        dimensions: ['720P', '1080P'],
        ratios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
        fps: [30],
        keyframes: ['first', 'last'],
        promptLength: { min: 1, max: 5000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:Wan-AI/wan2.7-r2v',
        puterId: 'togetherai:wan-ai/wan2.7-r2v',
        organization: 'Wan-AI',
        name: 'Wan 2.7 R2V',
        model: 'Wan-AI/wan2.7-r2v',
        costs_currency: 'usd-cents',
        costs: { 'per-second': 2, 'default-duration-per-video': 10 },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: seconds(5, 2, 10),
        dimensions: ['720P', '1080P'],
        ratios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
        fps: [30],
        keyframes: null,
        promptLength: { min: 1, max: 5000 },
        promptSupported: true,
    },
    // HappyHorse: $0.14/s at 720P, $0.24/s (1.0) or $0.18/s (1.1) at 1080p.
    {
        id: 'togetherai:alibaba/happyhorse-1.0-t2v',
        puterId: 'togetherai:alibaba/happyhorse-1.0-t2v',
        organization: 'Alibaba',
        name: 'HappyHorse 1.0 T2V',
        model: 'alibaba/happyhorse-1.0-t2v',
        costs_currency: 'usd-cents',
        costs: { 'per-second': 24, 'default-duration-per-video': 120 },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: null,
        dimensions: null,
        fps: null,
        keyframes: null,
        promptLength: null,
        promptSupported: true,
    },
    {
        id: 'togetherai:alibaba/happyhorse-1.0-i2v',
        puterId: 'togetherai:alibaba/happyhorse-1.0-i2v',
        organization: 'Alibaba',
        name: 'HappyHorse 1.0 I2V',
        model: 'alibaba/happyhorse-1.0-i2v',
        costs_currency: 'usd-cents',
        costs: { 'per-second': 24, 'default-duration-per-video': 120 },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: null,
        dimensions: null,
        fps: null,
        keyframes: ['first'],
        promptLength: null,
        promptSupported: true,
    },
    {
        id: 'togetherai:alibaba/happyhorse-1.0-r2v',
        puterId: 'togetherai:alibaba/happyhorse-1.0-r2v',
        organization: 'Alibaba',
        name: 'HappyHorse 1.0 R2V',
        model: 'alibaba/happyhorse-1.0-r2v',
        costs_currency: 'usd-cents',
        costs: { 'per-second': 24, 'default-duration-per-video': 120 },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: null,
        dimensions: null,
        fps: null,
        keyframes: null,
        promptLength: null,
        promptSupported: true,
    },
    {
        id: 'togetherai:alibaba/happyhorse-1.1-t2v',
        puterId: 'togetherai:alibaba/happyhorse-1.1-t2v',
        organization: 'Alibaba',
        name: 'HappyHorse 1.1 T2V',
        model: 'alibaba/happyhorse-1.1-t2v',
        costs_currency: 'usd-cents',
        costs: { 'per-second': 18, 'default-duration-per-video': 90 },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: null,
        dimensions: null,
        fps: null,
        keyframes: null,
        promptLength: null,
        promptSupported: true,
    },
    {
        id: 'togetherai:alibaba/happyhorse-1.1-i2v',
        puterId: 'togetherai:alibaba/happyhorse-1.1-i2v',
        organization: 'Alibaba',
        name: 'HappyHorse 1.1 I2V',
        model: 'alibaba/happyhorse-1.1-i2v',
        costs_currency: 'usd-cents',
        costs: { 'per-second': 18, 'default-duration-per-video': 90 },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: null,
        dimensions: null,
        fps: null,
        keyframes: ['first'],
        promptLength: null,
        promptSupported: true,
    },
    {
        id: 'togetherai:alibaba/happyhorse-1.1-r2v',
        puterId: 'togetherai:alibaba/happyhorse-1.1-r2v',
        organization: 'Alibaba',
        name: 'HappyHorse 1.1 R2V',
        model: 'alibaba/happyhorse-1.1-r2v',
        costs_currency: 'usd-cents',
        costs: { 'per-second': 18, 'default-duration-per-video': 90 },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: null,
        dimensions: null,
        fps: null,
        keyframes: null,
        promptLength: null,
        promptSupported: true,
    },
    {
        id: 'togetherai:vidu/vidu-q1',
        puterId: 'togetherai:vidu/vidu-q1',
        organization: 'Vidu',
        name: 'Vidu Q1',
        model: 'vidu/vidu-q1',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 22 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: ['1920x1080', '1080x1080', '1080x1920'],
        fps: [24],
        keyframes: ['first', 'last'],
        promptLength: { min: 2, max: 3000 },
        promptSupported: true,
    },
    // Vidu Q3: $0.0455-$0.104/s; Q3 Turbo: $0.13-$0.26/s, by resolution.
    {
        id: 'togetherai:vidu/vidu-q3',
        puterId: 'togetherai:vidu/vidu-q3',
        organization: 'Vidu',
        name: 'Vidu Q3',
        model: 'vidu/vidu-q3',
        costs_currency: 'usd-cents',
        costs: { 'per-second': 10.4, 'default-duration-per-video': 52 },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: null,
        dimensions: null,
        fps: null,
        keyframes: null,
        promptLength: null,
        promptSupported: true,
    },
    {
        id: 'togetherai:vidu/vidu-q3-turbo',
        puterId: 'togetherai:vidu/vidu-q3-turbo',
        organization: 'Vidu',
        name: 'Vidu Q3 Turbo',
        model: 'vidu/vidu-q3-turbo',
        costs_currency: 'usd-cents',
        costs: { 'per-second': 26, 'default-duration-per-video': 130 },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: null,
        dimensions: null,
        fps: null,
        keyframes: null,
        promptLength: null,
        promptSupported: true,
    },
    // FLUX 3 text-to-video: $0.17/s at 720p, $0.29/s at 1080p.
    {
        id: 'togetherai:black-forest-labs/FLUX-3',
        puterId: 'togetherai:black-forest-labs/flux-3',
        organization: 'Black Forest Labs',
        name: 'FLUX 3',
        model: 'black-forest-labs/FLUX-3',
        costs_currency: 'usd-cents',
        costs: { 'per-second': 29, 'default-duration-per-video': 145 },
        output_cost_key: 'default-duration-per-video',
        durationSeconds: null,
        dimensions: null,
        fps: null,
        keyframes: null,
        promptLength: null,
        promptSupported: true,
    },
];
