-- Copyright (C) 2024-present Puter Technologies Inc.
--
-- This file is part of Puter.
--
-- Puter is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Affero General Public License as published
-- by the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU Affero General Public License for more details.
--
-- You should have received a copy of the GNU Affero General Public License
-- along with this program.  If not, see <https://www.gnu.org/licenses/>.

-- TEMP: editor app insert removed — broken, will fix later

-- Intentionally not seeding the default apps (viewer, pdf, camera, player,
-- recorder): their index_url points to *.puter.com, which routes any file
-- opened through them off this instance and onto Puter Technologies Inc.'s
-- production servers. Left as a no-op to preserve migration numbering.
