-- Copyright (C) 2024-present Puter Technologies Inc.
--
-- This file is part of Puter.
--
-- Puter is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Affero General Public License as published
-- by the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU Affero General Public License for more details.
--
-- You should have received a copy of the GNU Affero General Public License
-- along with this program.  If not, see <https://www.gnu.org/licenses/>.

-- Intentionally a no-op. Originally: pointed PDF/Player at puter.com
-- hosted URLs and inserted a Music Player app pointing at
-- player.puter.com. All three route file content through Puter
-- Technologies Inc.'s servers instead of this instance, so they were
-- dropped here. Left as a no-op to preserve migration numbering; the
-- UPDATEs targeted apps that migration 0002 no longer creates anyway.
