// Shapes shared across the `puter.apps` operations. JSDoc-only; no runtime exports.

/**
 * A user of an app, as returned by `App.users()` and `App.getUsers()`.
 *
 * @typedef {Object} AppUser
 * @property {string} username The user's username.
 * @property {string} user_uuid The user's unique identifier.
 * @property {string | null} [user_email] The user's email address. Only present when the user granted
 * this app the `user:<uuid>:email:read` permission (e.g. via `puter.perms.requestEmail()`); omitted
 * otherwise. May be `null` if the user granted access but has no email on file.
 */

/**
 * Pagination options for `App.getUsers()`.
 *
 * @typedef {Object} GetUsersOptions
 * @property {number} [limit] The number of users to retrieve. Default is `100`.
 * @property {number} [offset] The offset to start retrieving users from. Default is `0`.
 */

/**
 * The `App` object containing Puter app details.
 *
 * @typedef {Object} App
 * @property {string} uid The unique identifier of the app, generated by Puter when the app is created.
 * @property {string} name The name of the app.
 * @property {string} index_url The URL of the index file of the app, loaded when the app is started.
 * @property {string} [title] The title of the app.
 * @property {string} [description] The description of the app.
 * @property {string} [icon] The Data URL of the icon of the app (a base64 encoded image).
 * @property {boolean} [maximize_on_start] Whether the app should be maximized when it is started.
 * Default is `false`.
 * @property {boolean} [background] Whether the app should run in the background. Default is `false`.
 * @property {boolean} [feedback_enabled] Whether users can send feedback to the app's developer through
 * `puter.ui.showFeedbackDialog()`. Default is `false` for apps created through `puter.apps.create`; the
 * Dev Center enables it at creation.
 * @property {string[]} [filetype_associations] The file types that the app can open. Each string is in
 * the format `".<extension>"` or `"mime/type"`, e.g. `[".txt", "image/png"]`. For a directory
 * association, the string should be `.directory`.
 * @property {Record<string, unknown>} [metadata] Custom metadata for the app as arbitrary key-value pairs.
 * @property {string} [created_at] The date and time when the app was created, in `YYYY-MM-DDTHH:MM:SSZ`
 * format.
 * @property {number} [open_count] The number of times the app has been opened. If `stats_period` is set
 * to a value other than `all`, this is the count within that period.
 * @property {number} [user_count] The number of users that have access to the app. If `stats_period` is
 * set to a value other than `all`, this is the count within that period.
 * @property {(pageSize?: number) => AsyncIterableIterator<AppUser>} users Iterates over all users of the
 * app, fetching them page by page. `pageSize` defaults to 100.
 * @property {(params?: GetUsersOptions) => Promise<AppUser[]>} getUsers Retrieves a list of users one
 * page at a time as defined by limit and offset.
 */

/**
 * The result returned by `Apps.create()`.
 *
 * @typedef {Object} CreateAppResult
 * @property {string} uid The unique identifier of the app, generated by Puter when the app is created.
 * @property {string} name The name of the app.
 * @property {string} title The title of the app.
 * @property {string} index_url The URL of the index file of the app, loaded when the app is started.
 * @property {string} subdomain The subdomain assigned to the app.
 * @property {{ username: string, uuid: string }} owner Information about the owner of the app.
 */

/**
 * Options for `Apps.list()` and `Apps.get()`.
 *
 * @typedef {Object} AppListOptions
 * @property {string} [stats_period] The period for which to get the user and open count. One of
 * `today`, `yesterday`, `7d`, `30d`, `this_month`, `last_month`, `this_year`, `last_year`,
 * `month_to_date`, `year_to_date`, or `last_12_months`. Default is `all` (all time).
 * @property {null | 16 | 32 | 64 | 128 | 256 | 512} [icon_size] The size of the icons to return.
 * Default is `null` (the original size).
 */

/**
 * Options for creating an app with `Apps.create()`.
 *
 * @typedef {Object} CreateAppOptions
 * @property {string} name The name of the app to create. Must be unique to the user's apps; if an app
 * with this name already exists the promise is rejected.
 * @property {string} indexURL The URL of the app's index page, displayed when the app is started. Must
 * start with `http://` or `https://`; other protocols are not allowed.
 * @property {string} [title] The human-readable title of the app. Defaults to `name` if not provided.
 * @property {string} [description] The description of the app aimed at the end user.
 * @property {string} [icon] The icon of the app.
 * @property {boolean} [maximizeOnStart] Whether the app should be maximized when it is started.
 * Defaults to `false`.
 * @property {boolean} [background] Whether the app should run in the background. Defaults to `false`.
 * @property {boolean} [feedbackEnabled] Whether users can send feedback to the app's developer through
 * `puter.ui.showFeedbackDialog()`. Defaults to `false`.
 * @property {string[]} [filetypeAssociations] The filetypes that the app can open. File extensions and
 * MIME types are supported, e.g. `[".txt", ".md", "application/pdf"]`. Defaults to `[]`.
 * @property {Record<string, unknown>} [metadata] Custom metadata for the app as arbitrary key-value pairs.
 * @property {boolean} [dedupeName] Whether to deduplicate the app name if it already exists. Defaults to
 * `false`.
 */

/**
 * Attributes to update with `Apps.update()`.
 *
 * @typedef {Object} UpdateAppAttributes
 * @property {string} [name] The new name of the app. Must be unique to the user's apps; if an app with
 * this name already exists the promise is rejected.
 * @property {string} [indexURL] The new URL of the app's index page. Must be accessible to the user.
 * @property {string} [title] The new title of the app.
 * @property {string} [description] The new description of the app aimed at the end user.
 * @property {string} [icon] The new icon of the app.
 * @property {boolean} [maximizeOnStart] Whether the app should be maximized when it is started.
 * Defaults to `false`.
 * @property {boolean} [background] Whether the app should run in the background. Defaults to `false`.
 * @property {boolean} [feedbackEnabled] Whether users can send feedback to the app's developer through
 * `puter.ui.showFeedbackDialog()`. Omitted leaves the app's current value unchanged.
 * @property {string[]} [filetypeAssociations] The filetypes that the app can open. File extensions and
 * MIME types are supported, e.g. `[".txt", ".md", "application/pdf"]`. Defaults to `[]`.
 * @property {Record<string, unknown>} [metadata] Custom metadata for the app as arbitrary key-value pairs.
 */

/**
 * The result returned by `Apps.checkName()`.
 *
 * @typedef {Object} CheckAppNameResult
 * @property {string} name The name that was checked.
 * @property {boolean} available Whether the name is available.
 */

export {};
