import { IChatModel } from '../types';

// Hardcoded from https://models.dev/api.json
export const MISTRAL_MODELS: IChatModel[] = [
    {
        puterId: 'mistralai:mistralai/mistral-medium-2508',
        id: 'mistral-medium-2508',
        modalities: { 'input': ['text', 'image'], 'output': ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-05',
        release_date: '2025-08-12',
        name: 'mistral-medium-2508',
        aliases: [
            'mistral-medium-latest',
            'mistral-medium',
            'mistralai/mistral-medium-2508',
        ],
        max_tokens: 131072,
        description: 'Update on Mistral Medium 3 with improved capabilities.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1000000,
            prompt_tokens: 40,
            completion_tokens: 200,
        },
    },
    {
        puterId: 'mistralai:mistralai/open-mistral-7b',
        id: 'open-mistral-7b',
        modalities: { 'input': ['text'], 'output': ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2023-12',
        release_date: '2023-09-27',
        name: 'open-mistral-7b',
        aliases: [
            'mistral-tiny',
            'mistral-tiny-2312',
            'mistralai/open-mistral-7b',
        ],
        max_tokens: 32768,
        description: 'Our first dense model released September 2023.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1000000,
            prompt_tokens: 25,
            completion_tokens: 25,
        },
    },
    {
        puterId: 'mistralai:mistralai/open-mistral-nemo',
        id: 'open-mistral-nemo',
        modalities: { 'input': ['text'], 'output': ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2024-07',
        release_date: '2024-07-01',
        name: 'open-mistral-nemo',
        aliases: [
            'open-mistral-nemo-2407',
            'mistral-tiny-2407',
            'mistral-tiny-latest',
            'mistralai/open-mistral-nemo',
        ],
        max_tokens: 131072,
        description: 'Our best multilingual open source model released July 2024.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1000000,
            prompt_tokens: 15,
            completion_tokens: 15,
        },
    },
    {
        puterId: 'mistralai:mistralai/pixtral-large-2411',
        id: 'pixtral-large-2411',
        modalities: { 'input': ['text', 'image'], 'output': ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2024-11',
        release_date: '2024-11-01',
        name: 'pixtral-large-2411',
        aliases: [
            'pixtral-large-latest',
            'mistral-large-pixtral-2411',
            'mistralai/pixtral-large-2411',
        ],
        max_tokens: 131072,
        description: 'Official pixtral-large-2411 Mistral AI model',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1000000,
            prompt_tokens: 200,
            completion_tokens: 600,
        },
    },
    {
        puterId: 'mistralai:mistralai/codestral-2508',
        id: 'codestral-2508',
        modalities: { 'input': ['text'], 'output': ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2024-10',
        release_date: '2024-05-29',
        name: 'codestral-2508',
        aliases: [
            'codestral-latest',
            'mistralai/codestral-2508',
        ],
        max_tokens: 256000,
        description: 'Our cutting-edge language model for coding released August 2025.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1000000,
            prompt_tokens: 30,
            completion_tokens: 90,
        },
    },
    {
        puterId: 'mistralai:mistralai/devstral-small-2507',
        id: 'devstral-small-2507',
        modalities: { 'input': ['text'], 'output': ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-05',
        release_date: '2025-07-10',
        name: 'devstral-small-2507',
        aliases: [
            'devstral-small-latest',
            'mistralai/devstral-small-2507',
        ],
        max_tokens: 131072,
        description: 'Our small open-source code-agentic model.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1000000,
            prompt_tokens: 10,
            completion_tokens: 30,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'mistralai:mistralai/devstral-medium-2507',
        id: 'devstral-medium-2507',
        modalities: { 'input': ['text'], 'output': ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-05',
        release_date: '2025-07-10',
        name: 'devstral-medium-2507',
        aliases: [
            'devstral-medium-latest',
            'mistralai/devstral-medium-2507',
        ],
        max_tokens: 131072,
        description: 'Our medium code-agentic model.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1000000,
            prompt_tokens: 40,
            completion_tokens: 200,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'mistralai:mistralai/mistral-small-2506',
        id: 'mistral-small-2506',
        modalities: { 'input': ['text', 'image'], 'output': ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-03',
        release_date: '2025-06-20',
        name: 'mistral-small-2506',
        aliases: [
            'mistral-small-latest',
            'mistralai/mistral-small-2506',
        ],
        max_tokens: 131072,
        description: 'Our latest enterprise-grade small model with the latest version released June 2025.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1000000,
            prompt_tokens: 10,
            completion_tokens: 30,
        },
    },
    {
        puterId: 'mistralai:mistralai/magistral-medium-2509',
        id: 'magistral-medium-2509',
        modalities: { 'input': ['text'], 'output': ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-06',
        release_date: '2025-03-17',
        name: 'magistral-medium-2509',
        aliases: [
            'magistral-medium-latest',
            'mistralai/magistral-medium-2509',
        ],
        max_tokens: 131072,
        description: 'Our frontier-class reasoning model release candidate September 2025.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1000000,
            prompt_tokens: 200,
            completion_tokens: 500,
        },
    },
    {
        puterId: 'mistralai:mistralai/magistral-small-2509',
        id: 'magistral-small-2509',
        modalities: { 'input': ['text'], 'output': ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-06',
        release_date: '2025-03-17',
        name: 'magistral-small-2509',
        aliases: [
            'magistral-small-latest',
            'mistralai/magistral-small-2509',
        ],
        max_tokens: 131072,
        description: 'Our efficient reasoning model released September 2025.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1000000,
            prompt_tokens: 50,
            completion_tokens: 150,
        },
    },
    {
        puterId: 'mistralai:mistralai/voxtral-mini-2507',
        id: 'voxtral-mini-2507',
        name: 'voxtral-mini-2507',
        aliases: [
            'voxtral-mini-latest',
            'mistralai/voxtral-mini-2507',
        ],
        max_tokens: 32768,
        description: 'A mini audio understanding model released in July 2025',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1000000,
            prompt_tokens: 4,
            completion_tokens: 4,
        },
    },
    {
        puterId: 'mistralai:mistralai/voxtral-small-2507',
        id: 'voxtral-small-2507',
        name: 'voxtral-small-2507',
        aliases: [
            'voxtral-small-latest',
            'mistralai/voxtral-small-2507',
        ],
        max_tokens: 32768,
        description: 'A small audio understanding model released in July 2025',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1000000,
            prompt_tokens: 10,
            completion_tokens: 30,
        },
    },
    {
        puterId: 'mistralai:mistralai/mistral-large-2512',
        id: 'mistral-large-latest',
        modalities: { 'input': ['text', 'image'], 'output': ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2024-11',
        release_date: '2024-11-01',
        name: 'mistral-large-2512',
        aliases: [
            'mistral-large-2512',
            'mistralai/mistral-large-2512',
        ],
        max_tokens: 262144,
        description: 'Official mistral-large-2512 Mistral AI model',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1000000,
            prompt_tokens: 50,
            completion_tokens: 150,
        },
    },
    {
        puterId: 'mistralai:mistralai/ministral-3b-2512',
        id: 'ministral-3b-2512',
        modalities: { 'input': ['text'], 'output': ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2024-10',
        release_date: '2024-10-01',
        name: 'ministral-3b-2512',
        aliases: [
            'ministral-3b-latest',
            'mistralai/ministral-3b-2512',
        ],
        max_tokens: 131072,
        description: 'Ministral 3 (a.k.a. Tinystral) 3B Instruct.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1000000,
            prompt_tokens: 10,
            completion_tokens: 10,
        },
    },
    {
        puterId: 'mistralai:mistralai/ministral-8b-2512',
        id: 'ministral-8b-2512',
        modalities: { 'input': ['text'], 'output': ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2024-10',
        release_date: '2024-10-01',
        name: 'ministral-8b-2512',
        aliases: [
            'ministral-8b-latest',
            'mistralai/ministral-8b-2512',
        ],
        max_tokens: 262144,
        description: 'Ministral 3 (a.k.a. Tinystral) 8B Instruct.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1000000,
            prompt_tokens: 15,
            completion_tokens: 15,
        },
    },
    {
        puterId: 'mistralai:mistralai/ministral-14b-2512',
        id: 'ministral-14b-2512',
        name: 'ministral-14b-2512',
        aliases: [
            'ministral-14b-latest',
            'mistralai/ministral-14b-2512',
        ],
        max_tokens: 262144,
        description: 'Ministral 3 (a.k.a. Tinystral) 14B Instruct.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1000000,
            prompt_tokens: 20,
            completion_tokens: 20,
        },
    },
];
