/*
 * Copyright (C) 2024  Puter Technologies Inc.
 *
 * This file is part of Phoenix Shell.
 *
 * Phoenix Shell is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
// Generated by /tools/gen.js
import module_ai from './ai.js'
import module_basename from './basename.js'
import module_cat from './cat.js'
import module_cd from './cd.js'
import module_changelog from './changelog.js'
import module_clear from './clear.js'
import module_concept_parser from './concept-parser.js'
import module_cp from './cp.js'
import module_date from './date.js'
import module_dcall from './dcall.js'
import module_dirname from './dirname.js'
import module_echo from './echo.js'
import module_env from './env.js'
import module_errno from './errno.js'
import module_exit from './exit.js'
import module_false from './false.js'
import module_grep from './grep.js'
import module_head from './head.js'
import module_help from './help.js'
import module_jq from './jq.js'
import module_login from './login.js'
import module_ls from './ls.js'
import module_man from './man.js'
import module_mkdir from './mkdir.js'
import module_mv from './mv.js'
import module_neofetch from './neofetch.js'
import module_printf from './printf.js'
import module_printhist from './printhist.js'
import module_pwd from './pwd.js'
import module_rm from './rm.js'
import module_rmdir from './rmdir.js'
import module_sample_data from './sample-data.js'
import module_sed from './sed.js'
import module_sleep from './sleep.js'
import module_sort from './sort.js'
import module_tail from './tail.js'
import module_test from './test.js'
import module_touch from './touch.js'
import module_true from './true.js'
import module_txt2img from './txt2img.js'
import module_usages from './usages.js'
import module_wc from './wc.js'
import module_which from './which.js'

export default {
    "ai": module_ai,
    "basename": module_basename,
    "cat": module_cat,
    "cd": module_cd,
    "changelog": module_changelog,
    "clear": module_clear,
    "concept-parser": module_concept_parser,
    "cp": module_cp,
    "date": module_date,
    "dcall": module_dcall,
    "dirname": module_dirname,
    "echo": module_echo,
    "env": module_env,
    "errno": module_errno,
    "exit": module_exit,
    "false": module_false,
    "grep": module_grep,
    "head": module_head,
    "help": module_help,
    "jq": module_jq,
    "login": module_login,
    "ls": module_ls,
    "man": module_man,
    "mkdir": module_mkdir,
    "mv": module_mv,
    "neofetch": module_neofetch,
    "printf": module_printf,
    "printhist": module_printhist,
    "pwd": module_pwd,
    "rm": module_rm,
    "rmdir": module_rmdir,
    "sample-data": module_sample_data,
    "sed": module_sed,
    "sleep": module_sleep,
    "sort": module_sort,
    "tail": module_tail,
    "test": module_test,
    "touch": module_touch,
    "true": module_true,
    "txt2img": module_txt2img,
    "usages": module_usages,
    "wc": module_wc,
    "which": module_which,
};
