-- Copyright (C) 2024-present Puter Technologies Inc.
--
-- Intentionally a no-op. Originally: pointed PDF/Player at puter.com
-- hosted URLs and inserted a Music Player app pointing at
-- player.puter.com. All three route file content through Puter
-- Technologies Inc.'s servers instead of this instance, so they were
-- dropped here (mirrors SQLite migration 0049). Left as a no-op to
-- preserve migration numbering; the UPDATEs targeted apps that
-- mysql_mig_2.sql no longer creates anyway.
