/*
 * Copyright (C) 2024-present Puter Technologies Inc.
 *
 * This file is part of Puter.
 *
 * Puter is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import type { IChatModel } from '../../types.js';

// Hardcoded from https://models.dev/api.json and https://docs.mistral.ai/models/overview
export const MISTRAL_MODELS: IChatModel[] = [
    {
        puterId: 'mistralai:mistralai/mistral-medium-2604',
        id: 'mistral-medium-2604',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2026-04',
        release_date: '2026-04-29',
        name: 'Mistral Medium 3.5',
        aliases: [
            'mistral-medium-3-5',
            'mistral-medium-3.5',
            'mistral-medium-3',
            'mistral-medium-latest',
            'mistral-medium',
            'mistralai/mistral-medium-3-5',
            'mistralai/mistral-medium-2604',
        ],
        context: 262_144,
        max_tokens: 262_144,
        description:
            'State-of-the-art multimodal model optimized for agentic and coding tasks.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 150,
            completion_tokens: 750,
        },
    },
    {
        puterId: 'mistralai:mistralai/mistral-large-2512',
        id: 'mistral-large-2512',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-12',
        release_date: '2025-12-02',
        name: 'Mistral Large 3',
        aliases: [
            'mistral-large-latest',
            'mistral-large',
            'mistralai/mistral-large-latest',
            'mistralai/mistral-large-2512',
        ],
        context: 262_144,
        max_tokens: 262_144,
        description:
            'State-of-the-art, open-weight, general-purpose multimodal model.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 50,
            completion_tokens: 150,
        },
    },
    {
        puterId: 'mistralai:mistralai/mistral-small-2603',
        id: 'mistral-small-2603',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-06',
        release_date: '2026-03-16',
        name: 'Mistral Small 4',
        aliases: [
            'mistral-small-latest',
            'mistral-small',
            'mistralai/mistral-small-latest',
            'mistralai/mistral-small-2603',
        ],
        context: 256_000,
        max_tokens: 256_000,
        description:
            'Hybrid open-weight model for instruct, reasoning, and coding tasks.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 15,
            completion_tokens: 60,
        },
    },
    {
        puterId: 'mistralai:mistralai/zai-glm-5-2',
        id: 'zai-glm-5-2',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        release_date: '2026-08-06',
        name: 'Z.ai GLM 5.2',
        aliases: ['glm-5-2'],
        context: 1_000_000,
        max_tokens: 128_000,
        description:
            'Third-party open-source model from Z.ai, hosted by Mistral for long-context coding and agentic workflows.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 140,
            completion_tokens: 440,
        },
    },
    {
        puterId: 'mistralai:mistralai/codestral-2508',
        id: 'codestral-2508',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-08',
        release_date: '2025-08-29',
        name: 'Codestral',
        aliases: ['codestral-latest', 'mistralai/codestral-2508'],
        context: 256_000,
        max_tokens: 256_000,
        description:
            'Cutting-edge language model for code completion, proficient in over 80 programming languages.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 30,
            completion_tokens: 90,
        },
    },
    {
        puterId: 'mistralai:mistralai/magistral-small-latest',
        id: 'magistral-small-latest',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-06',
        release_date: '2025-09-01',
        name: 'Magistral Small',
        aliases: [
            'magistral-small-2509',
            'mistralai/magistral-small-2509',
            'mistralai/magistral-small-latest',
        ],
        context: 131_072,
        max_tokens: 131_072,
        description: 'Efficient open-weight reasoning model.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 50,
            completion_tokens: 150,
        },
    },
    {
        puterId: 'mistralai:mistralai/ministral-14b-2512',
        id: 'ministral-14b-2512',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-12',
        release_date: '2025-12-16',
        name: 'Ministral 3 14B',
        aliases: ['ministral-14b-latest', 'mistralai/ministral-14b-2512'],
        context: 262_144,
        max_tokens: 262_144,
        description:
            'Best-in-class compact model with text and vision capabilities.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 20,
            completion_tokens: 20,
        },
    },
    {
        puterId: 'mistralai:mistralai/ministral-8b-2512',
        id: 'ministral-8b-2512',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-12',
        release_date: '2025-12-16',
        name: 'Ministral 3 8B',
        aliases: ['ministral-8b-latest', 'mistralai/ministral-8b-2512'],
        context: 262_144,
        max_tokens: 262_144,
        description:
            'Efficient compact model with text and vision capabilities.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 10,
            completion_tokens: 10,
        },
    },
    {
        puterId: 'mistralai:mistralai/ministral-3b-2512',
        id: 'ministral-3b-2512',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-12',
        release_date: '2025-12-16',
        name: 'Ministral 3 3B',
        aliases: ['ministral-3b-latest', 'mistralai/ministral-3b-2512'],
        context: 131_072,
        max_tokens: 131_072,
        description: 'Tiny, efficient model with multimodal support.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 4,
            completion_tokens: 4,
        },
    },
    {
        puterId: 'mistralai:mistralai/voxtral-small-2507',
        id: 'voxtral-small-2507',
        modalities: { input: ['text', 'audio'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-07',
        release_date: '2025-07-15',
        name: 'Voxtral Small',
        aliases: [
            'voxtral-small-latest',
            'mistralai/voxtral-small-2507',
            'mistralai/voxtral-small-latest',
        ],
        context: 32_768,
        max_tokens: 32_768,
        description: 'Audio-input model for instruct tasks.',
        provider: 'mistral',
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 10,
            completion_tokens: 30,
        },
    },
];
