/*
 * Copyright (C) 2024-present Puter Technologies Inc.
 *
 * This file is part of Puter.
 *
 * Puter is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import type { IChatModel } from '../../types.js';

// Hardcoded from https://models.dev/api.json
export const ALIBABA_MODELS: IChatModel[] = [
    // -- Commercial flagship ----------------------------------------
    {
        puterId: 'alibaba:qwen/qwen-max',
        id: 'qwen-max',
        name: 'Qwen Max',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2024-04-03',
        aliases: ['qwen/qwen-max'],
        context: 32_768,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 160,
            completion_tokens: 640,
            cached_tokens: 0,
        },
    },

    // -- Plus tier --------------------------------------------------
    {
        puterId: 'alibaba:qwen/qwen-plus',
        id: 'qwen-plus',
        name: 'Qwen Plus',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2024-01-25',
        aliases: ['qwen/qwen-plus'],
        context: 1_000_000,
        max_tokens: 32_768,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 40,
            completion_tokens: 120,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.5-plus',
        id: 'qwen3.5-plus',
        name: 'Qwen3.5 Plus',
        modalities: { input: ['text', 'image', 'video'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2026-02-16',
        aliases: ['qwen/qwen3.5-plus'],
        context: 1_000_000,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 40,
            completion_tokens: 240,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.6-plus',
        id: 'qwen3.6-plus',
        name: 'Qwen3.6 Plus',
        modalities: { input: ['text', 'image', 'video'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2026-04-02',
        aliases: ['qwen/qwen3.6-plus', 'qwen3.6-plus-2026-04-02'],
        context: 1_000_000,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 50,
            completion_tokens: 300,
            cached_tokens: 5,
        },
    },

    {
        puterId: 'alibaba:qwen/qwen3.6-flash',
        id: 'qwen3.6-flash',
        modalities: { input: ['text', 'image', 'video'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        release_date: '2026-04-27',
        name: 'Qwen3.6 Flash',
        aliases: ['qwen/qwen3.6-flash', 'qwen3.6-flash-2026-04-16'],
        context: 1_000_000,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 19,
            completion_tokens: 113,
        },
        max_tokens: 65_536,
    },
    {
        puterId: 'alibaba:qwen/qwen3.7-plus',
        id: 'qwen3.7-plus',
        modalities: { input: ['text', 'image', 'video'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        release_date: '2026-06-02',
        name: 'Qwen3.7 Plus',
        aliases: ['qwen/qwen3.7-plus', 'qwen3.7-plus-2026-05-26'],
        context: 1_000_000,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 50,
            completion_tokens: 300,
            cached_tokens: 5,
        },
        max_tokens: 65_536,
    },
    {
        puterId: 'alibaba:qwen/qwen3.7-max',
        id: 'qwen3.7-max',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        release_date: '2026-05-21',
        name: 'Qwen3.7 Max',
        aliases: ['qwen/qwen3.7-max'],
        context: 1_000_000,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 250,
            completion_tokens: 750,
            cached_tokens: 50,
        },
        max_tokens: 65_536,
    },
    {
        puterId: 'alibaba:qwen/qwen3.8-max',
        id: 'qwen3.8-max',
        modalities: {
            input: ['text', 'image', 'video', 'pdf'],
            output: ['text'],
        },
        open_weights: false,
        tool_call: true,
        release_date: '2026-08-03',
        name: 'Qwen3.8 Max',
        aliases: ['qwen/qwen3.8-max'],
        context: 1_000_000,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 200,
            completion_tokens: 600,
            cached_tokens: 25,
        },
        max_tokens: 131_072,
    },
    {
        puterId: 'alibaba:qwen/qwen3.8-max-0902',
        id: 'qwen3.8-max-0902',
        name: 'Qwen3.8 Max (0902)',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        release_date: '2026-09-02',
        aliases: ['qwen/qwen3.8-max-0902'],
        context: 1_000_000,
        max_tokens: 131_072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 200,
            completion_tokens: 600,
            cached_tokens: 25,
        },
    },

    // -- Turbo / Flash tier -----------------------------------------
    {
        puterId: 'alibaba:qwen/qwen-flash',
        id: 'qwen-flash',
        name: 'Qwen Flash',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2025-07-28',
        aliases: ['qwen/qwen-flash'],
        context: 1_000_000,
        max_tokens: 32_768,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 5,
            completion_tokens: 40,
            cached_tokens: 0,
        },
    },

    // -- Coding models ----------------------------------------------
    {
        puterId: 'alibaba:qwen/qwen3-coder-flash',
        id: 'qwen3-coder-flash',
        name: 'Qwen3 Coder Flash',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2025-07-28',
        aliases: ['qwen/qwen3-coder-flash'],
        context: 1_000_000,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 30,
            completion_tokens: 150,
            cached_tokens: 0,
        },
    },

    // -- Open-weight Qwen3.5 ----------------------------------------
    {
        puterId: 'alibaba:qwen/qwen3.5-397b-a17b',
        id: 'qwen3.5-397b-a17b',
        name: 'Qwen3.5 397B-A17B',
        modalities: {
            input: ['text', 'image', 'video', 'audio'],
            output: ['text'],
        },
        open_weights: true,
        tool_call: true,
        release_date: '2026-02-15',
        aliases: ['qwen/qwen3.5-397b-a17b'],
        context: 262_144,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 60,
            completion_tokens: 360,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.5-122b-a10b',
        id: 'qwen3.5-122b-a10b',
        name: 'Qwen3.5 122B-A10B',
        modalities: {
            input: ['text', 'image', 'video', 'audio'],
            output: ['text'],
        },
        open_weights: true,
        tool_call: true,
        release_date: '2026-02-23',
        aliases: ['qwen/qwen3.5-122b-a10b'],
        context: 262_144,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 40,
            completion_tokens: 320,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.5-35b-a3b',
        id: 'qwen3.5-35b-a3b',
        name: 'Qwen3.5 35B-A3B',
        modalities: {
            input: ['text', 'image', 'video', 'audio'],
            output: ['text'],
        },
        open_weights: true,
        tool_call: true,
        release_date: '2026-02-23',
        aliases: ['qwen/qwen3.5-35b-a3b'],
        context: 262_144,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 25,
            completion_tokens: 200,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.5-27b',
        id: 'qwen3.5-27b',
        name: 'Qwen3.5 27B',
        modalities: {
            input: ['text', 'image', 'video', 'audio'],
            output: ['text'],
        },
        open_weights: true,
        tool_call: true,
        release_date: '2026-02-23',
        aliases: ['qwen/qwen3.5-27b'],
        context: 262_144,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 30,
            completion_tokens: 240,
            cached_tokens: 0,
        },
    },

    // -- Open-weight Qwen3.6 ----------------------------------------
    {
        puterId: 'alibaba:qwen/qwen3.6-35b-a3b',
        id: 'qwen3.6-35b-a3b',
        name: 'Qwen3.6 35B-A3B',
        modalities: {
            input: ['text', 'image', 'video', 'audio'],
            output: ['text'],
        },
        open_weights: true,
        tool_call: true,
        release_date: '2026-04-17',
        aliases: ['qwen/qwen3.6-35b-a3b'],
        context: 262_144,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 24.8,
            completion_tokens: 148.5,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.6-27b',
        id: 'qwen3.6-27b',
        name: 'Qwen3.6 27B',
        modalities: {
            input: ['text', 'image', 'video', 'audio'],
            output: ['text'],
        },
        open_weights: true,
        tool_call: true,
        release_date: '2026-04-22',
        aliases: ['qwen/qwen3.6-27b'],
        context: 262_144,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 60,
            completion_tokens: 360,
            cached_tokens: 0,
        },
    },

    // -- Vision models ----------------------------------------------
    {
        puterId: 'alibaba:qwen/qwen3-vl-plus',
        id: 'qwen3-vl-plus',
        name: 'Qwen3-VL Plus',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2025-09-23',
        aliases: ['qwen/qwen3-vl-plus'],
        context: 262_144,
        max_tokens: 32_768,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 20,
            completion_tokens: 160,
            cached_tokens: 0,
        },
    },
    // -- Omni models (text interface, audio costs excluded) ---------
    {
        puterId: 'alibaba:qwen/qwen3-omni-flash',
        id: 'qwen3-omni-flash',
        name: 'Qwen3-Omni Flash',
        modalities: {
            input: ['text', 'image', 'audio', 'video'],
            output: ['text'],
        },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2025-09-15',
        aliases: ['qwen/qwen3-omni-flash'],
        context: 65_536,
        max_tokens: 16_384,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 43,
            completion_tokens: 166,
            cached_tokens: 0,
        },
    },
    // -- Translation models -----------------------------------------
    {
        puterId: 'alibaba:qwen/qwen-mt-plus',
        id: 'qwen-mt-plus',
        name: 'Qwen-MT Plus',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: false,
        knowledge: '2024-04',
        release_date: '2025-01',
        aliases: ['qwen/qwen-mt-plus'],
        context: 16_384,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 246,
            completion_tokens: 737,
            cached_tokens: 0,
        },
    },

    // -- Qwen Plus snapshots (all priced identically to qwen-plus) ---
    {
        puterId: 'alibaba:qwen/qwen-plus-2025-01-25',
        id: 'qwen-plus-2025-01-25',
        name: 'Qwen Plus (2025-01-25)',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        release_date: '2025-01-25',
        aliases: ['qwen/qwen-plus-2025-01-25'],
        context: 1_000_000,
        max_tokens: 32_768,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 40,
            completion_tokens: 120,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen-plus-2025-04-28',
        id: 'qwen-plus-2025-04-28',
        name: 'Qwen Plus (2025-04-28)',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        release_date: '2025-04-28',
        aliases: ['qwen/qwen-plus-2025-04-28'],
        context: 1_000_000,
        max_tokens: 32_768,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 40,
            completion_tokens: 120,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen-plus-2025-07-14',
        id: 'qwen-plus-2025-07-14',
        name: 'Qwen Plus (2025-07-14)',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        release_date: '2025-07-14',
        aliases: ['qwen/qwen-plus-2025-07-14'],
        context: 1_000_000,
        max_tokens: 32_768,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 40,
            completion_tokens: 120,
            cached_tokens: 0,
        },
    },
    // 'qwen-plus-latest' floats to the newest snapshot; kept on the newest
    // dated entry.
    {
        puterId: 'alibaba:qwen/qwen-plus-2025-12-01',
        id: 'qwen-plus-2025-12-01',
        name: 'Qwen Plus (2025-12-01)',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        release_date: '2025-12-01',
        aliases: ['qwen/qwen-plus-2025-12-01', 'qwen-plus-latest'],
        context: 1_000_000,
        max_tokens: 32_768,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 40,
            completion_tokens: 120,
            cached_tokens: 0,
        },
    },
    // -- Qwen3.7 Max snapshots and preview ------------------------
    {
        puterId: 'alibaba:qwen/qwen3.7-max-2026-05-20',
        id: 'qwen3.7-max-2026-05-20',
        name: 'Qwen3.7 Max (2026-05-20)',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        release_date: '2026-05-20',
        aliases: ['qwen/qwen3.7-max-2026-05-20'],
        context: 1_000_000,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 250,
            completion_tokens: 750,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.7-max-2026-06-08',
        id: 'qwen3.7-max-2026-06-08',
        name: 'Qwen3.7 Max (2026-06-08)',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        release_date: '2026-06-08',
        aliases: ['qwen/qwen3.7-max-2026-06-08'],
        context: 1_000_000,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 250,
            completion_tokens: 750,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.7-max-2026-05-17',
        id: 'qwen3.7-max-2026-05-17',
        name: 'Qwen3.7 Max (2026-05-17)',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        release_date: '2026-05-17',
        aliases: ['qwen/qwen3.7-max-2026-05-17'],
        context: 1_000_000,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 250,
            completion_tokens: 750,
            cached_tokens: 0,
        },
    },
    // No vendor-documented release date for the preview; omitted rather
    // than guessed.
    {
        puterId: 'alibaba:qwen/qwen3.7-max-preview',
        id: 'qwen3.7-max-preview',
        name: 'Qwen3.7 Max Preview',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        aliases: ['qwen/qwen3.7-max-preview'],
        context: 1_000_000,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 250,
            completion_tokens: 750,
            cached_tokens: 0,
        },
    },
    // -- Qwen3.5 Plus snapshots -----------------------------------
    {
        puterId: 'alibaba:qwen/qwen3.5-plus-2026-02-15',
        id: 'qwen3.5-plus-2026-02-15',
        name: 'Qwen3.5 Plus (2026-02-15)',
        modalities: { input: ['text', 'image', 'video'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2026-02-15',
        aliases: ['qwen/qwen3.5-plus-2026-02-15'],
        context: 1_000_000,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 40,
            completion_tokens: 240,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.5-plus-2026-04-20',
        id: 'qwen3.5-plus-2026-04-20',
        name: 'Qwen3.5 Plus (2026-04-20)',
        modalities: { input: ['text', 'image', 'video'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2026-04-20',
        aliases: ['qwen/qwen3.5-plus-2026-04-20'],
        context: 1_000_000,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 40,
            completion_tokens: 240,
            cached_tokens: 0,
        },
    },
    // -- Qwen3.5 / Qwen3.7 / Qwen3.8 Flash -----------------------
    {
        puterId: 'alibaba:qwen/qwen3.5-flash',
        id: 'qwen3.5-flash',
        name: 'Qwen3.5 Flash',
        modalities: { input: ['text', 'image', 'video'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2026-02-23',
        aliases: ['qwen/qwen3.5-flash', 'qwen3.5-flash-2026-02-23'],
        context: 1_000_000,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 10,
            completion_tokens: 40,
            cached_tokens: 1,
        },
    },
    // Tiered by input length; base tier (<=32K input) encoded here.
    {
        puterId: 'alibaba:qwen/qwen3.7-flash',
        id: 'qwen3.7-flash',
        name: 'Qwen3.7 Flash',
        modalities: { input: ['text', 'image', 'video'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        release_date: '2026-07-15',
        aliases: ['qwen/qwen3.7-flash', 'qwen3.7-flash-2026-07-15'],
        context: 1_000_000,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 3,
            completion_tokens: 13,
            cached_tokens: 0.3,
        },
    },
    // No vendor-documented release date; omitted rather than guessed.
    {
        puterId: 'alibaba:qwen/qwen3.8-flash',
        id: 'qwen3.8-flash',
        name: 'Qwen3.8 Flash',
        modalities: { input: ['text', 'image', 'video'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        aliases: ['qwen/qwen3.8-flash'],
        context: 1_000_000,
        max_tokens: 131_072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 15,
            completion_tokens: 47,
            cached_tokens: 1.6,
        },
    },
    // -- Open-weight Qwen3.8 --------------------------------------
    {
        puterId: 'alibaba:qwen/qwen3.8-27b',
        id: 'qwen3.8-27b',
        name: 'Qwen3.8 27B',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        release_date: '2026-08-14',
        aliases: ['qwen/qwen3.8-27b'],
        context: 262_144,
        max_tokens: 32_768,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 50,
            completion_tokens: 300,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.8-2.4t-a95b',
        id: 'qwen3.8-2.4t-a95b',
        name: 'Qwen3.8 2.4T-A95B',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        release_date: '2026-08-12',
        aliases: ['qwen/qwen3.8-2.4t-a95b'],
        context: 262_144,
        max_tokens: 131_072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 200,
            completion_tokens: 600,
            cached_tokens: 0,
        },
    },
    // -- Omni additions (text interface, audio costs excluded) ----
    {
        puterId: 'alibaba:qwen/qwen3.5-omni-flash',
        id: 'qwen3.5-omni-flash',
        name: 'Qwen3.5-Omni Flash',
        modalities: {
            input: ['text', 'image', 'video', 'audio'],
            output: ['text'],
        },
        open_weights: false,
        tool_call: true,
        release_date: '2026-03-15',
        aliases: ['qwen/qwen3.5-omni-flash', 'qwen3.5-omni-flash-2026-03-15'],
        context: 49_152,
        max_tokens: 16_384,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 40,
            completion_tokens: 220,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.5-omni-plus',
        id: 'qwen3.5-omni-plus',
        name: 'Qwen3.5-Omni Plus',
        modalities: {
            input: ['text', 'image', 'video', 'audio'],
            output: ['text'],
        },
        open_weights: false,
        tool_call: true,
        release_date: '2026-03-15',
        aliases: ['qwen/qwen3.5-omni-plus', 'qwen3.5-omni-plus-2026-03-15'],
        context: 983_616,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 140,
            completion_tokens: 830,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.8-omni-flash',
        id: 'qwen3.8-omni-flash',
        name: 'Qwen3.8-Omni Flash',
        modalities: {
            input: ['text', 'image', 'video', 'audio'],
            output: ['text'],
        },
        open_weights: false,
        tool_call: true,
        release_date: '2026-09-17',
        aliases: ['qwen/qwen3.8-omni-flash'],
        context: 1_000_000,
        max_tokens: 131_072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 15,
            completion_tokens: 47,
            cached_tokens: 1.6,
        },
    },
    // -- Translation additions ------------------------------------
    // No vendor-documented release date; omitted rather than guessed.
    {
        puterId: 'alibaba:qwen/qwen-mt-flash',
        id: 'qwen-mt-flash',
        name: 'Qwen-MT Flash',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: false,
        aliases: ['qwen/qwen-mt-flash'],
        context: 16_384,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 16,
            completion_tokens: 49,
            cached_tokens: 0,
        },
    },
    // No vendor-documented release date; omitted rather than guessed.
    {
        puterId: 'alibaba:qwen/qwen-mt-lite',
        id: 'qwen-mt-lite',
        name: 'Qwen-MT Lite',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: false,
        aliases: ['qwen/qwen-mt-lite'],
        context: 16_384,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 12,
            completion_tokens: 36,
            cached_tokens: 0,
        },
    },
    // -- Third-party models hosted on Model Studio ------------------
    // Prices are Alibaba's international (Singapore) rates, not the
    // upstream vendors' own rates. No cross-provider aliases on purpose.
    {
        puterId: 'alibaba:zhipu/glm-5.1',
        id: 'glm-5.1',
        name: 'GLM-5.1',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        release_date: '2026-04',
        context: 202_752,
        max_tokens: 128_000,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 140,
            completion_tokens: 440,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:zhipu/glm-5.2',
        id: 'glm-5.2',
        name: 'GLM-5.2',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        release_date: '2026-06-13',
        context: 1_000_000,
        max_tokens: 131_072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 140,
            completion_tokens: 440,
            cached_tokens: 0,
        },
    },
    // No vendor-documented release date for the preview; omitted rather
    // than guessed.
    {
        puterId: 'alibaba:zhipu/glm-5.2-fast-preview',
        id: 'glm-5.2-fast-preview',
        name: 'GLM-5.2 Fast Preview',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        context: 1_000_000,
        max_tokens: 131_072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 280,
            completion_tokens: 880,
            cached_tokens: 0,
        },
    },
    // Time-of-day pricing upstream (busy $0.44/$1.32, idle $0.22/$0.66
    // per MTok); the busy rate is encoded so cached-off-peak use is never
    // under-billed.
    {
        puterId: 'alibaba:deepseek/deepseek-v4-flash-0731',
        id: 'deepseek-v4-flash-0731',
        name: 'DeepSeek V4 Flash (0731)',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-05',
        release_date: '2026-07-31',
        context: 1_000_000,
        max_tokens: 384_000,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 44,
            completion_tokens: 132,
            cached_tokens: 0,
        },
    },
    // Time-of-day pricing upstream (busy $0.30/$1.20, idle $0.15/$0.60
    // per MTok); the busy rate is encoded so off-peak use is never
    // under-billed.
    {
        puterId: 'alibaba:deepseek/deepseek-v4.1-flash',
        id: 'deepseek-v4.1-flash',
        name: 'DeepSeek V4.1 Flash',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        release_date: '2026-09-13',
        context: 1_000_000,
        max_tokens: 393_216,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 30,
            completion_tokens: 120,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:deepseek/deepseek-v4-pro',
        id: 'deepseek-v4-pro',
        name: 'DeepSeek V4 Pro',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-05',
        release_date: '2026-04-24',
        context: 1_000_000,
        max_tokens: 384_000,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 240,
            completion_tokens: 480,
            cached_tokens: 0,
        },
    },
    // Time-of-day pricing upstream (busy $1.32/$3.96, idle $0.66/$1.98
    // per MTok); the busy rate is encoded so cached-off-peak use is never
    // under-billed.
    {
        puterId: 'alibaba:deepseek/deepseek-v4-pro-0813',
        id: 'deepseek-v4-pro-0813',
        name: 'DeepSeek V4 Pro (0813)',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        release_date: '2026-08-13',
        context: 1_000_000,
        max_tokens: 384_000,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 132,
            completion_tokens: 396,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:moonshotai/kimi-k2.7-code',
        id: 'kimi-k2.7-code',
        name: 'Kimi K2.7 Code',
        modalities: { input: ['text', 'image', 'video'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-01',
        release_date: '2026-06-12',
        context: 262_144,
        max_tokens: 262_144,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 95,
            completion_tokens: 400,
            cached_tokens: 0,
        },
    },
];
