/**
 * Copyright (C) 2024-present Puter Technologies Inc.
 *
 * This file is part of Puter.
 *
 * Puter is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import type { IChatModel } from '../../types.js';

// Hardcoded from https://models.dev/api.json
export const ALIBABA_MODELS: IChatModel[] = [
    // ── Commercial flagship ────────────────────────────────────────
    {
        puterId: 'alibaba:qwen/qwen-max',
        id: 'qwen-max',
        name: 'Qwen Max',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2024-04-03',
        aliases: ['qwen/qwen-max'],
        context: 32_768,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 160,
            completion_tokens: 640,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3-max',
        id: 'qwen3-max',
        name: 'Qwen3 Max',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2025-09-23',
        aliases: ['qwen/qwen3-max'],
        context: 262_144,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 120,
            completion_tokens: 600,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.6-max-preview',
        id: 'qwen3.6-max-preview',
        name: 'Qwen3.6 Max Preview',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2026-04-20',
        aliases: ['qwen/qwen3.6-max-preview'],
        context: 262_144,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 130,
            completion_tokens: 780,
            cached_tokens: 13,
        },
    },

    // ── Plus tier ──────────────────────────────────────────────────
    {
        puterId: 'alibaba:qwen/qwen-plus',
        id: 'qwen-plus',
        name: 'Qwen Plus',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2024-01-25',
        aliases: ['qwen/qwen-plus'],
        context: 1_000_000,
        max_tokens: 32_768,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 40,
            completion_tokens: 120,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.5-plus',
        id: 'qwen3.5-plus',
        name: 'Qwen3.5 Plus',
        modalities: { input: ['text', 'image', 'video'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2026-02-16',
        aliases: ['qwen/qwen3.5-plus'],
        context: 1_000_000,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 40,
            completion_tokens: 240,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.6-plus',
        id: 'qwen3.6-plus',
        name: 'Qwen3.6 Plus',
        modalities: { input: ['text', 'image', 'video'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2026-04-02',
        aliases: ['qwen/qwen3.6-plus'],
        context: 1_000_000,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 50,
            completion_tokens: 300,
            cached_tokens: 5,
        },
    },

    // ── Turbo / Flash tier ─────────────────────────────────────────
    {
        puterId: 'alibaba:qwen/qwen-turbo',
        id: 'qwen-turbo',
        name: 'Qwen Turbo',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2024-11-01',
        aliases: ['qwen/qwen-turbo'],
        context: 1_000_000,
        max_tokens: 16_384,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 5,
            completion_tokens: 20,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen-flash',
        id: 'qwen-flash',
        name: 'Qwen Flash',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2025-07-28',
        aliases: ['qwen/qwen-flash'],
        context: 1_000_000,
        max_tokens: 32_768,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 5,
            completion_tokens: 40,
            cached_tokens: 0,
        },
    },

    // ── Coding models ──────────────────────────────────────────────
    {
        puterId: 'alibaba:qwen/qwen3-coder-plus',
        id: 'qwen3-coder-plus',
        name: 'Qwen3 Coder Plus',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2025-07-23',
        aliases: ['qwen/qwen3-coder-plus'],
        context: 1_048_576,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 100,
            completion_tokens: 500,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3-coder-flash',
        id: 'qwen3-coder-flash',
        name: 'Qwen3 Coder Flash',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2025-07-28',
        aliases: ['qwen/qwen3-coder-flash'],
        context: 1_000_000,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 30,
            completion_tokens: 150,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3-coder-480b-a35b-instruct',
        id: 'qwen3-coder-480b-a35b-instruct',
        name: 'Qwen3-Coder 480B-A35B Instruct',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2025-04',
        aliases: ['qwen/qwen3-coder-480b-a35b-instruct'],
        context: 262_144,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 150,
            completion_tokens: 750,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3-coder-30b-a3b-instruct',
        id: 'qwen3-coder-30b-a3b-instruct',
        name: 'Qwen3-Coder 30B-A3B Instruct',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2025-04',
        aliases: ['qwen/qwen3-coder-30b-a3b-instruct'],
        context: 262_144,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 45,
            completion_tokens: 225,
            cached_tokens: 0,
        },
    },

    // ── Reasoning models ───────────────────────────────────────────
    {
        puterId: 'alibaba:qwen/qwq-plus',
        id: 'qwq-plus',
        name: 'QwQ Plus',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2025-03-05',
        aliases: ['qwen/qwq-plus'],
        context: 131_072,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 80,
            completion_tokens: 240,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3-next-80b-a3b-thinking',
        id: 'qwen3-next-80b-a3b-thinking',
        name: 'Qwen3-Next 80B-A3B (Thinking)',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2025-09',
        aliases: ['qwen/qwen3-next-80b-a3b-thinking'],
        context: 131_072,
        max_tokens: 32_768,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 50,
            completion_tokens: 600,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3-next-80b-a3b-instruct',
        id: 'qwen3-next-80b-a3b-instruct',
        name: 'Qwen3-Next 80B-A3B Instruct',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2025-09',
        aliases: ['qwen/qwen3-next-80b-a3b-instruct'],
        context: 131_072,
        max_tokens: 32_768,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 50,
            completion_tokens: 200,
            cached_tokens: 0,
        },
    },

    // ── Open-weight Qwen3 ──────────────────────────────────────────
    {
        puterId: 'alibaba:qwen/qwen3-235b-a22b',
        id: 'qwen3-235b-a22b',
        name: 'Qwen3 235B-A22B',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2025-04',
        aliases: ['qwen/qwen3-235b-a22b'],
        context: 131_072,
        max_tokens: 16_384,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 70,
            completion_tokens: 280,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3-32b',
        id: 'qwen3-32b',
        name: 'Qwen3 32B',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2025-04',
        aliases: ['qwen/qwen3-32b'],
        context: 131_072,
        max_tokens: 16_384,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 70,
            completion_tokens: 280,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3-14b',
        id: 'qwen3-14b',
        name: 'Qwen3 14B',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2025-04',
        aliases: ['qwen/qwen3-14b'],
        context: 131_072,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 35,
            completion_tokens: 140,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3-8b',
        id: 'qwen3-8b',
        name: 'Qwen3 8B',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2025-04',
        aliases: ['qwen/qwen3-8b'],
        context: 131_072,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 18,
            completion_tokens: 70,
            cached_tokens: 0,
        },
    },

    // ── Open-weight Qwen3.5 ────────────────────────────────────────
    {
        puterId: 'alibaba:qwen/qwen3.5-397b-a17b',
        id: 'qwen3.5-397b-a17b',
        name: 'Qwen3.5 397B-A17B',
        modalities: {
            input: ['text', 'image', 'video', 'audio'],
            output: ['text'],
        },
        open_weights: true,
        tool_call: true,
        release_date: '2026-02-15',
        aliases: ['qwen/qwen3.5-397b-a17b'],
        context: 262_144,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 60,
            completion_tokens: 360,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.5-122b-a10b',
        id: 'qwen3.5-122b-a10b',
        name: 'Qwen3.5 122B-A10B',
        modalities: {
            input: ['text', 'image', 'video', 'audio'],
            output: ['text'],
        },
        open_weights: true,
        tool_call: true,
        release_date: '2026-02-23',
        aliases: ['qwen/qwen3.5-122b-a10b'],
        context: 262_144,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 40,
            completion_tokens: 320,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.5-35b-a3b',
        id: 'qwen3.5-35b-a3b',
        name: 'Qwen3.5 35B-A3B',
        modalities: {
            input: ['text', 'image', 'video', 'audio'],
            output: ['text'],
        },
        open_weights: true,
        tool_call: true,
        release_date: '2026-02-23',
        aliases: ['qwen/qwen3.5-35b-a3b'],
        context: 262_144,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 25,
            completion_tokens: 200,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.5-27b',
        id: 'qwen3.5-27b',
        name: 'Qwen3.5 27B',
        modalities: {
            input: ['text', 'image', 'video', 'audio'],
            output: ['text'],
        },
        open_weights: true,
        tool_call: true,
        release_date: '2026-02-23',
        aliases: ['qwen/qwen3.5-27b'],
        context: 262_144,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 30,
            completion_tokens: 240,
            cached_tokens: 0,
        },
    },

    // ── Open-weight Qwen3.6 ────────────────────────────────────────
    {
        puterId: 'alibaba:qwen/qwen3.6-35b-a3b',
        id: 'qwen3.6-35b-a3b',
        name: 'Qwen3.6 35B-A3B',
        modalities: {
            input: ['text', 'image', 'video', 'audio'],
            output: ['text'],
        },
        open_weights: true,
        tool_call: true,
        release_date: '2026-04-17',
        aliases: ['qwen/qwen3.6-35b-a3b'],
        context: 262_144,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 24.8,
            completion_tokens: 148.5,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3.6-27b',
        id: 'qwen3.6-27b',
        name: 'Qwen3.6 27B',
        modalities: {
            input: ['text', 'image', 'video', 'audio'],
            output: ['text'],
        },
        open_weights: true,
        tool_call: true,
        release_date: '2026-04-22',
        aliases: ['qwen/qwen3.6-27b'],
        context: 262_144,
        max_tokens: 65_536,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 60,
            completion_tokens: 360,
            cached_tokens: 0,
        },
    },

    // ── Vision models ──────────────────────────────────────────────
    {
        puterId: 'alibaba:qwen/qwen-vl-max',
        id: 'qwen-vl-max',
        name: 'Qwen-VL Max',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2024-04-08',
        aliases: ['qwen/qwen-vl-max'],
        context: 131_072,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 80,
            completion_tokens: 320,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen-vl-plus',
        id: 'qwen-vl-plus',
        name: 'Qwen-VL Plus',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2024-01-25',
        aliases: ['qwen/qwen-vl-plus'],
        context: 131_072,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 21,
            completion_tokens: 63,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen-vl-ocr',
        id: 'qwen-vl-ocr',
        name: 'Qwen-VL OCR',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: false,
        knowledge: '2024-04',
        release_date: '2024-10-28',
        aliases: ['qwen/qwen-vl-ocr'],
        context: 34_096,
        max_tokens: 4_096,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 72,
            completion_tokens: 72,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3-vl-235b-a22b',
        id: 'qwen3-vl-235b-a22b',
        name: 'Qwen3-VL 235B-A22B',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2025-04',
        aliases: ['qwen/qwen3-vl-235b-a22b'],
        context: 131_072,
        max_tokens: 32_768,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 70,
            completion_tokens: 280,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3-vl-plus',
        id: 'qwen3-vl-plus',
        name: 'Qwen3-VL Plus',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2025-09-23',
        aliases: ['qwen/qwen3-vl-plus'],
        context: 262_144,
        max_tokens: 32_768,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 20,
            completion_tokens: 160,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3-vl-30b-a3b',
        id: 'qwen3-vl-30b-a3b',
        name: 'Qwen3-VL 30B-A3B',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2025-04',
        release_date: '2025-04',
        aliases: ['qwen/qwen3-vl-30b-a3b'],
        context: 131_072,
        max_tokens: 32_768,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 20,
            completion_tokens: 80,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qvq-max',
        id: 'qvq-max',
        name: 'QVQ Max',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2025-03-25',
        aliases: ['qwen/qvq-max'],
        context: 131_072,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 120,
            completion_tokens: 480,
            cached_tokens: 0,
        },
    },

    // ── Legacy Qwen2.5 ────────────────────────────────────────────
    {
        puterId: 'alibaba:qwen/qwen2-5-72b-instruct',
        id: 'qwen2-5-72b-instruct',
        name: 'Qwen2.5 72B Instruct',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2024-09',
        aliases: ['qwen/qwen2-5-72b-instruct'],
        context: 131_072,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 140,
            completion_tokens: 560,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen2-5-32b-instruct',
        id: 'qwen2-5-32b-instruct',
        name: 'Qwen2.5 32B Instruct',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2024-09',
        aliases: ['qwen/qwen2-5-32b-instruct'],
        context: 131_072,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 70,
            completion_tokens: 280,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen2-5-14b-instruct',
        id: 'qwen2-5-14b-instruct',
        name: 'Qwen2.5 14B Instruct',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2024-09',
        aliases: ['qwen/qwen2-5-14b-instruct'],
        context: 131_072,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 35,
            completion_tokens: 140,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen2-5-7b-instruct',
        id: 'qwen2-5-7b-instruct',
        name: 'Qwen2.5 7B Instruct',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2024-09',
        aliases: ['qwen/qwen2-5-7b-instruct'],
        context: 131_072,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 17.5,
            completion_tokens: 70,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen2-5-vl-72b-instruct',
        id: 'qwen2-5-vl-72b-instruct',
        name: 'Qwen2.5-VL 72B Instruct',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2024-09',
        aliases: ['qwen/qwen2-5-vl-72b-instruct'],
        context: 131_072,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 280,
            completion_tokens: 840,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen2-5-vl-7b-instruct',
        id: 'qwen2-5-vl-7b-instruct',
        name: 'Qwen2.5-VL 7B Instruct',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: true,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2024-09',
        aliases: ['qwen/qwen2-5-vl-7b-instruct'],
        context: 131_072,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 35,
            completion_tokens: 105,
            cached_tokens: 0,
        },
    },

    // ── Omni models (text interface, audio costs excluded) ─────────
    {
        puterId: 'alibaba:qwen/qwen-omni-turbo',
        id: 'qwen-omni-turbo',
        name: 'Qwen-Omni Turbo',
        modalities: {
            input: ['text', 'image', 'audio', 'video'],
            output: ['text'],
        },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2025-01-19',
        aliases: ['qwen/qwen-omni-turbo'],
        context: 32_768,
        max_tokens: 2_048,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 7,
            completion_tokens: 27,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen3-omni-flash',
        id: 'qwen3-omni-flash',
        name: 'Qwen3-Omni Flash',
        modalities: {
            input: ['text', 'image', 'audio', 'video'],
            output: ['text'],
        },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2025-09-15',
        aliases: ['qwen/qwen3-omni-flash'],
        context: 65_536,
        max_tokens: 16_384,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 43,
            completion_tokens: 166,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen2-5-omni-7b',
        id: 'qwen2-5-omni-7b',
        name: 'Qwen2.5-Omni 7B',
        modalities: {
            input: ['text', 'image', 'audio', 'video'],
            output: ['text'],
        },
        open_weights: true,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2024-12',
        aliases: ['qwen/qwen2-5-omni-7b'],
        context: 32_768,
        max_tokens: 2_048,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 10,
            completion_tokens: 40,
            cached_tokens: 0,
        },
    },

    // ── Translation models ─────────────────────────────────────────
    {
        puterId: 'alibaba:qwen/qwen-mt-plus',
        id: 'qwen-mt-plus',
        name: 'Qwen-MT Plus',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: false,
        knowledge: '2024-04',
        release_date: '2025-01',
        aliases: ['qwen/qwen-mt-plus'],
        context: 16_384,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 246,
            completion_tokens: 737,
            cached_tokens: 0,
        },
    },
    {
        puterId: 'alibaba:qwen/qwen-mt-turbo',
        id: 'qwen-mt-turbo',
        name: 'Qwen-MT Turbo',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: false,
        knowledge: '2024-04',
        release_date: '2025-01',
        aliases: ['qwen/qwen-mt-turbo'],
        context: 16_384,
        max_tokens: 8_192,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 16,
            completion_tokens: 49,
            cached_tokens: 0,
        },
    },
];
