/*
 * Copyright (C) 2024  Puter Technologies Inc.
 *
 * This file is part of Phoenix Shell.
 *
 * Phoenix Shell is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
// Generated by /tools/gen.js
import module_add from './add.js'
import module_branch from './branch.js'
import module_clone from './clone.js'
import module_commit from './commit.js'
import module_config from './config.js'
import module_fetch from './fetch.js'
import module_help from './help.js'
import module_init from './init.js'
import module_log from './log.js'
import module_remote from './remote.js'
import module_show from './show.js'
import module_status from './status.js'
import module_version from './version.js'

export default {
    "add": module_add,
    "branch": module_branch,
    "clone": module_clone,
    "commit": module_commit,
    "config": module_config,
    "fetch": module_fetch,
    "help": module_help,
    "init": module_init,
    "log": module_log,
    "remote": module_remote,
    "show": module_show,
    "status": module_status,
    "version": module_version,
};
