site_name: Puter v2.5.1 documentation

theme:
  name: material
  palette:
    primary: indigo
    accent: pink
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
    scheme: default

nav:
  - Home: index.md
  - General System Architecture: arch.md
  - Glosary: glosary.md
  - Contribution Guidelines: oscon.md
  - Technological Stack: stack.md
  - Support: support.md
  - Colaborate with this doc: this.md
  - What next: roadmap.md
  - Guides: dev_guides/dev_guides.md
