import { IChatModel } from '../types';

// Hardcoded from https://models.dev/api.json
export const GEMINI_MODELS: IChatModel[] = [
    {
        puterId: 'google:google/gemini-2.0-flash',
        id: 'gemini-2.0-flash',
        modalities: { 'input': ['text', 'image', 'audio', 'video', 'pdf'], 'output': ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-06',
        release_date: '2024-12-11',
        name: 'Gemini 2.0 Flash',
        aliases: ['google/gemini-2.0-flash'],
        context: 131072,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 10,
            completion_tokens: 40,
            cached_tokens: 3,

        },
        max_tokens: 8192,
    },
    {
        puterId: 'google:google/gemini-2.0-flash-lite',
        id: 'gemini-2.0-flash-lite',
        modalities: { 'input': ['text', 'image', 'audio', 'video', 'pdf'], 'output': ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-06',
        release_date: '2024-12-11',
        name: 'Gemini 2.0 Flash-Lite',
        aliases: ['google/gemini-2.0-flash-lite'],
        context: 1_048_576,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 8,
            completion_tokens: 30,
        },
        max_tokens: 8192,
    },
    {
        puterId: 'google:google/gemini-2.5-flash',
        id: 'gemini-2.5-flash',
        modalities: { 'input': ['text', 'image', 'audio', 'video', 'pdf'], 'output': ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-01',
        release_date: '2025-03-20',
        name: 'Gemini 2.5 Flash',
        aliases: ['google/gemini-2.5-flash'],
        context: 1_048_576,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 30,
            completion_tokens: 250,
            cached_tokens: 3,
        },
        max_tokens: 65536,
    },
    {
        puterId: 'google:google/gemini-2.5-flash-lite',
        id: 'gemini-2.5-flash-lite',
        modalities: { 'input': ['text', 'image', 'audio', 'video', 'pdf'], 'output': ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-01',
        release_date: '2025-06-17',
        name: 'Gemini 2.5 Flash-Lite',
        aliases: ['google/gemini-2.5-flash-lite'],
        context: 1_048_576,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 10,
            completion_tokens: 40,
            cached_tokens: 1,
        },
        max_tokens: 65536,
    },
    {
        puterId: 'google:google/gemini-2.5-pro',
        id: 'gemini-2.5-pro',
        modalities: { 'input': ['text', 'image', 'audio', 'video', 'pdf'], 'output': ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-01',
        release_date: '2025-03-20',
        name: 'Gemini 2.5 Pro',
        aliases: ['google/gemini-2.5-pro'],
        context: 1_048_576,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 125,
            completion_tokens: 1000,
            cached_tokens: 13,
        },
        max_tokens: 200_000,
    },
    {
        puterId: 'google:google/gemini-3-pro-preview',
        id: 'gemini-3-pro-preview',
        modalities: { 'input': ['text', 'image', 'video', 'audio', 'pdf'], 'output': ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-01',
        release_date: '2025-11-18',
        name: 'Gemini 3 Pro',
        aliases: ['google/gemini-3-pro-preview'],
        context: 1_048_576,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 200,
            completion_tokens: 1200,
            cached_tokens: 20,
        },
        max_tokens: 200_000,
    },
    {
        puterId: 'google:google/gemini-3-flash-preview',
        id: 'gemini-3-flash-preview',
        modalities: { 'input': ['text', 'image', 'video', 'audio', 'pdf'], 'output': ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-01',
        release_date: '2025-12-17',
        name: 'Gemini 3 Flash',
        aliases: ['google/gemini-3-flash-preview'],
        context: 1_048_576,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 50,
            completion_tokens: 300,
            cached_tokens: 5,
        },
        max_tokens: 65536,
    },
];
