-- Copyright (C) 2024-present Puter Technologies Inc.
--
-- This file is part of Puter.
--
-- Puter is free software: you can redistribute it and/or modify
-- it under the terms of the GNU Affero General Public License as published
-- by the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU Affero General Public License for more details.
--
-- You should have received a copy of the GNU Affero General Public License
-- along with this program.  If not, see <https://www.gnu.org/licenses/>.

CREATE TABLE IF NOT EXISTS "user" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid varchar(36) NOT NULL UNIQUE,
  username varchar(50) UNIQUE,
  email varchar(256),
  password varchar(225),
  free_storage bigint,
  max_subdomains integer,
  taskbar_items text,
  desktop_uuid varchar(36),
  appdata_uuid varchar(36),
  documents_uuid varchar(36),
  pictures_uuid varchar(36),
  videos_uuid varchar(36),
  trash_uuid varchar(36),
  trash_id integer,
  appdata_id integer,
  desktop_id integer,
  documents_id integer,
  pictures_id integer,
  videos_id integer,
  referrer varchar(64),
  desktop_bg_url text,
  desktop_bg_color varchar(20),
  desktop_bg_fit varchar(16),
  pass_recovery_token varchar(36),
  requires_email_confirmation boolean NOT NULL DEFAULT FALSE,
  email_confirm_code varchar(8),
  email_confirm_token varchar(36),
  email_confirmed boolean NOT NULL DEFAULT FALSE,
  dev_first_name varchar(100),
  dev_last_name varchar(100),
  dev_paypal varchar(100),
  dev_approved_for_incentive_program boolean DEFAULT FALSE,
  dev_joined_incentive_program boolean DEFAULT FALSE,
  suspended boolean,
  unsubscribed boolean NOT NULL DEFAULT FALSE,
  "timestamp" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_activity_ts timestamp,
  referral_code varchar(16) UNIQUE,
  referred_by integer REFERENCES "user" (id) ON DELETE SET NULL ON UPDATE CASCADE,
  unconfirmed_change_email varchar(256),
  change_email_confirm_token varchar(256),
  otp_secret text,
  otp_enabled boolean DEFAULT FALSE,
  otp_recovery_codes text,
  stripe_customer_id varchar(40),
  public_uuid varchar(36),
  public_id integer,
  clean_email varchar(256),
  audit_metadata jsonb,
  signup_ip varchar(45),
  signup_ip_forwarded varchar(45),
  signup_user_agent varchar(512),
  signup_origin varchar(255),
  signup_server varchar(255),
  metadata jsonb DEFAULT '{}'::jsonb,
  reputation smallint DEFAULT 100
);

CREATE INDEX IF NOT EXISTS idx_user_email ON "user" (email);
CREATE INDEX IF NOT EXISTS idx_user_pass_recovery_token ON "user" (pass_recovery_token);
CREATE INDEX IF NOT EXISTS idx_user_referrer ON "user" (referrer);
CREATE INDEX IF NOT EXISTS idx_user_email_confirm_token ON "user" (email_confirm_token);
CREATE INDEX IF NOT EXISTS idx_user_last_activity_ts ON "user" (last_activity_ts);
CREATE INDEX IF NOT EXISTS idx_user_referred_by ON "user" (referred_by);
CREATE INDEX IF NOT EXISTS idx_user_stripe_customer_id ON "user" (stripe_customer_id);
CREATE INDEX IF NOT EXISTS idx_user_clean_email ON "user" (clean_email);
CREATE INDEX IF NOT EXISTS idx_user_signup_ip ON "user" (signup_ip);
CREATE INDEX IF NOT EXISTS idx_user_signup_ip_forwarded ON "user" (signup_ip_forwarded);
CREATE INDEX IF NOT EXISTS idx_user_signup_user_agent ON "user" (signup_user_agent);
CREATE INDEX IF NOT EXISTS idx_user_signup_origin ON "user" (signup_origin);
CREATE INDEX IF NOT EXISTS idx_user_signup_server ON "user" (signup_server);

CREATE TABLE IF NOT EXISTS apps (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid varchar(40) NOT NULL UNIQUE,
  owner_user_id integer REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  icon text,
  name varchar(100) NOT NULL UNIQUE,
  title varchar(100) NOT NULL,
  description text,
  godmode boolean DEFAULT FALSE,
  maximize_on_start boolean DEFAULT FALSE,
  index_url text NOT NULL,
  approved_for_listing boolean DEFAULT FALSE,
  approved_for_opening_items boolean DEFAULT FALSE,
  approved_for_incentive_program boolean DEFAULT FALSE,
  "timestamp" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_review timestamp,
  tags varchar(255),
  app_owner integer REFERENCES apps (id) ON DELETE SET NULL ON UPDATE CASCADE,
  background boolean DEFAULT FALSE,
  metadata jsonb,
  protected boolean DEFAULT FALSE,
  is_private boolean DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_apps_owner_user_id ON apps (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_apps_app_owner ON apps (app_owner);
CREATE INDEX IF NOT EXISTS idx_apps_owner_timestamp ON apps (owner_user_id, "timestamp" DESC);
CREATE INDEX IF NOT EXISTS idx_apps_listing_timestamp ON apps (approved_for_listing, "timestamp" DESC);

CREATE TABLE IF NOT EXISTS "group" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid varchar(40) UNIQUE,
  owner_user_id integer REFERENCES "user" (id) ON DELETE SET NULL ON UPDATE CASCADE,
  extra jsonb,
  metadata jsonb,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_group_owner_user_id ON "group" (owner_user_id);

CREATE TABLE IF NOT EXISTS app_filetype_association (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app_id integer NOT NULL REFERENCES apps (id) ON DELETE CASCADE ON UPDATE CASCADE,
  type varchar(60) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_app_filetype_association_app_id ON app_filetype_association (app_id);
CREATE INDEX IF NOT EXISTS idx_app_filetype_association_type ON app_filetype_association (type);

CREATE TABLE IF NOT EXISTS app_opens (
  _id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app_uid varchar(40) NOT NULL REFERENCES apps (uid) ON DELETE CASCADE ON UPDATE CASCADE,
  user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  ts integer NOT NULL,
  human_ts timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_app_opens_user_id ON app_opens (user_id);
CREATE INDEX IF NOT EXISTS idx_app_opens_app_uid ON app_opens (app_uid);
CREATE INDEX IF NOT EXISTS idx_app_opens_uid_ts ON app_opens (app_uid, ts);
CREATE INDEX IF NOT EXISTS idx_app_opens_app_user ON app_opens (app_uid, user_id);

CREATE TABLE IF NOT EXISTS fsentries (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid varchar(36) NOT NULL UNIQUE,
  bucket varchar(50),
  bucket_region varchar(30),
  public_token varchar(36) UNIQUE,
  file_request_token varchar(36) UNIQUE,
  is_shortcut boolean DEFAULT FALSE,
  shortcut_to integer REFERENCES fsentries (id) ON DELETE SET NULL ON UPDATE CASCADE,
  user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  parent_id integer REFERENCES fsentries (id) ON DELETE CASCADE ON UPDATE CASCADE,
  associated_app_id integer REFERENCES apps (id) ON DELETE SET NULL ON UPDATE CASCADE,
  is_dir boolean DEFAULT FALSE,
  layout varchar(30),
  sort_by varchar(20),
  sort_order varchar(10),
  is_public boolean,
  thumbnail text,
  immutable boolean NOT NULL DEFAULT FALSE,
  name varchar(767) NOT NULL,
  metadata text,
  modified integer NOT NULL,
  created integer,
  accessed integer,
  size bigint,
  symlink_path varchar(260),
  is_symlink boolean DEFAULT FALSE,
  parent_uid varchar(36),
  path varchar(4096),
  CONSTRAINT fsentries_parent_name_unique UNIQUE (parent_id, name)
);

CREATE INDEX IF NOT EXISTS idx_fsentries_name ON fsentries (name);
CREATE INDEX IF NOT EXISTS idx_fsentries_modified ON fsentries (modified);
CREATE INDEX IF NOT EXISTS idx_fsentries_parent_id ON fsentries (parent_id);
CREATE INDEX IF NOT EXISTS idx_fsentries_is_dir ON fsentries (is_dir);
CREATE INDEX IF NOT EXISTS idx_fsentries_user_id ON fsentries (user_id);
CREATE INDEX IF NOT EXISTS idx_fsentries_shortcut_to ON fsentries (shortcut_to);
CREATE INDEX IF NOT EXISTS idx_fsentries_associated_app_id ON fsentries (associated_app_id);
CREATE INDEX IF NOT EXISTS idx_fsentries_bucket ON fsentries (bucket);
CREATE INDEX IF NOT EXISTS idx_fsentries_bucket_region ON fsentries (bucket_region);
CREATE INDEX IF NOT EXISTS idx_fsentries_parent_uid ON fsentries (parent_uid);
CREATE INDEX IF NOT EXISTS idx_fsentries_path ON fsentries (path);
CREATE INDEX IF NOT EXISTS idx_fsentries_accessed ON fsentries (accessed);
CREATE INDEX IF NOT EXISTS idx_fsentries_user_parent_name ON fsentries (user_id, parent_uid, name);
CREATE INDEX IF NOT EXISTS idx_fsentries_parent_uid_name ON fsentries (parent_uid, name);

CREATE TABLE IF NOT EXISTS fsentry_versions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fsentry_id integer NOT NULL REFERENCES fsentries (id) ON DELETE CASCADE ON UPDATE CASCADE,
  fsentry_uuid varchar(36) NOT NULL,
  version_id varchar(60) NOT NULL,
  user_id integer REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  message text,
  ts_epoch integer
);

CREATE INDEX IF NOT EXISTS idx_fsentry_versions_fsentry_id ON fsentry_versions (fsentry_id);
CREATE INDEX IF NOT EXISTS idx_fsentry_versions_fsentry_uuid ON fsentry_versions (fsentry_uuid);
CREATE INDEX IF NOT EXISTS idx_fsentry_versions_user_id ON fsentry_versions (user_id);

CREATE TABLE IF NOT EXISTS subdomains (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid varchar(40) UNIQUE,
  subdomain varchar(64) NOT NULL UNIQUE,
  user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  root_dir_id integer REFERENCES fsentries (id) ON DELETE SET NULL ON UPDATE CASCADE,
  associated_app_id integer REFERENCES apps (id) ON DELETE CASCADE ON UPDATE CASCADE,
  ts timestamp DEFAULT CURRENT_TIMESTAMP,
  app_owner integer REFERENCES apps (id) ON DELETE SET NULL ON UPDATE CASCADE,
  protected boolean DEFAULT FALSE,
  domain varchar(265),
  database_id varchar(40),
  preamble_version varchar(64)
);

CREATE INDEX IF NOT EXISTS idx_subdomains_user_id ON subdomains (user_id);
CREATE INDEX IF NOT EXISTS idx_subdomains_root_dir_id ON subdomains (root_dir_id);
CREATE INDEX IF NOT EXISTS idx_subdomains_associated_app_id ON subdomains (associated_app_id);
CREATE INDEX IF NOT EXISTS idx_subdomains_app_owner ON subdomains (app_owner);
CREATE INDEX IF NOT EXISTS idx_subdomains_domain ON subdomains (domain);
CREATE INDEX IF NOT EXISTS idx_subdomains_root_user ON subdomains (root_dir_id, user_id);
CREATE INDEX IF NOT EXISTS idx_subdomains_app_user ON subdomains (associated_app_id, user_id);

CREATE TABLE IF NOT EXISTS kv (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app varchar(40),
  user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  kkey_hash bigint NOT NULL,
  kkey text NOT NULL,
  value text,
  migrated boolean DEFAULT FALSE,
  "expireAt" timestamp,
  CONSTRAINT kv_app_user_kkey_hash_unique UNIQUE (app, user_id, kkey_hash)
);

CREATE INDEX IF NOT EXISTS idx_kv_app ON kv (app);
CREATE INDEX IF NOT EXISTS idx_kv_user_id ON kv (user_id);
CREATE INDEX IF NOT EXISTS idx_kv_kkey_hash ON kv (kkey_hash);

CREATE TABLE IF NOT EXISTS sessions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  uuid varchar(40) NOT NULL,
  meta jsonb,
  created_at bigint DEFAULT 0,
  last_activity bigint DEFAULT 0,
  kind varchar(32) NOT NULL DEFAULT 'web'
    CHECK (kind IN ('web', 'app', 'access_token', 'asset', 'worker')),
  label varchar(255),
  parent_session_id varchar(64),
  last_ip varchar(64),
  last_user_agent varchar(512),
  revoked_at bigint,
  expires_at bigint,
  app_uid varchar(64),
  legacy_token_uid varchar(64),
  created_via varchar(32),
  auth_id varchar(64),
  access_token_uid varchar(64)
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_uuid ON sessions (uuid);
CREATE INDEX IF NOT EXISTS idx_sessions_user_revoked ON sessions (user_id, revoked_at);
CREATE INDEX IF NOT EXISTS idx_sessions_parent ON sessions (parent_session_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_user_app_active
  ON sessions (user_id, app_uid)
  WHERE kind = 'app' AND revoked_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_legacy_token_active
  ON sessions (legacy_token_uid)
  WHERE legacy_token_uid IS NOT NULL AND revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_sessions_kind_user ON sessions (kind, user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_access_token_uid
  ON sessions (access_token_uid)
  WHERE access_token_uid IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_user_worker_active
  ON sessions (user_id, COALESCE(app_uid, ''), (meta #>> ARRAY['worker_name']))
  WHERE kind = 'worker' AND revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS user_to_app_permissions (
  user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  app_id integer NOT NULL REFERENCES apps (id) ON DELETE CASCADE ON UPDATE CASCADE,
  permission varchar(255) NOT NULL,
  extra jsonb,
  dt timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, app_id, permission)
);

CREATE INDEX IF NOT EXISTS idx_utap_user_permission ON user_to_app_permissions (user_id, permission);
CREATE INDEX IF NOT EXISTS idx_utap_app_permission ON user_to_app_permissions (app_id, permission);

CREATE TABLE IF NOT EXISTS user_to_group_permissions (
  user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  group_id integer NOT NULL REFERENCES "group" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  permission varchar(255) NOT NULL,
  extra jsonb,
  PRIMARY KEY (user_id, group_id, permission)
);

CREATE INDEX IF NOT EXISTS idx_user_to_group_permissions_group_id ON user_to_group_permissions (group_id);

CREATE TABLE IF NOT EXISTS user_to_user_permissions (
  issuer_user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  holder_user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  permission varchar(255) NOT NULL,
  extra jsonb,
  PRIMARY KEY (issuer_user_id, holder_user_id, permission)
);

CREATE INDEX IF NOT EXISTS idx_user_to_user_permissions_holder_user_id ON user_to_user_permissions (holder_user_id);

CREATE TABLE IF NOT EXISTS dev_to_app_permissions (
  user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  app_id integer NOT NULL REFERENCES apps (id) ON DELETE CASCADE ON UPDATE CASCADE,
  permission varchar(255) NOT NULL,
  extra jsonb,
  PRIMARY KEY (user_id, app_id, permission)
);

CREATE INDEX IF NOT EXISTS idx_dev_to_app_permissions_app_id ON dev_to_app_permissions (app_id);
CREATE INDEX IF NOT EXISTS idx_dev_to_app_permissions_permission ON dev_to_app_permissions (permission);

CREATE TABLE IF NOT EXISTS access_token_permissions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_uid varchar(40) NOT NULL,
  authorizer_user_id integer REFERENCES "user" (id) ON DELETE SET NULL ON UPDATE CASCADE,
  authorizer_app_id integer REFERENCES apps (id) ON DELETE SET NULL ON UPDATE CASCADE,
  permission varchar(255) NOT NULL,
  extra jsonb,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_access_token_permissions_token_uid ON access_token_permissions (token_uid);

CREATE TABLE IF NOT EXISTS old_app_names (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app_uid varchar(40) NOT NULL REFERENCES apps (uid) ON DELETE CASCADE,
  name varchar(255) NOT NULL,
  "timestamp" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_old_app_names_app_uid_name UNIQUE (app_uid, name)
);

CREATE INDEX IF NOT EXISTS idx_old_app_names_app_uid ON old_app_names (app_uid);
CREATE INDEX IF NOT EXISTS idx_old_app_names_name ON old_app_names (name);

CREATE TABLE IF NOT EXISTS jct_user_group (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  group_id integer NOT NULL REFERENCES "group" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  extra jsonb,
  metadata jsonb,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_jct_user_group_user_id ON jct_user_group (user_id);
CREATE INDEX IF NOT EXISTS idx_jct_user_group_group_id ON jct_user_group (group_id);

CREATE TABLE IF NOT EXISTS notification (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  uid varchar(40) UNIQUE,
  value jsonb NOT NULL,
  acknowledged bigint,
  shown bigint,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notification_user_id ON notification (user_id);

CREATE TABLE IF NOT EXISTS share (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid varchar(40) UNIQUE,
  issuer_user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  recipient_email varchar(255) NOT NULL,
  data jsonb,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_share_issuer_user_id ON share (issuer_user_id);
CREATE INDEX IF NOT EXISTS idx_share_recipient_email ON share (recipient_email);

CREATE TABLE IF NOT EXISTS feedback (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  message text,
  ts timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_feedback_user_id ON feedback (user_id);

CREATE TABLE IF NOT EXISTS thread (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid varchar(40) NOT NULL UNIQUE,
  parent_uid varchar(40) REFERENCES thread (uid) ON DELETE CASCADE ON UPDATE CASCADE,
  owner_user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  "schema" text,
  text text NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_thread_parent_uid ON thread (parent_uid);
CREATE INDEX IF NOT EXISTS idx_thread_owner_user_id ON thread (owner_user_id);

CREATE TABLE IF NOT EXISTS user_comments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid varchar(40) NOT NULL UNIQUE,
  user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  metadata jsonb,
  text text NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_comments_user_id ON user_comments (user_id);
CREATE INDEX IF NOT EXISTS idx_user_comments_uid ON user_comments (uid);

CREATE TABLE IF NOT EXISTS user_fsentry_comments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_comment_id integer NOT NULL REFERENCES user_comments (id) ON DELETE CASCADE ON UPDATE CASCADE,
  fsentry_id integer NOT NULL REFERENCES fsentries (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_fsentry_comments_user_comment_id ON user_fsentry_comments (user_comment_id);
CREATE INDEX IF NOT EXISTS idx_user_fsentry_comments_fsentry_id ON user_fsentry_comments (fsentry_id);

CREATE TABLE IF NOT EXISTS user_fsentry_version_comments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_comment_id integer NOT NULL REFERENCES user_comments (id) ON DELETE CASCADE ON UPDATE CASCADE,
  fsentry_version_id integer NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_user_fsentry_version_comments_user_comment_id ON user_fsentry_version_comments (user_comment_id);
CREATE INDEX IF NOT EXISTS idx_user_fsentry_version_comments_version_id ON user_fsentry_version_comments (fsentry_version_id);

CREATE TABLE IF NOT EXISTS user_group_comments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_comment_id integer NOT NULL REFERENCES user_comments (id) ON DELETE CASCADE ON UPDATE CASCADE,
  group_id integer NOT NULL REFERENCES "group" (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_group_comments_user_comment_id ON user_group_comments (user_comment_id);
CREATE INDEX IF NOT EXISTS idx_user_group_comments_group_id ON user_group_comments (group_id);

CREATE TABLE IF NOT EXISTS user_user_comments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_comment_id integer NOT NULL REFERENCES user_comments (id) ON DELETE CASCADE ON UPDATE CASCADE,
  commented_user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_user_comments_user_comment_id ON user_user_comments (user_comment_id);
CREATE INDEX IF NOT EXISTS idx_user_user_comments_commented_user_id ON user_user_comments (commented_user_id);

CREATE TABLE IF NOT EXISTS user_oidc_providers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  provider varchar(64) NOT NULL,
  provider_sub varchar(255) NOT NULL,
  refresh_token text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_oidc_providers_user_id ON user_oidc_providers (user_id);
CREATE INDEX IF NOT EXISTS idx_user_oidc_providers_provider ON user_oidc_providers (provider);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_oidc_providers_provider_sub_unique ON user_oidc_providers (provider, provider_sub);

CREATE TABLE IF NOT EXISTS app_update_audit (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app_id integer REFERENCES apps (id) ON DELETE SET NULL ON UPDATE CASCADE,
  app_id_keep integer NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  old_name varchar(50),
  new_name varchar(50),
  reason varchar(255)
);

CREATE INDEX IF NOT EXISTS idx_app_update_audit_app_id ON app_update_audit (app_id);

CREATE TABLE IF NOT EXISTS user_update_audit (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES "user" (id) ON DELETE SET NULL ON UPDATE CASCADE,
  user_id_keep integer NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  old_email varchar(256),
  new_email varchar(256),
  old_username varchar(50),
  new_username varchar(50),
  reason varchar(255)
);

CREATE INDEX IF NOT EXISTS idx_user_update_audit_user_id ON user_update_audit (user_id);

CREATE TABLE IF NOT EXISTS storage_audit (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES "user" (id) ON DELETE SET NULL ON UPDATE CASCADE,
  user_id_keep integer NOT NULL,
  is_subtract boolean NOT NULL DEFAULT FALSE,
  amount bigint NOT NULL,
  field_a varchar(16),
  field_b varchar(16),
  reason varchar(255),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_storage_audit_user_id ON storage_audit (user_id);

CREATE TABLE IF NOT EXISTS audit_user_to_app_permissions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES "user" (id) ON DELETE SET NULL ON UPDATE CASCADE,
  user_id_keep integer NOT NULL,
  app_id integer REFERENCES apps (id) ON DELETE SET NULL ON UPDATE CASCADE,
  app_id_keep integer NOT NULL,
  permission varchar(255) NOT NULL,
  extra jsonb,
  action varchar(16),
  reason varchar(255),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_user_to_app_permissions_user_id ON audit_user_to_app_permissions (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_user_to_app_permissions_app_id ON audit_user_to_app_permissions (app_id);

CREATE TABLE IF NOT EXISTS audit_dev_to_app_permissions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES "user" (id) ON DELETE SET NULL ON UPDATE CASCADE,
  user_id_keep integer NOT NULL,
  app_id integer REFERENCES apps (id) ON DELETE SET NULL ON UPDATE CASCADE,
  app_id_keep integer NOT NULL,
  permission varchar(255) NOT NULL,
  extra jsonb,
  action varchar(16),
  reason varchar(255),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_dev_to_app_permissions_user_id ON audit_dev_to_app_permissions (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_dev_to_app_permissions_app_id ON audit_dev_to_app_permissions (app_id);

CREATE TABLE IF NOT EXISTS audit_user_to_group_permissions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES "user" (id) ON DELETE SET NULL ON UPDATE CASCADE,
  user_id_keep integer NOT NULL,
  group_id integer REFERENCES "group" (id) ON DELETE SET NULL ON UPDATE CASCADE,
  group_id_keep integer NOT NULL,
  permission varchar(255) NOT NULL,
  extra jsonb,
  action varchar(255),
  reason varchar(255),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_user_to_group_permissions_user_id ON audit_user_to_group_permissions (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_user_to_group_permissions_group_id ON audit_user_to_group_permissions (group_id);

CREATE TABLE IF NOT EXISTS audit_user_to_user_permissions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issuer_user_id integer REFERENCES "user" (id) ON DELETE SET NULL ON UPDATE CASCADE,
  issuer_user_id_keep integer NOT NULL,
  holder_user_id integer REFERENCES "user" (id) ON DELETE SET NULL ON UPDATE CASCADE,
  holder_user_id_keep integer NOT NULL,
  permission varchar(255) NOT NULL,
  extra jsonb,
  action varchar(16),
  reason varchar(255),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_user_to_user_permissions_issuer_user_id ON audit_user_to_user_permissions (issuer_user_id);
CREATE INDEX IF NOT EXISTS idx_audit_user_to_user_permissions_holder_user_id ON audit_user_to_user_permissions (holder_user_id);

CREATE TABLE IF NOT EXISTS ai_usage (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  app_id integer REFERENCES apps (id) ON DELETE SET NULL ON UPDATE CASCADE,
  service_name varchar(64),
  model_name varchar(128),
  price_modifier varchar(40),
  cost integer,
  value_uint_1 integer,
  value_uint_2 integer,
  value_uint_3 integer,
  value_uint_4 integer,
  value_uint_5 integer,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ai_usage_app_id ON ai_usage (app_id);
CREATE INDEX IF NOT EXISTS idx_ai_usage_service_name ON ai_usage (service_name);
CREATE INDEX IF NOT EXISTS idx_ai_usage_model_name ON ai_usage (model_name);
CREATE INDEX IF NOT EXISTS idx_ai_usage_price_modifier ON ai_usage (price_modifier);
CREATE INDEX IF NOT EXISTS idx_ai_usage_created_at ON ai_usage (created_at);
CREATE INDEX IF NOT EXISTS idx_ai_usage_user_timestamp ON ai_usage (user_id, created_at);

CREATE TABLE IF NOT EXISTS general_analytics (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  uid varchar(40) NOT NULL,
  trace_id varchar(40),
  user_id integer REFERENCES "user" (id) ON DELETE SET NULL ON UPDATE CASCADE,
  user_id_keep integer,
  app_id integer REFERENCES apps (id) ON DELETE SET NULL ON UPDATE CASCADE,
  app_id_keep integer,
  server_id varchar(40),
  actor_type varchar(40),
  tags jsonb,
  fields jsonb
);

CREATE INDEX IF NOT EXISTS idx_general_analytics_user_id ON general_analytics (user_id);
CREATE INDEX IF NOT EXISTS idx_general_analytics_app_id ON general_analytics (app_id);

CREATE TABLE IF NOT EXISTS monthly_usage_counts (
  year integer NOT NULL,
  month integer NOT NULL,
  service_type varchar(40) NOT NULL,
  service_name varchar(40) NOT NULL,
  actor_key varchar(255) NOT NULL,
  pricing_category jsonb NOT NULL,
  pricing_category_hash bytea NOT NULL,
  "count" integer DEFAULT 0,
  value_uint_1 integer,
  value_uint_2 integer,
  value_uint_3 integer,
  PRIMARY KEY (year, month, service_type, service_name, actor_key, pricing_category_hash)
);

CREATE TABLE IF NOT EXISTS service_usage_monthly (
  "key" varchar(255) NOT NULL,
  year integer NOT NULL,
  month integer NOT NULL,
  user_id integer REFERENCES "user" (id) ON DELETE SET NULL ON UPDATE CASCADE,
  app_id integer REFERENCES apps (id) ON DELETE SET NULL ON UPDATE CASCADE,
  "count" integer NOT NULL,
  extra jsonb,
  PRIMARY KEY ("key", year, month)
);

CREATE INDEX IF NOT EXISTS idx_service_usage_monthly_user_id ON service_usage_monthly (user_id);
CREATE INDEX IF NOT EXISTS idx_service_usage_monthly_app_id ON service_usage_monthly (app_id);

CREATE TABLE IF NOT EXISTS per_user_credit (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL UNIQUE REFERENCES "user" (id) ON DELETE CASCADE ON UPDATE CASCADE,
  amount bigint NOT NULL,
  last_updated_at bigint NOT NULL
);

INSERT INTO "user" (id, uuid, username, metadata)
VALUES (1, '5d4adce0-a381-4982-9c02-6e2540026238', 'system', '{}'::jsonb)
ON CONFLICT (uuid) DO UPDATE SET username = EXCLUDED.username;

SELECT setval(pg_get_serial_sequence('"user"', 'id'), COALESCE((SELECT MAX(id) FROM "user"), 1), true);

INSERT INTO "group" (uid, owner_user_id, extra, metadata)
VALUES
  ('26bfb1fb-421f-45bc-9aa4-d81ea569e7a5', 1, '{"critical": true, "type": "default", "name": "system"}'::jsonb, '{"title": "System", "color": "#000000"}'::jsonb),
  ('ca342a5e-b13d-4dee-9048-58b11a57cc55', 1, '{"critical": true, "type": "default", "name": "admin"}'::jsonb, '{"title": "Admin", "color": "#a83232"}'::jsonb),
  ('78b1b1dd-c959-44d2-b02c-8735671f9997', 1, '{"critical": true, "type": "default", "name": "user"}'::jsonb, '{"title": "User", "color": "#3254a8"}'::jsonb),
  ('b7220104-7905-4985-b996-649fdcdb3c8f', 1, '{"critical": true, "type": "default", "name": "temp"}'::jsonb, '{"title": "Temp", "color": "#888888"}'::jsonb),
  ('3c2dfff7-d22a-41aa-a193-59a61dac4b64', 1, '{"type": "default", "name": "moderator"}'::jsonb, '{"title": "Moderator", "color": "#a432a8"}'::jsonb),
  ('5e8f251d-3382-4b0d-932c-7bb82f48652f', 1, '{"type": "default", "name": "developer"}'::jsonb, '{"title": "Developer", "color": "#32a852"}'::jsonb)
ON CONFLICT (uid) DO UPDATE SET
  owner_user_id = EXCLUDED.owner_user_id,
  extra = EXCLUDED.extra,
  metadata = EXCLUDED.metadata;

INSERT INTO apps (
  uid, owner_user_id, icon, name, title, description, index_url,
  godmode, maximize_on_start, background,
  approved_for_listing, approved_for_opening_items,
  approved_for_incentive_program, tags, "timestamp"
)
VALUES
  ('app-3920851d-bda8-479b-9407-8517293c7d44', 1, NULL, 'pdf', 'PDF', '', 'https://pdf.puter.com', FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 'productivity', '2020-01-01 00:00:00'),
  ('app-5584fbf7-ed69-41fc-99cd-85da21b1ef51', 1, NULL, 'camera', 'Camera', 'Camera in the browser.', 'https://online-camera.com', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, NULL, '2020-01-01 00:00:00'),
  ('app-11edfba2-1ed3-4e22-8573-47e88fb87d70', 1, NULL, 'player', 'Player', 'A free video player app in the browser.', 'https://simple-player.puter.com', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, NULL, '2020-01-01 00:00:00'),
  ('app-7bdca1a4-6373-4c98-ad97-03ff2d608ca1', 1, NULL, 'recorder', 'Recorder', 'Online voice recorder in the browser with cloud storage.', 'https://voice-recorder.com', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, NULL, '2020-01-01 00:00:00'),
  ('app-d7e9471f-e441-4d72-a5ab-75e96573b76b', 1, NULL, 'music-player', 'Music Player', 'A free music player app in the browser.', 'https://player.puter.com', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, NULL, '2026-05-10 00:00:00'),
  ('app-e3ac5486-da8c-42ad-8377-8728086e0980', 1, NULL, 'git', 'Git', 'Puter Git client', 'https://builtins.namespaces.puter.com/git', FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, 'productivity', '2020-01-01 00:00:00'),
  ('app-0b37f054-07d4-4627-8765-11bd23e889d4', 1, NULL, 'dev-center', 'Dev Center', 'This is the app that makes apps', 'https://builtins.namespaces.puter.com/dev-center', TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, NULL, '2020-01-01 00:00:00'),
  ('app-fbbdb72b-ad08-4cb4-86a1-de0f27cf2e1e', 1, NULL, 'puter-linux', 'Puter Linux', 'Linux emulator for Puter', 'https://builtins.namespaces.puter.com/emulator', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, NULL, '2020-01-01 00:00:00'),
  ('app-838dfbc4-bf8b-48c2-b47b-c4adc77fab58', 1, NULL, 'editor', 'Editor', 'Text editor', 'https://online-notepad.com', TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, 'productivity', '2020-01-01 00:00:00'),
  ('app-58282b08-990a-4906-95f7-fa37ff92452b', 1, NULL, 'draw', 'Draw', 'Image editor', 'https://draw.puter.com', TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, 'graphics', '2020-01-01 00:00:00'),
  ('app-0bef044f-918f-4cbf-a0c0-b4a17ee81085', 1, NULL, 'about', 'About', 'About Puter', 'https://about.puter.com', TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, NULL, '2020-01-01 00:00:00'),
  ('app-a2ae72a4-1ba3-4a29-b5c0-6de1be5cf178', 1, NULL, 'app-center', 'App Center', 'Discover apps for Puter', 'https://app-center.puter.com', TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, NULL, '2020-01-01 00:00:00'),
  ('app-93005ce0-80d1-50d9-9b1e-9c453c375d56', 1, NULL, 'markus', 'Markus', 'Markdown editor', 'https://markus.puter.com', TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, 'productivity', '2020-01-01 00:00:00'),
  ('app-6f79ef7b-52b7-4b31-91c6-fc07b62e9396', 1, NULL, 'code', 'Code', 'Code editor', 'https://code.puter.com', TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, 'productivity', '2020-01-01 00:00:00'),
  ('app-862fc09e-c7b8-4c30-b5b4-47b3cc5f5232', 1, NULL, 'memos', 'Memos', 'Notes and memos', 'https://memos.puter.com', FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 'productivity', '2020-01-01 00:00:00'),
  ('app-aeb8c03e-1144-4c57-bff5-3a1a7c17f9f0', 1, NULL, 'word-processor', 'Word Processor', 'Write documents', 'https://word-processor.puter.com', FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 'productivity', '2020-01-01 00:00:00'),
  ('app-c10a1999-22f5-4644-9960-9aaac0d4934e', 1, NULL, 'spreadsheet', 'Spreadsheet', 'Work with spreadsheets', 'https://spreadsheet.puter.com', FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 'productivity', '2020-01-01 00:00:00'),
  ('app-e9c1d58d-3d8d-4f0a-a85c-e383ef63bc29', 1, NULL, 'presentation', 'Presentation', 'Create presentations', 'https://presentation.puter.com', FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 'productivity', '2020-01-01 00:00:00'),
  ('app-fb7d9e42-8207-4fa0-b680-f0239327097f', 1, NULL, 'pdf-editor', 'PDF Editor', 'Edit PDF documents', 'https://pdf-editor.puter.com', FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 'productivity', '2020-01-01 00:00:00')
ON CONFLICT (uid) DO UPDATE SET
  owner_user_id = EXCLUDED.owner_user_id,
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  index_url = EXCLUDED.index_url,
  godmode = EXCLUDED.godmode,
  maximize_on_start = EXCLUDED.maximize_on_start,
  background = EXCLUDED.background,
  approved_for_listing = EXCLUDED.approved_for_listing,
  approved_for_opening_items = EXCLUDED.approved_for_opening_items,
  approved_for_incentive_program = EXCLUDED.approved_for_incentive_program,
  tags = EXCLUDED.tags;

INSERT INTO user_to_group_permissions (user_id, group_id, permission, extra)
SELECT u.id, g.id, 'driver', '{}'::jsonb
FROM "user" u, "group" g
WHERE u.username = 'system'
  AND g.uid = 'ca342a5e-b13d-4dee-9048-58b11a57cc55'
ON CONFLICT (user_id, group_id, permission) DO UPDATE SET extra = EXCLUDED.extra;
