import type { ListPage, ListPaginationOptions, ListStreamOptions, RequestCallbacks } from '../shared.d.ts';

/** A user of an app, as returned by `App.users()` and `App.getUsers()`. */
export interface AppUser {
    /** The user's username. */
    username: string;
    /** The user's unique identifier. */
    user_uuid: string;
    /**
     * The user's email address. Only present when the user granted this app
     * the `user:<uuid>:email:read` permission (e.g. via
     * `puter.perms.requestEmail()`); omitted otherwise. May be `null` if the
     * user granted access but has no email on file.
     */
    user_email?: string | null;
}

/** Pagination options for `App.getUsers()`. */
export interface GetUsersOptions {
    /** The number of users to retrieve. Default is `100`. */
    limit?: number;
    /** The offset to start retrieving users from. Default is `0`. */
    offset?: number;
}

/** The `App` object containing Puter app details. */
export interface App {
    /** The unique identifier of the app, generated by Puter when the app is created. */
    uid: string;
    /** The name of the app. */
    name: string;
    /** The URL of the index file of the app, loaded when the app is started. */
    index_url: string;
    /** The title of the app. */
    title?: string;
    /** The description of the app. */
    description?: string;
    /** The Data URL of the icon of the app (a base64 encoded image). */
    icon?: string;
    /** Whether the app should be maximized when it is started. Default is `false`. */
    maximize_on_start?: boolean;
    /** Whether the app should run in the background. Default is `false`. */
    background?: boolean;
    /**
     * The file types that the app can open. Each string is in the format
     * `".<extension>"` or `"mime/type"`, e.g. `[".txt", "image/png"]`. For a
     * directory association, the string should be `.directory`.
     */
    filetype_associations?: string[];
    /** Custom metadata for the app as arbitrary key-value pairs. */
    metadata?: Record<string, unknown>;
    /** The date and time when the app was created, in `YYYY-MM-DDTHH:MM:SSZ` format. */
    created_at?: string;
    /**
     * The number of times the app has been opened. If `stats_period` is set to
     * a value other than `all`, this is the count within that period.
     */
    open_count?: number;
    /**
     * The number of users that have access to the app. If `stats_period` is set
     * to a value other than `all`, this is the count within that period.
     */
    user_count?: number;
    /**
     * Iterates over all users of the app, fetching them page by page.
     * @param pageSize - The number of users to retrieve per page. Default is 100.
     */
    users (pageSize?: number): AsyncIterableIterator<AppUser>;
    /**
     * Retrieves a list of users one page at a time as defined by limit and offset.
     * @param params - Pagination options.
     */
    getUsers (params?: GetUsersOptions): Promise<AppUser[]>;
}

/** The result returned by `Apps.create()`. */
export interface CreateAppResult {
    /** The unique identifier of the app, generated by Puter when the app is created. */
    uid: string;
    /** The name of the app. */
    name: string;
    /** The title of the app. */
    title: string;
    /** The URL of the index file of the app, loaded when the app is started. */
    index_url: string;
    /** The subdomain assigned to the app. */
    subdomain: string;
    /** Information about the owner of the app. */
    owner: {
        /** The username of the owner. */
        username: string;
        /** The unique identifier of the owner. */
        uuid: string;
    };
}

/** Options for `Apps.list()` and `Apps.get()`. */
export interface AppListOptions {
    /**
     * The period for which to get the user and open count. One of `today`,
     * `yesterday`, `7d`, `30d`, `this_month`, `last_month`, `this_year`,
     * `last_year`, `month_to_date`, `year_to_date`, or `last_12_months`.
     * Default is `all` (all time).
     */
    stats_period?: string;
    /** The size of the icons to return. Default is `null` (the original size). */
    icon_size?: null | 16 | 32 | 64 | 128 | 256 | 512;
}

/** Options for creating an app with `Apps.create()`. */
export interface CreateAppOptions {
    /**
     * The name of the app to create. Must be unique to the user's apps;
     * if an app with this name already exists the promise is rejected.
     */
    name: string;
    /**
     * The URL of the app's index page, displayed when the app is started.
     * Must start with `http://` or `https://`; other protocols are not allowed.
     */
    indexURL: string;
    /** The human-readable title of the app. Defaults to `name` if not provided. */
    title?: string;
    /** The description of the app aimed at the end user. */
    description?: string;
    /** The icon of the app. */
    icon?: string;
    /** Whether the app should be maximized when it is started. Defaults to `false`. */
    maximizeOnStart?: boolean;
    /** Whether the app should run in the background. Defaults to `false`. */
    background?: boolean;
    /**
     * The filetypes that the app can open. File extensions and MIME types are
     * supported, e.g. `[".txt", ".md", "application/pdf"]`. Defaults to `[]`.
     */
    filetypeAssociations?: string[];
    /** Custom metadata for the app as arbitrary key-value pairs. */
    metadata?: Record<string, unknown>;
    /** Whether to deduplicate the app name if it already exists. Defaults to `false`. */
    dedupeName?: boolean;
}

/** Attributes to update with `Apps.update()`. */
export interface UpdateAppAttributes {
    /**
     * The new name of the app. Must be unique to the user's apps; if an app
     * with this name already exists the promise is rejected.
     */
    name?: string;
    /** The new URL of the app's index page. Must be accessible to the user. */
    indexURL?: string;
    /** The new title of the app. */
    title?: string;
    /** The new description of the app aimed at the end user. */
    description?: string;
    /** The new icon of the app. */
    icon?: string;
    /** Whether the app should be maximized when it is started. Defaults to `false`. */
    maximizeOnStart?: boolean;
    /** Whether the app should run in the background. Defaults to `false`. */
    background?: boolean;
    /**
     * The filetypes that the app can open. File extensions and MIME types are
     * supported, e.g. `[".txt", ".md", "application/pdf"]`. Defaults to `[]`.
     */
    filetypeAssociations?: string[];
    /** Custom metadata for the app as arbitrary key-value pairs. */
    metadata?: Record<string, unknown>;
}

/** The result returned by `Apps.checkName()`. */
export interface CheckAppNameResult {
    /** The name that was checked. */
    name: string;
    /** Whether the name is available. */
    available: boolean;
}

/** Create, manage, and interact with applications in the Puter ecosystem. */
export class Apps {
    /**
     * Returns all apps belonging to the user that this app has access to,
     * fetching page by page under the hood. Resolves to an empty array if
     * the user has no apps. With `stream: true` it instead returns an async
     * iterator of pages for `for await ... of`; with `cursor` (even `null`),
     * `offset`, or `includeTotal` it resolves to a single page envelope.
     */
    list (options: AppListOptions & ListStreamOptions): AsyncIterableIterator<ListPage<App>>;
    list (options: AppListOptions & ListPaginationOptions & ({ cursor: string | null } | { offset: number } | { includeTotal: true })): Promise<ListPage<App>>;
    list (options?: AppListOptions & { limit?: number }): Promise<App[]>;
    /**
     * Creates a Puter app with the given name. The app name must be unique to
     * the user's apps; if one already exists the promise is rejected. `indexURL`
     * must start with `http://` or `https://`.
     */
    create (name: string, indexURL: string, title?: string): Promise<CreateAppResult>;
    create (options: CreateAppOptions): Promise<CreateAppResult>;
    /** Updates attributes of the app with the given name. */
    update (name: string, attributes: UpdateAppAttributes): Promise<App>;
    /** Returns the app with the given name. If the app does not exist, the promise is rejected. */
    get (name: string, options?: AppListOptions): Promise<App>;
    /**
     * Deletes the app with the given name. Resolves to `{ success: true, uid }`
     * with the `uid` of the deleted app.
     */
    delete (name: string): Promise<{ success: boolean; uid: string }>;
    checkName (name: string): Promise<CheckAppNameResult>;
    getDeveloperProfile (options?: RequestCallbacks<Record<string, unknown>>): Promise<Record<string, unknown>>;
    getDeveloperProfile (success: (value: Record<string, unknown>) => void, error?: (reason: unknown) => void): Promise<Record<string, unknown>>;
}
