export interface FileSignatureInfo {
    read_url?: string;
    write_url?: string;
    metadata_url?: string;
    fsentry_accessed?: number;
    fsentry_modified?: number;
    fsentry_created?: number;
    fsentry_is_dir?: boolean;
    fsentry_size?: number | null;
    fsentry_name?: string;
    path?: string;
    uid?: string;
}

export interface InternalFSProperties {
    signature?: string | null;
    expires?: string | null;
    file_signature: FileSignatureInfo;
}

/**
 * Represents a file or a directory in the Puter file system.
 */
export class FSItem {
    constructor (options: Record<string, unknown>);

    readURL?: string;
    writeURL?: string;
    metadataURL?: string;
    /** The name of the item. */
    name: string;
    uid: string;
    /** The unique identifier of the item, generated by Puter when the item is created. */
    id: string;
    uuid: string;
    /** The path of the item, relative to the root directory of the file system. */
    path: string;
    /** The size of the item in bytes. `null` if the item is a directory. */
    size: number | null;
    /** Unix timestamp of when the item was last accessed. */
    accessed?: number;
    /** Unix timestamp of when the item was last modified. */
    modified?: number;
    /** Unix timestamp of when the item was created. */
    created?: number;
    /** Whether the item is a directory. `true` for a directory, `false` for a file. */
    isDir: boolean;
    _internalProperties?: InternalFSProperties;

    /** Writes data to the file, overwriting its existing contents. Resolves to the written `FSItem`. */
    write (data: Blob | File | ArrayBuffer | ArrayBufferView | string): Promise<FSItem>;
    /** Renames the item. Resolves to the renamed `FSItem`. */
    rename (newName: string): Promise<FSItem>;
    move (destination: string, overwrite?: boolean, newName?: string): Promise<FSItem>;
    copy (destinationDirectory: string, autoRename?: boolean, overwrite?: boolean): Promise<FSItem>;
    /** Deletes the item. Resolves once the item has been deleted. */
    delete (): Promise<void>;
    /** Creates a new subdirectory inside the item. The item must be a directory, otherwise an error is thrown. Resolves to the created `FSItem`. */
    mkdir (name: string): Promise<FSItem>;
    /** Lists the contents of the item. The item must be a directory, otherwise an error is thrown. Resolves to an array of `FSItem` objects. */
    readdir (): Promise<FSItem[]>;
    /** Reads the contents of the file. Resolves to a `Blob` containing the file's contents. */
    read (): Promise<Blob>;

    // Placeholders that are not implemented in the runtime SDK yet.
    watch (callback: (item: FSItem) => void): void;
    open (callback: (item: FSItem) => void): void;
    setAsWallpaper (options?: Record<string, unknown>, callback?: () => void): void;
    versions (): Promise<unknown>;
    trash (): Promise<unknown>;
    metadata (): Promise<unknown>;
}
