/*
 * Copyright (C) 2024-present Puter Technologies Inc.
 *
 * This file is part of Puter.
 *
 * Puter is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { IVideoModel } from '../types.js';

interface ITogetherVideoModel extends IVideoModel {
    model: string;
    organization: string;
    durationSeconds: number[] | null;
    dimensions: string[] | null;
    fps: number[] | null;
    keyframes: string[] | null;
    promptLength: { min: number; max: number } | null;
    promptSupported: boolean | null;
}

export const TOGETHER_VIDEO_GENERATION_MODELS: ITogetherVideoModel[] = [
    {
        id: 'togetherai:minimax/video-01-director',
        puterId: 'togetherai:minimax/video-01-director',
        organization: 'MiniMax',
        name: 'MiniMax 01 Director',
        model: 'minimax/video-01-director',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 28 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: ['1366x768'],
        fps: [25],
        keyframes: ['first'],
        promptLength: { min: 2, max: 3000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:minimax/hailuo-02',
        puterId: 'togetherai:minimax/hailuo-02',
        organization: 'MiniMax',
        name: 'MiniMax Hailuo 02',
        model: 'minimax/hailuo-02',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 49 },
        output_cost_key: 'per-video',
        durationSeconds: [10],
        dimensions: ['1366x768', '1920x1080'],
        fps: [25],
        keyframes: ['first'],
        promptLength: { min: 2, max: 3000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:google/veo-2.0',
        puterId: 'togetherai:google/veo-2.0',
        organization: 'Google',
        name: 'Veo 2.0',
        model: 'google/veo-2.0',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 250 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: ['1280x720', '720x1280'],
        fps: [24],
        keyframes: ['first', 'last'],
        promptLength: { min: 2, max: 3000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:google/veo-3.0',
        puterId: 'togetherai:google/veo-3.0',
        organization: 'Google',
        name: 'Veo 3.0',
        model: 'google/veo-3.0',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 160 },
        output_cost_key: 'per-video',
        durationSeconds: [8],
        dimensions: ['1280x720', '720x1280', '1920x1080', '1080x1920'],
        fps: [24],
        keyframes: ['first'],
        promptLength: { min: 2, max: 3000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:google/veo-3.0-audio',
        puterId: 'togetherai:google/veo-3.0-audio',
        organization: 'Google',
        name: 'Veo 3.0 + Audio',
        model: 'google/veo-3.0-audio',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 320 },
        output_cost_key: 'per-video',
        durationSeconds: [8],
        dimensions: ['1280x720', '720x1280', '1920x1080', '1080x1920'],
        fps: [24],
        keyframes: ['first'],
        promptLength: { min: 2, max: 3000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:google/veo-3.0-fast',
        puterId: 'togetherai:google/veo-3.0-fast',
        organization: 'Google',
        name: 'Veo 3.0 Fast',
        model: 'google/veo-3.0-fast',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 80 },
        output_cost_key: 'per-video',
        durationSeconds: [8],
        dimensions: ['1280x720', '720x1280', '1920x1080', '1080x1920'],
        fps: [24],
        keyframes: ['first'],
        promptLength: { min: 2, max: 3000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:google/veo-3.0-fast-audio',
        puterId: 'togetherai:google/veo-3.0-fast-audio',
        organization: 'Google',
        name: 'Veo 3.0 Fast + Audio',
        model: 'google/veo-3.0-fast-audio',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 120 },
        output_cost_key: 'per-video',
        durationSeconds: [8],
        dimensions: ['1280x720', '720x1280', '1920x1080', '1080x1920'],
        fps: [24],
        keyframes: ['first'],
        promptLength: { min: 2, max: 3000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:ByteDance/Seedance-1.0-lite',
        puterId: 'togetherai:bytedance/seedance-1.0-lite',
        organization: 'ByteDance',
        name: 'Seedance 1.0 Lite',
        model: 'ByteDance/Seedance-1.0-lite',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 14 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: [
            '864x480',
            '736x544',
            '640x640',
            '960x416',
            '416x960',
            '1248x704',
            '1120x832',
            '960x960',
            '1504x640',
            '640x1504',
        ],
        fps: [24],
        keyframes: ['first', 'last'],
        promptLength: { min: 2, max: 3000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:ByteDance/Seedance-1.0-pro',
        puterId: 'togetherai:bytedance/seedance-1.0-pro',
        organization: 'ByteDance',
        name: 'Seedance 1.0 Pro',
        model: 'ByteDance/Seedance-1.0-pro',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 57 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: [
            '864x480',
            '736x544',
            '640x640',
            '960x416',
            '416x960',
            '1248x704',
            '1120x832',
            '960x960',
            '1504x640',
            '640x1504',
        ],
        fps: [24],
        keyframes: ['first', 'last'],
        promptLength: { min: 2, max: 3000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:pixverse/pixverse-v5',
        puterId: 'togetherai:pixverse/pixverse-v5',
        organization: 'PixVerse',
        name: 'PixVerse v5',
        model: 'pixverse/pixverse-v5',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 30 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: [
            '640x360',
            '480x360',
            '360x360',
            '270x360',
            '360x640',
            '960x540',
            '720x540',
            '540x540',
            '405x540',
            '540x960',
            '1280x720',
            '960x720',
            '720x720',
            '540x720',
            '720x1280',
            '1920x1080',
            '1440x1080',
            '1080x1080',
            '810x1080',
            '1080x1920',
        ],
        fps: [16, 24],
        keyframes: ['first', 'last'],
        promptLength: { min: 2, max: 2048 },
        promptSupported: true,
    },
    {
        id: 'togetherai:kwaivgI/kling-2.1-master',
        puterId: 'togetherai:kwaivgi/kling-2.1-master',
        organization: 'Kuaishou',
        name: 'Kling 2.1 Master',
        model: 'kwaivgI/kling-2.1-master',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 92 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: ['1920x1080', '1080x1080', '1080x1920'],
        fps: [24],
        keyframes: ['first'],
        promptLength: { min: 2, max: 2500 },
        promptSupported: true,
    },
    {
        id: 'togetherai:kwaivgI/kling-2.1-standard',
        puterId: 'togetherai:kwaivgi/kling-2.1-standard',
        organization: 'Kuaishou',
        name: 'Kling 2.1 Standard',
        model: 'kwaivgI/kling-2.1-standard',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 18 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: ['1920x1080', '1080x1080', '1080x1920'],
        fps: [24],
        keyframes: ['first'],
        promptLength: null,
        promptSupported: false,
    },
    {
        id: 'togetherai:kwaivgI/kling-2.1-pro',
        puterId: 'togetherai:kwaivgi/kling-2.1-pro',
        organization: 'Kuaishou',
        name: 'Kling 2.1 Pro',
        model: 'kwaivgI/kling-2.1-pro',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 32 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: ['1920x1080', '1080x1080', '1080x1920'],
        fps: [24],
        keyframes: ['first', 'last'],
        promptLength: null,
        promptSupported: false,
    },
    {
        id: 'togetherai:kwaivgI/kling-2.0-master',
        puterId: 'togetherai:kwaivgi/kling-2.0-master',
        organization: 'Kuaishou',
        name: 'Kling 2.0 Master',
        model: 'kwaivgI/kling-2.0-master',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 92 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: ['1280x720', '720x720', '720x1280'],
        fps: [24],
        keyframes: ['first'],
        promptLength: { min: 2, max: 2500 },
        promptSupported: true,
    },
    {
        id: 'togetherai:kwaivgI/kling-1.6-standard',
        puterId: 'togetherai:kwaivgi/kling-1.6-standard',
        organization: 'Kuaishou',
        name: 'Kling 1.6 Standard',
        model: 'kwaivgI/kling-1.6-standard',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 19 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: ['1920x1080', '1080x1080', '1080x1920'],
        fps: [30, 24],
        keyframes: ['first'],
        promptLength: { min: 2, max: 2500 },
        promptSupported: true,
    },
    {
        id: 'togetherai:kwaivgI/kling-1.6-pro',
        puterId: 'togetherai:kwaivgi/kling-1.6-pro',
        organization: 'Kuaishou',
        name: 'Kling 1.6 Pro',
        model: 'kwaivgI/kling-1.6-pro',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 32 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: ['1920x1080', '1080x1080', '1080x1920'],
        fps: [24],
        keyframes: ['first'],
        promptLength: null,
        promptSupported: false,
    },
    {
        id: 'togetherai:Wan-AI/Wan2.2-I2V-A14B',
        puterId: 'togetherai:wan-ai/wan2.2-i2v-a14b',
        organization: 'Wan-AI',
        name: 'Wan 2.2 I2V',
        model: 'Wan-AI/Wan2.2-I2V-A14B',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 31 },
        output_cost_key: 'per-video',
        durationSeconds: null,
        dimensions: null,
        fps: null,
        keyframes: null,
        promptLength: null,
        promptSupported: null,
    },
    {
        id: 'togetherai:Wan-AI/Wan2.2-T2V-A14B',
        puterId: 'togetherai:wan-ai/wan2.2-t2v-a14b',
        organization: 'Wan-AI',
        name: 'Wan 2.2 T2V',
        model: 'Wan-AI/Wan2.2-T2V-A14B',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 66 },
        output_cost_key: 'per-video',
        durationSeconds: null,
        dimensions: null,
        fps: null,
        keyframes: null,
        promptLength: null,
        promptSupported: null,
    },
    {
        id: 'togetherai:Wan-AI/wan2.7-t2v',
        puterId: 'togetherai:wan-ai/wan2.7-t2v',
        organization: 'Wan-AI',
        name: 'Wan 2.7 T2V',
        model: 'Wan-AI/wan2.7-t2v',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 10 },
        output_cost_key: 'per-video',
        durationSeconds: null,
        dimensions: null,
        fps: null,
        keyframes: null,
        promptLength: null,
        promptSupported: null,
    },
    {
        id: 'togetherai:vidu/vidu-2.0',
        puterId: 'togetherai:vidu/vidu-2.0',
        organization: 'Vidu',
        name: 'Vidu 2.0',
        model: 'vidu/vidu-2.0',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 28 },
        output_cost_key: 'per-video',
        durationSeconds: [8],
        dimensions: [
            '1920x1080',
            '1080x1080',
            '1080x1920',
            '1280x720',
            '720x720',
            '720x1280',
            '640x360',
            '360x360',
            '360x640',
        ],
        fps: [24],
        keyframes: ['first', 'last'],
        promptLength: { min: 2, max: 3000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:vidu/vidu-q1',
        puterId: 'togetherai:vidu/vidu-q1',
        organization: 'Vidu',
        name: 'Vidu Q1',
        model: 'vidu/vidu-q1',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 22 },
        output_cost_key: 'per-video',
        durationSeconds: [5],
        dimensions: ['1920x1080', '1080x1080', '1080x1920'],
        fps: [24],
        keyframes: ['first', 'last'],
        promptLength: { min: 2, max: 3000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:openai/sora-2',
        puterId: 'togetherai:openai/sora-2',
        organization: 'OpenAI',
        name: 'Sora 2',
        model: 'openai/sora-2',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 80 },
        output_cost_key: 'per-video',
        durationSeconds: [8],
        dimensions: ['1280x720', '720x1280'],
        fps: null,
        keyframes: ['first'],
        promptLength: { min: 1, max: 4000 },
        promptSupported: true,
    },
    {
        id: 'togetherai:openai/sora-2-pro',
        puterId: 'togetherai:openai/sora-2-pro',
        organization: 'OpenAI',
        name: 'Sora 2 Pro',
        model: 'openai/sora-2-pro',
        costs_currency: 'usd-cents',
        costs: { 'per-video': 300 },
        output_cost_key: 'per-video',
        durationSeconds: [8],
        dimensions: ['1280x720', '720x1280'],
        fps: null,
        keyframes: ['first'],
        promptLength: { min: 1, max: 4000 },
        promptSupported: true,
    },
];
