#!/usr/bin/env sh

files=$(git diff --cached --name-only --diff-filter=ACMR | \
  grep -E '^(src/backend|extensions)/.*\.(js|mjs|cjs|ts)$')

if [ -z "$files" ]; then
  exit 0
fi

echo "$files" | xargs npx eslint --fix --no-warn-ignored
status=$?

echo "$files" | xargs git add

exit $status
