// TODO DS: centralize somewhere

import type { IChatModel } from '../../types.js';

// Hardcoded from https://models.dev/api.json
export const OPEN_AI_MODELS: IChatModel[] = [
    {
        puterId: 'openai:openai/gpt-5.5',
        id: 'gpt-5.5-2026-04-23',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-12-01',
        release_date: '2026-04-23',
        aliases: ['gpt-5.5', 'openai/gpt-5.5'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 500,
            cached_tokens: 50,
            completion_tokens: 3000,
        },
        context: 1_050_000,
        max_tokens: 128_000,
    },
    {
        puterId: 'openai:openai/gpt-5.5-pro',
        id: 'gpt-5.5-pro-2026-04-23',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-12-01',
        release_date: '2026-04-23',
        aliases: ['gpt-5.5-pro', 'openai/gpt-5.5-pro'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 3000,
            cached_tokens: 3000, // there is no cache actually. This is here for safety
            completion_tokens: 18000,
        },
        context: 1_050_000,
        max_tokens: 128_000,
        responses_api_only: true,
    },
    {
        puterId: 'openai:openai/gpt-5.4',
        id: 'gpt-5.4-2026-03-05',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-08-31',
        release_date: '2026-03-05',
        aliases: ['gpt-5.4', 'openai/gpt-5.4'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 250,
            cached_tokens: 25,
            completion_tokens: 1500,
        },
        context: 1_050_000,
        max_tokens: 1_050_000,
    },
    {
        puterId: 'openai:openai/gpt-5.3-codex',
        id: 'gpt-5.3-codex',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-08-31',
        aliases: ['openai/gpt-5.3-codex'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 175,
            cached_tokens: 17.5,
            completion_tokens: 1400,
        },
        context: 128_000,
        max_tokens: 128000,
        responses_api_only: true,
    },
    {
        puterId: 'openai:openai/gpt-5.2-codex',
        id: 'gpt-5.2-codex',
        modalities: { input: ['text', 'image', 'pdf'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-08-31',
        release_date: '2025-12-11',
        aliases: ['openai/gpt-5.2-codex'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 175,
            cached_tokens: 18,
            completion_tokens: 1400,
        },
        context: 128_000,
        max_tokens: 128000,
        responses_api_only: true,
    },
    {
        puterId: 'openai:openai/gpt-5.2-chat',
        id: 'gpt-5.2-chat-latest',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-08-31',
        release_date: '2025-12-11',
        aliases: ['gpt-5.2-chat', 'openai/gpt-5.2-chat'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 175,
            cached_tokens: 17.5,
            completion_tokens: 1400,
        },
        context: 128_000,
        max_tokens: 16384,
    },
    {
        puterId: 'openai:openai/gpt-5.2-pro',
        id: 'gpt-5.2-pro-2025-12-11',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-08-31',
        release_date: '2025-12-11',
        aliases: ['gpt-5.2-pro', 'openai/gpt-5.2-pro'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 2100,
            completion_tokens: 16800,
        },
        context: 128_000,
        max_tokens: 16384,
        responses_api_only: true,
    },
    {
        puterId: 'openai:openai/gpt-5.2',
        id: 'gpt-5.2-2025-12-11',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2025-08-31',
        release_date: '2025-12-11',
        aliases: ['gpt-5.2', 'openai/gpt-5.2'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 175,
            cached_tokens: 17.5,
            completion_tokens: 1400,
        },
        context: 128_000,
        max_tokens: 128000,
    },
    {
        puterId: 'openai:openai/gpt-5.1',
        id: 'gpt-5.1',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-09-30',
        release_date: '2025-11-13',
        aliases: ['openai/gpt-5.1'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 125,
            cached_tokens: 13,
            completion_tokens: 1000,
        },
        context: 128_000,
        max_tokens: 128000,
    },
    {
        puterId: 'openai:openai/gpt-5.1-codex',
        id: 'gpt-5.1-codex',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-09-30',
        release_date: '2025-11-13',
        aliases: ['openai/gpt-5.1-codex'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 125,
            cached_tokens: 13,
            completion_tokens: 1000,
        },
        context: 128_000,
        max_tokens: 128000,
        responses_api_only: true,
    },
    {
        puterId: 'openai:openai/gpt-5.1-codex-mini',
        id: 'gpt-5.1-codex-mini',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-09-30',
        release_date: '2025-11-13',
        aliases: ['openai/gpt-5.1-codex-mini'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 25,
            cached_tokens: 3,
            completion_tokens: 200,
        },
        context: 128_000,
        max_tokens: 128000,
        responses_api_only: true,
    },
    {
        puterId: 'openai:openai/gpt-5.1-chat',
        id: 'gpt-5.1-chat-latest',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-09-30',
        release_date: '2025-11-13',
        aliases: ['openai/gpt-5.1-chat'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 125,
            cached_tokens: 13,
            completion_tokens: 1000,
        },
        context: 128_000,
        max_tokens: 16384,
    },
    {
        puterId: 'openai:openai/gpt-5',
        id: 'gpt-5-2025-08-07',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-09-30',
        release_date: '2025-08-07',
        aliases: ['gpt-5', 'openai/gpt-5'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 125,
            cached_tokens: 13,
            completion_tokens: 1000,
        },
        context: 128_000,
        max_tokens: 128000,
    },
    {
        puterId: 'openai:openai/gpt-5-mini',
        id: 'gpt-5-mini-2025-08-07',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-05-30',
        release_date: '2025-08-07',
        aliases: ['gpt-5-mini', 'openai/gpt-5-mini'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 25,
            cached_tokens: 3,
            completion_tokens: 200,
        },
        context: 128_000,
        max_tokens: 128000,
    },
    {
        puterId: 'openai:openai/gpt-5-nano',
        id: 'gpt-5-nano-2025-08-07',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-05-30',
        release_date: '2025-08-07',
        aliases: ['gpt-5-nano', 'openai/gpt-5-nano'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 5,
            cached_tokens: 1,
            completion_tokens: 40,
        },
        context: 128_000,
        max_tokens: 128000,
    },
    {
        puterId: 'openai:openai/gpt-5-chat',
        id: 'gpt-5-chat-latest',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: false,
        knowledge: '2024-09-30',
        release_date: '2025-08-07',
        aliases: ['openai/gpt-5-chat'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 125,
            cached_tokens: 13,
            completion_tokens: 1000,
        },
        context: 128_000,
        max_tokens: 16384,
    },
    {
        puterId: 'openai:openai/gpt-4o',
        id: 'gpt-4o',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2023-09',
        release_date: '2024-05-13',
        aliases: ['openai/gpt-4o'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 250,
            cached_tokens: 125,
            completion_tokens: 1000,
        },
        context: 128_000,
        max_tokens: 16384,
    },
    {
        puterId: 'openai:openai/gpt-4o-mini',
        id: 'gpt-4o-mini',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2023-09',
        release_date: '2024-07-18',
        aliases: ['openai/gpt-4o-mini'],
        context: 128_000,
        max_tokens: 16384,
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 15,
            cached_tokens: 8,
            completion_tokens: 60,
        },
    },
    {
        puterId: 'openai:openai/o1',
        id: 'o1',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2023-09',
        release_date: '2024-12-05',
        aliases: ['openai/o1'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 1500,
            cached_tokens: 750,
            completion_tokens: 6000,
        },
        context: 200_000,
        max_tokens: 100000,
    },
    {
        puterId: 'openai:openai/o1-mini',
        id: 'o1-mini',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: false,
        knowledge: '2023-09',
        release_date: '2024-09-12',
        aliases: ['openai/o1-mini'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 110,
            completion_tokens: 440,
        },
        context: 128_000,
        max_tokens: 65536,
    },
    {
        puterId: 'openai:openai/o1-pro',
        id: 'o1-pro',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2023-09',
        release_date: '2025-03-19',
        aliases: ['openai/o1-pro'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 15000,
            completion_tokens: 60000,
        },
        context: 200_000,
        max_tokens: 100000,
    },
    {
        puterId: 'openai:openai/o3',
        id: 'o3',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-05',
        release_date: '2025-04-16',
        aliases: ['openai/o3'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 200,
            cached_tokens: 50,
            completion_tokens: 800,
        },
        context: 200_000,
        max_tokens: 100000,
    },
    {
        puterId: 'openai:openai/o3-pro',
        id: 'o3-pro',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-05',
        release_date: '2025-06-10',
        aliases: ['openai/o3-pro'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 2000,
            cached_tokens: 50,
            completion_tokens: 8000,
        },
        context: 200_000,
        max_tokens: 100000,
        responses_api_only: true,
    },
    {
        puterId: 'openai:openai/o3-mini',
        id: 'o3-mini',
        modalities: { input: ['text'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-05',
        release_date: '2024-12-20',
        aliases: ['openai/o3-mini'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 110,
            cached_tokens: 55,
            completion_tokens: 440,
        },
        context: 200_000,
        max_tokens: 100000,
    },
    {
        puterId: 'openai:openai/o4-mini',
        id: 'o4-mini',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-05',
        release_date: '2025-04-16',
        aliases: ['openai/o4-mini'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 110,
            completion_tokens: 440,
        },
        context: 200_000,
        max_tokens: 100000,
    },
    {
        puterId: 'openai:openai/gpt-4.1',
        id: 'gpt-4.1',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2025-04-14',
        aliases: ['openai/gpt-4.1'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 200,
            cached_tokens: 50,
            completion_tokens: 800,
        },
        context: 1_047_576,
        max_tokens: 32768,
    },
    {
        puterId: 'openai:openai/gpt-4.1-mini',
        id: 'gpt-4.1-mini',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2025-04-14',
        aliases: ['openai/gpt-4.1-mini'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 40,
            cached_tokens: 10,
            completion_tokens: 160,
        },
        context: 1_047_576,
        max_tokens: 32768,
    },
    {
        puterId: 'openai:openai/gpt-4.1-nano',
        id: 'gpt-4.1-nano',
        modalities: { input: ['text', 'image'], output: ['text'] },
        open_weights: false,
        tool_call: true,
        knowledge: '2024-04',
        release_date: '2025-04-14',
        aliases: ['openai/gpt-4.1-nano'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 10,
            cached_tokens: 2,
            completion_tokens: 40,
        },
        context: 1_047_576,
        max_tokens: 32768,
    },
    {
        puterId: 'openai:openai/gpt-4.5-preview',
        id: 'gpt-4.5-preview',
        aliases: ['openai/gpt-4.5-preview'],
        costs_currency: 'usd-cents',
        input_cost_key: 'prompt_tokens',
        output_cost_key: 'completion_tokens',
        costs: {
            tokens: 1_000_000,
            prompt_tokens: 7500,
            completion_tokens: 15000,
        },
        context: 128_000,
        max_tokens: 32768,
    },
];
